// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountfinancecountersnapshot"
	"github.com/Wei-Shaw/sub2api/ent/accountfinanceprofile"
	"github.com/Wei-Shaw/sub2api/ent/accountgroup"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreammultiplierchange"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementread"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/authidentity"
	"github.com/Wei-Shaw/sub2api/ent/authidentitychannel"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitor"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitordailyrollup"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitorhistory"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitorrequesttemplate"
	"github.com/Wei-Shaw/sub2api/ent/errorpassthroughrule"
	"github.com/Wei-Shaw/sub2api/ent/financealert"
	"github.com/Wei-Shaw/sub2api/ent/financeasyncjob"
	"github.com/Wei-Shaw/sub2api/ent/financebackfilljob"
	"github.com/Wei-Shaw/sub2api/ent/financecalculationrevision"
	"github.com/Wei-Shaw/sub2api/ent/financedailyaggregate"
	"github.com/Wei-Shaw/sub2api/ent/financeexportjob"
	"github.com/Wei-Shaw/sub2api/ent/financefxrateversion"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/idempotencyrecord"
	"github.com/Wei-Shaw/sub2api/ent/identityadoptiondecision"
	"github.com/Wei-Shaw/sub2api/ent/paymentauditlog"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentproviderfeeevent"
	"github.com/Wei-Shaw/sub2api/ent/paymentproviderinstance"
	"github.com/Wei-Shaw/sub2api/ent/pendingauthsession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/promocode"
	"github.com/Wei-Shaw/sub2api/ent/promocodeusage"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/securitysecret"
	"github.com/Wei-Shaw/sub2api/ent/setting"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrevenuerecognition"
	"github.com/Wei-Shaw/sub2api/ent/systemmodelpriceversion"
	"github.com/Wei-Shaw/sub2api/ent/tlsfingerprintprofile"
	"github.com/Wei-Shaw/sub2api/ent/upstreambalancesnapshot"
	"github.com/Wei-Shaw/sub2api/ent/upstreambillreconciliation"
	"github.com/Wei-Shaw/sub2api/ent/upstreamcostsettlementinterval"
	"github.com/Wei-Shaw/sub2api/ent/upstreamfinanceprotocol"
	"github.com/Wei-Shaw/sub2api/ent/upstreamfinanceprotocolversion"
	"github.com/Wei-Shaw/sub2api/ent/upstreamfinancesyncrun"
	"github.com/Wei-Shaw/sub2api/ent/upstreamfundevent"
	"github.com/Wei-Shaw/sub2api/ent/upstreammodelpriceversion"
	"github.com/Wei-Shaw/sub2api/ent/upstreamwallet"
	"github.com/Wei-Shaw/sub2api/ent/upstreamwalletaccount"
	"github.com/Wei-Shaw/sub2api/ent/usagecleanuptask"
	"github.com/Wei-Shaw/sub2api/ent/usagecostsettlementallocation"
	"github.com/Wei-Shaw/sub2api/ent/usagefinancecostsegment"
	"github.com/Wei-Shaw/sub2api/ent/usagefinancerecord"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/usagerevenueallocation"
	"github.com/Wei-Shaw/sub2api/ent/usageupstreamattempt"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userallowedgroup"
	"github.com/Wei-Shaw/sub2api/ent/userattributedefinition"
	"github.com/Wei-Shaw/sub2api/ent/userattributevalue"
	"github.com/Wei-Shaw/sub2api/ent/userplatformquota"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The APIKeyFunc type is an adapter to allow the use of ordinary function as a Querier.
type APIKeyFunc func(context.Context, *ent.APIKeyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f APIKeyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.APIKeyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.APIKeyQuery", q)
}

// The TraverseAPIKey type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAPIKey func(context.Context, *ent.APIKeyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAPIKey) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAPIKey) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.APIKeyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.APIKeyQuery", q)
}

// The AccountFunc type is an adapter to allow the use of ordinary function as a Querier.
type AccountFunc func(context.Context, *ent.AccountQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AccountFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AccountQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AccountQuery", q)
}

// The TraverseAccount type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAccount func(context.Context, *ent.AccountQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAccount) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAccount) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AccountQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AccountQuery", q)
}

// The AccountFinanceCounterSnapshotFunc type is an adapter to allow the use of ordinary function as a Querier.
type AccountFinanceCounterSnapshotFunc func(context.Context, *ent.AccountFinanceCounterSnapshotQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AccountFinanceCounterSnapshotFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AccountFinanceCounterSnapshotQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AccountFinanceCounterSnapshotQuery", q)
}

// The TraverseAccountFinanceCounterSnapshot type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAccountFinanceCounterSnapshot func(context.Context, *ent.AccountFinanceCounterSnapshotQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAccountFinanceCounterSnapshot) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAccountFinanceCounterSnapshot) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AccountFinanceCounterSnapshotQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AccountFinanceCounterSnapshotQuery", q)
}

// The AccountFinanceProfileFunc type is an adapter to allow the use of ordinary function as a Querier.
type AccountFinanceProfileFunc func(context.Context, *ent.AccountFinanceProfileQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AccountFinanceProfileFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AccountFinanceProfileQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AccountFinanceProfileQuery", q)
}

// The TraverseAccountFinanceProfile type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAccountFinanceProfile func(context.Context, *ent.AccountFinanceProfileQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAccountFinanceProfile) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAccountFinanceProfile) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AccountFinanceProfileQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AccountFinanceProfileQuery", q)
}

// The AccountGroupFunc type is an adapter to allow the use of ordinary function as a Querier.
type AccountGroupFunc func(context.Context, *ent.AccountGroupQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AccountGroupFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AccountGroupQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AccountGroupQuery", q)
}

// The TraverseAccountGroup type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAccountGroup func(context.Context, *ent.AccountGroupQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAccountGroup) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAccountGroup) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AccountGroupQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AccountGroupQuery", q)
}

// The AccountUpstreamMultiplierChangeFunc type is an adapter to allow the use of ordinary function as a Querier.
type AccountUpstreamMultiplierChangeFunc func(context.Context, *ent.AccountUpstreamMultiplierChangeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AccountUpstreamMultiplierChangeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AccountUpstreamMultiplierChangeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AccountUpstreamMultiplierChangeQuery", q)
}

// The TraverseAccountUpstreamMultiplierChange type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAccountUpstreamMultiplierChange func(context.Context, *ent.AccountUpstreamMultiplierChangeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAccountUpstreamMultiplierChange) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAccountUpstreamMultiplierChange) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AccountUpstreamMultiplierChangeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AccountUpstreamMultiplierChangeQuery", q)
}

// The AnnouncementFunc type is an adapter to allow the use of ordinary function as a Querier.
type AnnouncementFunc func(context.Context, *ent.AnnouncementQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AnnouncementFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AnnouncementQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AnnouncementQuery", q)
}

// The TraverseAnnouncement type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAnnouncement func(context.Context, *ent.AnnouncementQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAnnouncement) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAnnouncement) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AnnouncementQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AnnouncementQuery", q)
}

// The AnnouncementReadFunc type is an adapter to allow the use of ordinary function as a Querier.
type AnnouncementReadFunc func(context.Context, *ent.AnnouncementReadQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AnnouncementReadFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AnnouncementReadQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AnnouncementReadQuery", q)
}

// The TraverseAnnouncementRead type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAnnouncementRead func(context.Context, *ent.AnnouncementReadQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAnnouncementRead) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAnnouncementRead) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AnnouncementReadQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AnnouncementReadQuery", q)
}

// The AuthIdentityFunc type is an adapter to allow the use of ordinary function as a Querier.
type AuthIdentityFunc func(context.Context, *ent.AuthIdentityQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AuthIdentityFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AuthIdentityQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AuthIdentityQuery", q)
}

// The TraverseAuthIdentity type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAuthIdentity func(context.Context, *ent.AuthIdentityQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAuthIdentity) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAuthIdentity) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AuthIdentityQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AuthIdentityQuery", q)
}

// The AuthIdentityChannelFunc type is an adapter to allow the use of ordinary function as a Querier.
type AuthIdentityChannelFunc func(context.Context, *ent.AuthIdentityChannelQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AuthIdentityChannelFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AuthIdentityChannelQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AuthIdentityChannelQuery", q)
}

// The TraverseAuthIdentityChannel type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAuthIdentityChannel func(context.Context, *ent.AuthIdentityChannelQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAuthIdentityChannel) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAuthIdentityChannel) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AuthIdentityChannelQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AuthIdentityChannelQuery", q)
}

// The ChannelMonitorFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelMonitorFunc func(context.Context, *ent.ChannelMonitorQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelMonitorFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelMonitorQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorQuery", q)
}

// The TraverseChannelMonitor type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelMonitor func(context.Context, *ent.ChannelMonitorQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelMonitor) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelMonitor) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelMonitorQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorQuery", q)
}

// The ChannelMonitorDailyRollupFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelMonitorDailyRollupFunc func(context.Context, *ent.ChannelMonitorDailyRollupQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelMonitorDailyRollupFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelMonitorDailyRollupQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorDailyRollupQuery", q)
}

// The TraverseChannelMonitorDailyRollup type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelMonitorDailyRollup func(context.Context, *ent.ChannelMonitorDailyRollupQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelMonitorDailyRollup) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelMonitorDailyRollup) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelMonitorDailyRollupQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorDailyRollupQuery", q)
}

// The ChannelMonitorHistoryFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelMonitorHistoryFunc func(context.Context, *ent.ChannelMonitorHistoryQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelMonitorHistoryFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelMonitorHistoryQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorHistoryQuery", q)
}

// The TraverseChannelMonitorHistory type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelMonitorHistory func(context.Context, *ent.ChannelMonitorHistoryQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelMonitorHistory) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelMonitorHistory) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelMonitorHistoryQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorHistoryQuery", q)
}

// The ChannelMonitorRequestTemplateFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelMonitorRequestTemplateFunc func(context.Context, *ent.ChannelMonitorRequestTemplateQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelMonitorRequestTemplateFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelMonitorRequestTemplateQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorRequestTemplateQuery", q)
}

// The TraverseChannelMonitorRequestTemplate type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelMonitorRequestTemplate func(context.Context, *ent.ChannelMonitorRequestTemplateQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelMonitorRequestTemplate) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelMonitorRequestTemplate) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelMonitorRequestTemplateQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorRequestTemplateQuery", q)
}

// The ErrorPassthroughRuleFunc type is an adapter to allow the use of ordinary function as a Querier.
type ErrorPassthroughRuleFunc func(context.Context, *ent.ErrorPassthroughRuleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ErrorPassthroughRuleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ErrorPassthroughRuleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ErrorPassthroughRuleQuery", q)
}

// The TraverseErrorPassthroughRule type is an adapter to allow the use of ordinary function as Traverser.
type TraverseErrorPassthroughRule func(context.Context, *ent.ErrorPassthroughRuleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseErrorPassthroughRule) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseErrorPassthroughRule) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ErrorPassthroughRuleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ErrorPassthroughRuleQuery", q)
}

// The FinanceAlertFunc type is an adapter to allow the use of ordinary function as a Querier.
type FinanceAlertFunc func(context.Context, *ent.FinanceAlertQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f FinanceAlertFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.FinanceAlertQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.FinanceAlertQuery", q)
}

// The TraverseFinanceAlert type is an adapter to allow the use of ordinary function as Traverser.
type TraverseFinanceAlert func(context.Context, *ent.FinanceAlertQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFinanceAlert) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFinanceAlert) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.FinanceAlertQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.FinanceAlertQuery", q)
}

// The FinanceAsyncJobFunc type is an adapter to allow the use of ordinary function as a Querier.
type FinanceAsyncJobFunc func(context.Context, *ent.FinanceAsyncJobQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f FinanceAsyncJobFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.FinanceAsyncJobQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.FinanceAsyncJobQuery", q)
}

// The TraverseFinanceAsyncJob type is an adapter to allow the use of ordinary function as Traverser.
type TraverseFinanceAsyncJob func(context.Context, *ent.FinanceAsyncJobQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFinanceAsyncJob) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFinanceAsyncJob) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.FinanceAsyncJobQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.FinanceAsyncJobQuery", q)
}

// The FinanceBackfillJobFunc type is an adapter to allow the use of ordinary function as a Querier.
type FinanceBackfillJobFunc func(context.Context, *ent.FinanceBackfillJobQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f FinanceBackfillJobFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.FinanceBackfillJobQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.FinanceBackfillJobQuery", q)
}

// The TraverseFinanceBackfillJob type is an adapter to allow the use of ordinary function as Traverser.
type TraverseFinanceBackfillJob func(context.Context, *ent.FinanceBackfillJobQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFinanceBackfillJob) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFinanceBackfillJob) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.FinanceBackfillJobQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.FinanceBackfillJobQuery", q)
}

// The FinanceCalculationRevisionFunc type is an adapter to allow the use of ordinary function as a Querier.
type FinanceCalculationRevisionFunc func(context.Context, *ent.FinanceCalculationRevisionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f FinanceCalculationRevisionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.FinanceCalculationRevisionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.FinanceCalculationRevisionQuery", q)
}

// The TraverseFinanceCalculationRevision type is an adapter to allow the use of ordinary function as Traverser.
type TraverseFinanceCalculationRevision func(context.Context, *ent.FinanceCalculationRevisionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFinanceCalculationRevision) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFinanceCalculationRevision) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.FinanceCalculationRevisionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.FinanceCalculationRevisionQuery", q)
}

// The FinanceDailyAggregateFunc type is an adapter to allow the use of ordinary function as a Querier.
type FinanceDailyAggregateFunc func(context.Context, *ent.FinanceDailyAggregateQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f FinanceDailyAggregateFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.FinanceDailyAggregateQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.FinanceDailyAggregateQuery", q)
}

// The TraverseFinanceDailyAggregate type is an adapter to allow the use of ordinary function as Traverser.
type TraverseFinanceDailyAggregate func(context.Context, *ent.FinanceDailyAggregateQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFinanceDailyAggregate) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFinanceDailyAggregate) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.FinanceDailyAggregateQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.FinanceDailyAggregateQuery", q)
}

// The FinanceExportJobFunc type is an adapter to allow the use of ordinary function as a Querier.
type FinanceExportJobFunc func(context.Context, *ent.FinanceExportJobQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f FinanceExportJobFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.FinanceExportJobQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.FinanceExportJobQuery", q)
}

// The TraverseFinanceExportJob type is an adapter to allow the use of ordinary function as Traverser.
type TraverseFinanceExportJob func(context.Context, *ent.FinanceExportJobQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFinanceExportJob) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFinanceExportJob) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.FinanceExportJobQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.FinanceExportJobQuery", q)
}

// The FinanceFXRateVersionFunc type is an adapter to allow the use of ordinary function as a Querier.
type FinanceFXRateVersionFunc func(context.Context, *ent.FinanceFXRateVersionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f FinanceFXRateVersionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.FinanceFXRateVersionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.FinanceFXRateVersionQuery", q)
}

// The TraverseFinanceFXRateVersion type is an adapter to allow the use of ordinary function as Traverser.
type TraverseFinanceFXRateVersion func(context.Context, *ent.FinanceFXRateVersionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFinanceFXRateVersion) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFinanceFXRateVersion) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.FinanceFXRateVersionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.FinanceFXRateVersionQuery", q)
}

// The GroupFunc type is an adapter to allow the use of ordinary function as a Querier.
type GroupFunc func(context.Context, *ent.GroupQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f GroupFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.GroupQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.GroupQuery", q)
}

// The TraverseGroup type is an adapter to allow the use of ordinary function as Traverser.
type TraverseGroup func(context.Context, *ent.GroupQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseGroup) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseGroup) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.GroupQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.GroupQuery", q)
}

// The IdempotencyRecordFunc type is an adapter to allow the use of ordinary function as a Querier.
type IdempotencyRecordFunc func(context.Context, *ent.IdempotencyRecordQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f IdempotencyRecordFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.IdempotencyRecordQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.IdempotencyRecordQuery", q)
}

// The TraverseIdempotencyRecord type is an adapter to allow the use of ordinary function as Traverser.
type TraverseIdempotencyRecord func(context.Context, *ent.IdempotencyRecordQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseIdempotencyRecord) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseIdempotencyRecord) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.IdempotencyRecordQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.IdempotencyRecordQuery", q)
}

// The IdentityAdoptionDecisionFunc type is an adapter to allow the use of ordinary function as a Querier.
type IdentityAdoptionDecisionFunc func(context.Context, *ent.IdentityAdoptionDecisionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f IdentityAdoptionDecisionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.IdentityAdoptionDecisionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.IdentityAdoptionDecisionQuery", q)
}

// The TraverseIdentityAdoptionDecision type is an adapter to allow the use of ordinary function as Traverser.
type TraverseIdentityAdoptionDecision func(context.Context, *ent.IdentityAdoptionDecisionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseIdentityAdoptionDecision) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseIdentityAdoptionDecision) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.IdentityAdoptionDecisionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.IdentityAdoptionDecisionQuery", q)
}

// The PaymentAuditLogFunc type is an adapter to allow the use of ordinary function as a Querier.
type PaymentAuditLogFunc func(context.Context, *ent.PaymentAuditLogQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PaymentAuditLogFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PaymentAuditLogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PaymentAuditLogQuery", q)
}

// The TraversePaymentAuditLog type is an adapter to allow the use of ordinary function as Traverser.
type TraversePaymentAuditLog func(context.Context, *ent.PaymentAuditLogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePaymentAuditLog) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePaymentAuditLog) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PaymentAuditLogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PaymentAuditLogQuery", q)
}

// The PaymentOrderFunc type is an adapter to allow the use of ordinary function as a Querier.
type PaymentOrderFunc func(context.Context, *ent.PaymentOrderQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PaymentOrderFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PaymentOrderQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PaymentOrderQuery", q)
}

// The TraversePaymentOrder type is an adapter to allow the use of ordinary function as Traverser.
type TraversePaymentOrder func(context.Context, *ent.PaymentOrderQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePaymentOrder) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePaymentOrder) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PaymentOrderQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PaymentOrderQuery", q)
}

// The PaymentProviderFeeEventFunc type is an adapter to allow the use of ordinary function as a Querier.
type PaymentProviderFeeEventFunc func(context.Context, *ent.PaymentProviderFeeEventQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PaymentProviderFeeEventFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PaymentProviderFeeEventQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PaymentProviderFeeEventQuery", q)
}

// The TraversePaymentProviderFeeEvent type is an adapter to allow the use of ordinary function as Traverser.
type TraversePaymentProviderFeeEvent func(context.Context, *ent.PaymentProviderFeeEventQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePaymentProviderFeeEvent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePaymentProviderFeeEvent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PaymentProviderFeeEventQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PaymentProviderFeeEventQuery", q)
}

// The PaymentProviderInstanceFunc type is an adapter to allow the use of ordinary function as a Querier.
type PaymentProviderInstanceFunc func(context.Context, *ent.PaymentProviderInstanceQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PaymentProviderInstanceFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PaymentProviderInstanceQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PaymentProviderInstanceQuery", q)
}

// The TraversePaymentProviderInstance type is an adapter to allow the use of ordinary function as Traverser.
type TraversePaymentProviderInstance func(context.Context, *ent.PaymentProviderInstanceQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePaymentProviderInstance) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePaymentProviderInstance) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PaymentProviderInstanceQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PaymentProviderInstanceQuery", q)
}

// The PendingAuthSessionFunc type is an adapter to allow the use of ordinary function as a Querier.
type PendingAuthSessionFunc func(context.Context, *ent.PendingAuthSessionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PendingAuthSessionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PendingAuthSessionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PendingAuthSessionQuery", q)
}

// The TraversePendingAuthSession type is an adapter to allow the use of ordinary function as Traverser.
type TraversePendingAuthSession func(context.Context, *ent.PendingAuthSessionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePendingAuthSession) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePendingAuthSession) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PendingAuthSessionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PendingAuthSessionQuery", q)
}

// The PromoCodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type PromoCodeFunc func(context.Context, *ent.PromoCodeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PromoCodeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PromoCodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PromoCodeQuery", q)
}

// The TraversePromoCode type is an adapter to allow the use of ordinary function as Traverser.
type TraversePromoCode func(context.Context, *ent.PromoCodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePromoCode) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePromoCode) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PromoCodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PromoCodeQuery", q)
}

// The PromoCodeUsageFunc type is an adapter to allow the use of ordinary function as a Querier.
type PromoCodeUsageFunc func(context.Context, *ent.PromoCodeUsageQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PromoCodeUsageFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PromoCodeUsageQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PromoCodeUsageQuery", q)
}

// The TraversePromoCodeUsage type is an adapter to allow the use of ordinary function as Traverser.
type TraversePromoCodeUsage func(context.Context, *ent.PromoCodeUsageQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePromoCodeUsage) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePromoCodeUsage) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PromoCodeUsageQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PromoCodeUsageQuery", q)
}

// The ProxyFunc type is an adapter to allow the use of ordinary function as a Querier.
type ProxyFunc func(context.Context, *ent.ProxyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ProxyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ProxyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ProxyQuery", q)
}

// The TraverseProxy type is an adapter to allow the use of ordinary function as Traverser.
type TraverseProxy func(context.Context, *ent.ProxyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseProxy) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseProxy) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ProxyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ProxyQuery", q)
}

// The RedeemCodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type RedeemCodeFunc func(context.Context, *ent.RedeemCodeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RedeemCodeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RedeemCodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RedeemCodeQuery", q)
}

// The TraverseRedeemCode type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRedeemCode func(context.Context, *ent.RedeemCodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRedeemCode) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRedeemCode) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RedeemCodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RedeemCodeQuery", q)
}

// The SecuritySecretFunc type is an adapter to allow the use of ordinary function as a Querier.
type SecuritySecretFunc func(context.Context, *ent.SecuritySecretQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SecuritySecretFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SecuritySecretQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SecuritySecretQuery", q)
}

// The TraverseSecuritySecret type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSecuritySecret func(context.Context, *ent.SecuritySecretQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSecuritySecret) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSecuritySecret) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SecuritySecretQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SecuritySecretQuery", q)
}

// The SettingFunc type is an adapter to allow the use of ordinary function as a Querier.
type SettingFunc func(context.Context, *ent.SettingQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SettingFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SettingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SettingQuery", q)
}

// The TraverseSetting type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSetting func(context.Context, *ent.SettingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSetting) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSetting) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SettingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SettingQuery", q)
}

// The SubscriptionPlanFunc type is an adapter to allow the use of ordinary function as a Querier.
type SubscriptionPlanFunc func(context.Context, *ent.SubscriptionPlanQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SubscriptionPlanFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SubscriptionPlanQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SubscriptionPlanQuery", q)
}

// The TraverseSubscriptionPlan type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSubscriptionPlan func(context.Context, *ent.SubscriptionPlanQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSubscriptionPlan) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSubscriptionPlan) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SubscriptionPlanQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SubscriptionPlanQuery", q)
}

// The SubscriptionRevenueRecognitionFunc type is an adapter to allow the use of ordinary function as a Querier.
type SubscriptionRevenueRecognitionFunc func(context.Context, *ent.SubscriptionRevenueRecognitionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SubscriptionRevenueRecognitionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SubscriptionRevenueRecognitionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SubscriptionRevenueRecognitionQuery", q)
}

// The TraverseSubscriptionRevenueRecognition type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSubscriptionRevenueRecognition func(context.Context, *ent.SubscriptionRevenueRecognitionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSubscriptionRevenueRecognition) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSubscriptionRevenueRecognition) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SubscriptionRevenueRecognitionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SubscriptionRevenueRecognitionQuery", q)
}

// The SystemModelPriceVersionFunc type is an adapter to allow the use of ordinary function as a Querier.
type SystemModelPriceVersionFunc func(context.Context, *ent.SystemModelPriceVersionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SystemModelPriceVersionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SystemModelPriceVersionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SystemModelPriceVersionQuery", q)
}

// The TraverseSystemModelPriceVersion type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSystemModelPriceVersion func(context.Context, *ent.SystemModelPriceVersionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSystemModelPriceVersion) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSystemModelPriceVersion) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SystemModelPriceVersionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SystemModelPriceVersionQuery", q)
}

// The TLSFingerprintProfileFunc type is an adapter to allow the use of ordinary function as a Querier.
type TLSFingerprintProfileFunc func(context.Context, *ent.TLSFingerprintProfileQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f TLSFingerprintProfileFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.TLSFingerprintProfileQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.TLSFingerprintProfileQuery", q)
}

// The TraverseTLSFingerprintProfile type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTLSFingerprintProfile func(context.Context, *ent.TLSFingerprintProfileQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTLSFingerprintProfile) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTLSFingerprintProfile) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TLSFingerprintProfileQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.TLSFingerprintProfileQuery", q)
}

// The UpstreamBalanceSnapshotFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamBalanceSnapshotFunc func(context.Context, *ent.UpstreamBalanceSnapshotQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UpstreamBalanceSnapshotFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UpstreamBalanceSnapshotQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UpstreamBalanceSnapshotQuery", q)
}

// The TraverseUpstreamBalanceSnapshot type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamBalanceSnapshot func(context.Context, *ent.UpstreamBalanceSnapshotQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamBalanceSnapshot) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamBalanceSnapshot) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UpstreamBalanceSnapshotQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UpstreamBalanceSnapshotQuery", q)
}

// The UpstreamBillReconciliationFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamBillReconciliationFunc func(context.Context, *ent.UpstreamBillReconciliationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UpstreamBillReconciliationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UpstreamBillReconciliationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UpstreamBillReconciliationQuery", q)
}

// The TraverseUpstreamBillReconciliation type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamBillReconciliation func(context.Context, *ent.UpstreamBillReconciliationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamBillReconciliation) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamBillReconciliation) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UpstreamBillReconciliationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UpstreamBillReconciliationQuery", q)
}

// The UpstreamCostSettlementIntervalFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamCostSettlementIntervalFunc func(context.Context, *ent.UpstreamCostSettlementIntervalQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UpstreamCostSettlementIntervalFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UpstreamCostSettlementIntervalQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UpstreamCostSettlementIntervalQuery", q)
}

// The TraverseUpstreamCostSettlementInterval type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamCostSettlementInterval func(context.Context, *ent.UpstreamCostSettlementIntervalQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamCostSettlementInterval) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamCostSettlementInterval) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UpstreamCostSettlementIntervalQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UpstreamCostSettlementIntervalQuery", q)
}

// The UpstreamFinanceProtocolFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamFinanceProtocolFunc func(context.Context, *ent.UpstreamFinanceProtocolQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UpstreamFinanceProtocolFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UpstreamFinanceProtocolQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UpstreamFinanceProtocolQuery", q)
}

// The TraverseUpstreamFinanceProtocol type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamFinanceProtocol func(context.Context, *ent.UpstreamFinanceProtocolQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamFinanceProtocol) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamFinanceProtocol) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UpstreamFinanceProtocolQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UpstreamFinanceProtocolQuery", q)
}

// The UpstreamFinanceProtocolVersionFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamFinanceProtocolVersionFunc func(context.Context, *ent.UpstreamFinanceProtocolVersionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UpstreamFinanceProtocolVersionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UpstreamFinanceProtocolVersionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UpstreamFinanceProtocolVersionQuery", q)
}

// The TraverseUpstreamFinanceProtocolVersion type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamFinanceProtocolVersion func(context.Context, *ent.UpstreamFinanceProtocolVersionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamFinanceProtocolVersion) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamFinanceProtocolVersion) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UpstreamFinanceProtocolVersionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UpstreamFinanceProtocolVersionQuery", q)
}

// The UpstreamFinanceSyncRunFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamFinanceSyncRunFunc func(context.Context, *ent.UpstreamFinanceSyncRunQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UpstreamFinanceSyncRunFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UpstreamFinanceSyncRunQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UpstreamFinanceSyncRunQuery", q)
}

// The TraverseUpstreamFinanceSyncRun type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamFinanceSyncRun func(context.Context, *ent.UpstreamFinanceSyncRunQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamFinanceSyncRun) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamFinanceSyncRun) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UpstreamFinanceSyncRunQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UpstreamFinanceSyncRunQuery", q)
}

// The UpstreamFundEventFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamFundEventFunc func(context.Context, *ent.UpstreamFundEventQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UpstreamFundEventFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UpstreamFundEventQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UpstreamFundEventQuery", q)
}

// The TraverseUpstreamFundEvent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamFundEvent func(context.Context, *ent.UpstreamFundEventQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamFundEvent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamFundEvent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UpstreamFundEventQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UpstreamFundEventQuery", q)
}

// The UpstreamModelPriceVersionFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamModelPriceVersionFunc func(context.Context, *ent.UpstreamModelPriceVersionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UpstreamModelPriceVersionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UpstreamModelPriceVersionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UpstreamModelPriceVersionQuery", q)
}

// The TraverseUpstreamModelPriceVersion type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamModelPriceVersion func(context.Context, *ent.UpstreamModelPriceVersionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamModelPriceVersion) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamModelPriceVersion) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UpstreamModelPriceVersionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UpstreamModelPriceVersionQuery", q)
}

// The UpstreamWalletFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamWalletFunc func(context.Context, *ent.UpstreamWalletQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UpstreamWalletFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UpstreamWalletQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UpstreamWalletQuery", q)
}

// The TraverseUpstreamWallet type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamWallet func(context.Context, *ent.UpstreamWalletQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamWallet) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamWallet) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UpstreamWalletQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UpstreamWalletQuery", q)
}

// The UpstreamWalletAccountFunc type is an adapter to allow the use of ordinary function as a Querier.
type UpstreamWalletAccountFunc func(context.Context, *ent.UpstreamWalletAccountQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UpstreamWalletAccountFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UpstreamWalletAccountQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UpstreamWalletAccountQuery", q)
}

// The TraverseUpstreamWalletAccount type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUpstreamWalletAccount func(context.Context, *ent.UpstreamWalletAccountQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUpstreamWalletAccount) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUpstreamWalletAccount) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UpstreamWalletAccountQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UpstreamWalletAccountQuery", q)
}

// The UsageCleanupTaskFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageCleanupTaskFunc func(context.Context, *ent.UsageCleanupTaskQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageCleanupTaskFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageCleanupTaskQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageCleanupTaskQuery", q)
}

// The TraverseUsageCleanupTask type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageCleanupTask func(context.Context, *ent.UsageCleanupTaskQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageCleanupTask) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageCleanupTask) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageCleanupTaskQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageCleanupTaskQuery", q)
}

// The UsageCostSettlementAllocationFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageCostSettlementAllocationFunc func(context.Context, *ent.UsageCostSettlementAllocationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageCostSettlementAllocationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageCostSettlementAllocationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageCostSettlementAllocationQuery", q)
}

// The TraverseUsageCostSettlementAllocation type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageCostSettlementAllocation func(context.Context, *ent.UsageCostSettlementAllocationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageCostSettlementAllocation) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageCostSettlementAllocation) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageCostSettlementAllocationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageCostSettlementAllocationQuery", q)
}

// The UsageFinanceCostSegmentFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageFinanceCostSegmentFunc func(context.Context, *ent.UsageFinanceCostSegmentQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageFinanceCostSegmentFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageFinanceCostSegmentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageFinanceCostSegmentQuery", q)
}

// The TraverseUsageFinanceCostSegment type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageFinanceCostSegment func(context.Context, *ent.UsageFinanceCostSegmentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageFinanceCostSegment) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageFinanceCostSegment) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageFinanceCostSegmentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageFinanceCostSegmentQuery", q)
}

// The UsageFinanceRecordFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageFinanceRecordFunc func(context.Context, *ent.UsageFinanceRecordQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageFinanceRecordFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageFinanceRecordQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageFinanceRecordQuery", q)
}

// The TraverseUsageFinanceRecord type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageFinanceRecord func(context.Context, *ent.UsageFinanceRecordQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageFinanceRecord) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageFinanceRecord) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageFinanceRecordQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageFinanceRecordQuery", q)
}

// The UsageLogFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageLogFunc func(context.Context, *ent.UsageLogQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageLogFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageLogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageLogQuery", q)
}

// The TraverseUsageLog type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageLog func(context.Context, *ent.UsageLogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageLog) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageLog) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageLogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageLogQuery", q)
}

// The UsageRevenueAllocationFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageRevenueAllocationFunc func(context.Context, *ent.UsageRevenueAllocationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageRevenueAllocationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageRevenueAllocationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageRevenueAllocationQuery", q)
}

// The TraverseUsageRevenueAllocation type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageRevenueAllocation func(context.Context, *ent.UsageRevenueAllocationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageRevenueAllocation) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageRevenueAllocation) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageRevenueAllocationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageRevenueAllocationQuery", q)
}

// The UsageUpstreamAttemptFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageUpstreamAttemptFunc func(context.Context, *ent.UsageUpstreamAttemptQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageUpstreamAttemptFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageUpstreamAttemptQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageUpstreamAttemptQuery", q)
}

// The TraverseUsageUpstreamAttempt type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageUpstreamAttempt func(context.Context, *ent.UsageUpstreamAttemptQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageUpstreamAttempt) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageUpstreamAttempt) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageUpstreamAttemptQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageUpstreamAttemptQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *ent.UserQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *ent.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The UserAllowedGroupFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserAllowedGroupFunc func(context.Context, *ent.UserAllowedGroupQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserAllowedGroupFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserAllowedGroupQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserAllowedGroupQuery", q)
}

// The TraverseUserAllowedGroup type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserAllowedGroup func(context.Context, *ent.UserAllowedGroupQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserAllowedGroup) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserAllowedGroup) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserAllowedGroupQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserAllowedGroupQuery", q)
}

// The UserAttributeDefinitionFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserAttributeDefinitionFunc func(context.Context, *ent.UserAttributeDefinitionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserAttributeDefinitionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserAttributeDefinitionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserAttributeDefinitionQuery", q)
}

// The TraverseUserAttributeDefinition type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserAttributeDefinition func(context.Context, *ent.UserAttributeDefinitionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserAttributeDefinition) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserAttributeDefinition) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserAttributeDefinitionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserAttributeDefinitionQuery", q)
}

// The UserAttributeValueFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserAttributeValueFunc func(context.Context, *ent.UserAttributeValueQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserAttributeValueFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserAttributeValueQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserAttributeValueQuery", q)
}

// The TraverseUserAttributeValue type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserAttributeValue func(context.Context, *ent.UserAttributeValueQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserAttributeValue) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserAttributeValue) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserAttributeValueQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserAttributeValueQuery", q)
}

// The UserPlatformQuotaFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserPlatformQuotaFunc func(context.Context, *ent.UserPlatformQuotaQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserPlatformQuotaFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserPlatformQuotaQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserPlatformQuotaQuery", q)
}

// The TraverseUserPlatformQuota type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserPlatformQuota func(context.Context, *ent.UserPlatformQuotaQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserPlatformQuota) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserPlatformQuota) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserPlatformQuotaQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserPlatformQuotaQuery", q)
}

// The UserSubscriptionFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserSubscriptionFunc func(context.Context, *ent.UserSubscriptionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserSubscriptionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserSubscriptionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserSubscriptionQuery", q)
}

// The TraverseUserSubscription type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserSubscription func(context.Context, *ent.UserSubscriptionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserSubscription) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserSubscription) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserSubscriptionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserSubscriptionQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.APIKeyQuery:
		return &query[*ent.APIKeyQuery, predicate.APIKey, apikey.OrderOption]{typ: ent.TypeAPIKey, tq: q}, nil
	case *ent.AccountQuery:
		return &query[*ent.AccountQuery, predicate.Account, account.OrderOption]{typ: ent.TypeAccount, tq: q}, nil
	case *ent.AccountFinanceCounterSnapshotQuery:
		return &query[*ent.AccountFinanceCounterSnapshotQuery, predicate.AccountFinanceCounterSnapshot, accountfinancecountersnapshot.OrderOption]{typ: ent.TypeAccountFinanceCounterSnapshot, tq: q}, nil
	case *ent.AccountFinanceProfileQuery:
		return &query[*ent.AccountFinanceProfileQuery, predicate.AccountFinanceProfile, accountfinanceprofile.OrderOption]{typ: ent.TypeAccountFinanceProfile, tq: q}, nil
	case *ent.AccountGroupQuery:
		return &query[*ent.AccountGroupQuery, predicate.AccountGroup, accountgroup.OrderOption]{typ: ent.TypeAccountGroup, tq: q}, nil
	case *ent.AccountUpstreamMultiplierChangeQuery:
		return &query[*ent.AccountUpstreamMultiplierChangeQuery, predicate.AccountUpstreamMultiplierChange, accountupstreammultiplierchange.OrderOption]{typ: ent.TypeAccountUpstreamMultiplierChange, tq: q}, nil
	case *ent.AnnouncementQuery:
		return &query[*ent.AnnouncementQuery, predicate.Announcement, announcement.OrderOption]{typ: ent.TypeAnnouncement, tq: q}, nil
	case *ent.AnnouncementReadQuery:
		return &query[*ent.AnnouncementReadQuery, predicate.AnnouncementRead, announcementread.OrderOption]{typ: ent.TypeAnnouncementRead, tq: q}, nil
	case *ent.AuthIdentityQuery:
		return &query[*ent.AuthIdentityQuery, predicate.AuthIdentity, authidentity.OrderOption]{typ: ent.TypeAuthIdentity, tq: q}, nil
	case *ent.AuthIdentityChannelQuery:
		return &query[*ent.AuthIdentityChannelQuery, predicate.AuthIdentityChannel, authidentitychannel.OrderOption]{typ: ent.TypeAuthIdentityChannel, tq: q}, nil
	case *ent.ChannelMonitorQuery:
		return &query[*ent.ChannelMonitorQuery, predicate.ChannelMonitor, channelmonitor.OrderOption]{typ: ent.TypeChannelMonitor, tq: q}, nil
	case *ent.ChannelMonitorDailyRollupQuery:
		return &query[*ent.ChannelMonitorDailyRollupQuery, predicate.ChannelMonitorDailyRollup, channelmonitordailyrollup.OrderOption]{typ: ent.TypeChannelMonitorDailyRollup, tq: q}, nil
	case *ent.ChannelMonitorHistoryQuery:
		return &query[*ent.ChannelMonitorHistoryQuery, predicate.ChannelMonitorHistory, channelmonitorhistory.OrderOption]{typ: ent.TypeChannelMonitorHistory, tq: q}, nil
	case *ent.ChannelMonitorRequestTemplateQuery:
		return &query[*ent.ChannelMonitorRequestTemplateQuery, predicate.ChannelMonitorRequestTemplate, channelmonitorrequesttemplate.OrderOption]{typ: ent.TypeChannelMonitorRequestTemplate, tq: q}, nil
	case *ent.ErrorPassthroughRuleQuery:
		return &query[*ent.ErrorPassthroughRuleQuery, predicate.ErrorPassthroughRule, errorpassthroughrule.OrderOption]{typ: ent.TypeErrorPassthroughRule, tq: q}, nil
	case *ent.FinanceAlertQuery:
		return &query[*ent.FinanceAlertQuery, predicate.FinanceAlert, financealert.OrderOption]{typ: ent.TypeFinanceAlert, tq: q}, nil
	case *ent.FinanceAsyncJobQuery:
		return &query[*ent.FinanceAsyncJobQuery, predicate.FinanceAsyncJob, financeasyncjob.OrderOption]{typ: ent.TypeFinanceAsyncJob, tq: q}, nil
	case *ent.FinanceBackfillJobQuery:
		return &query[*ent.FinanceBackfillJobQuery, predicate.FinanceBackfillJob, financebackfilljob.OrderOption]{typ: ent.TypeFinanceBackfillJob, tq: q}, nil
	case *ent.FinanceCalculationRevisionQuery:
		return &query[*ent.FinanceCalculationRevisionQuery, predicate.FinanceCalculationRevision, financecalculationrevision.OrderOption]{typ: ent.TypeFinanceCalculationRevision, tq: q}, nil
	case *ent.FinanceDailyAggregateQuery:
		return &query[*ent.FinanceDailyAggregateQuery, predicate.FinanceDailyAggregate, financedailyaggregate.OrderOption]{typ: ent.TypeFinanceDailyAggregate, tq: q}, nil
	case *ent.FinanceExportJobQuery:
		return &query[*ent.FinanceExportJobQuery, predicate.FinanceExportJob, financeexportjob.OrderOption]{typ: ent.TypeFinanceExportJob, tq: q}, nil
	case *ent.FinanceFXRateVersionQuery:
		return &query[*ent.FinanceFXRateVersionQuery, predicate.FinanceFXRateVersion, financefxrateversion.OrderOption]{typ: ent.TypeFinanceFXRateVersion, tq: q}, nil
	case *ent.GroupQuery:
		return &query[*ent.GroupQuery, predicate.Group, group.OrderOption]{typ: ent.TypeGroup, tq: q}, nil
	case *ent.IdempotencyRecordQuery:
		return &query[*ent.IdempotencyRecordQuery, predicate.IdempotencyRecord, idempotencyrecord.OrderOption]{typ: ent.TypeIdempotencyRecord, tq: q}, nil
	case *ent.IdentityAdoptionDecisionQuery:
		return &query[*ent.IdentityAdoptionDecisionQuery, predicate.IdentityAdoptionDecision, identityadoptiondecision.OrderOption]{typ: ent.TypeIdentityAdoptionDecision, tq: q}, nil
	case *ent.PaymentAuditLogQuery:
		return &query[*ent.PaymentAuditLogQuery, predicate.PaymentAuditLog, paymentauditlog.OrderOption]{typ: ent.TypePaymentAuditLog, tq: q}, nil
	case *ent.PaymentOrderQuery:
		return &query[*ent.PaymentOrderQuery, predicate.PaymentOrder, paymentorder.OrderOption]{typ: ent.TypePaymentOrder, tq: q}, nil
	case *ent.PaymentProviderFeeEventQuery:
		return &query[*ent.PaymentProviderFeeEventQuery, predicate.PaymentProviderFeeEvent, paymentproviderfeeevent.OrderOption]{typ: ent.TypePaymentProviderFeeEvent, tq: q}, nil
	case *ent.PaymentProviderInstanceQuery:
		return &query[*ent.PaymentProviderInstanceQuery, predicate.PaymentProviderInstance, paymentproviderinstance.OrderOption]{typ: ent.TypePaymentProviderInstance, tq: q}, nil
	case *ent.PendingAuthSessionQuery:
		return &query[*ent.PendingAuthSessionQuery, predicate.PendingAuthSession, pendingauthsession.OrderOption]{typ: ent.TypePendingAuthSession, tq: q}, nil
	case *ent.PromoCodeQuery:
		return &query[*ent.PromoCodeQuery, predicate.PromoCode, promocode.OrderOption]{typ: ent.TypePromoCode, tq: q}, nil
	case *ent.PromoCodeUsageQuery:
		return &query[*ent.PromoCodeUsageQuery, predicate.PromoCodeUsage, promocodeusage.OrderOption]{typ: ent.TypePromoCodeUsage, tq: q}, nil
	case *ent.ProxyQuery:
		return &query[*ent.ProxyQuery, predicate.Proxy, proxy.OrderOption]{typ: ent.TypeProxy, tq: q}, nil
	case *ent.RedeemCodeQuery:
		return &query[*ent.RedeemCodeQuery, predicate.RedeemCode, redeemcode.OrderOption]{typ: ent.TypeRedeemCode, tq: q}, nil
	case *ent.SecuritySecretQuery:
		return &query[*ent.SecuritySecretQuery, predicate.SecuritySecret, securitysecret.OrderOption]{typ: ent.TypeSecuritySecret, tq: q}, nil
	case *ent.SettingQuery:
		return &query[*ent.SettingQuery, predicate.Setting, setting.OrderOption]{typ: ent.TypeSetting, tq: q}, nil
	case *ent.SubscriptionPlanQuery:
		return &query[*ent.SubscriptionPlanQuery, predicate.SubscriptionPlan, subscriptionplan.OrderOption]{typ: ent.TypeSubscriptionPlan, tq: q}, nil
	case *ent.SubscriptionRevenueRecognitionQuery:
		return &query[*ent.SubscriptionRevenueRecognitionQuery, predicate.SubscriptionRevenueRecognition, subscriptionrevenuerecognition.OrderOption]{typ: ent.TypeSubscriptionRevenueRecognition, tq: q}, nil
	case *ent.SystemModelPriceVersionQuery:
		return &query[*ent.SystemModelPriceVersionQuery, predicate.SystemModelPriceVersion, systemmodelpriceversion.OrderOption]{typ: ent.TypeSystemModelPriceVersion, tq: q}, nil
	case *ent.TLSFingerprintProfileQuery:
		return &query[*ent.TLSFingerprintProfileQuery, predicate.TLSFingerprintProfile, tlsfingerprintprofile.OrderOption]{typ: ent.TypeTLSFingerprintProfile, tq: q}, nil
	case *ent.UpstreamBalanceSnapshotQuery:
		return &query[*ent.UpstreamBalanceSnapshotQuery, predicate.UpstreamBalanceSnapshot, upstreambalancesnapshot.OrderOption]{typ: ent.TypeUpstreamBalanceSnapshot, tq: q}, nil
	case *ent.UpstreamBillReconciliationQuery:
		return &query[*ent.UpstreamBillReconciliationQuery, predicate.UpstreamBillReconciliation, upstreambillreconciliation.OrderOption]{typ: ent.TypeUpstreamBillReconciliation, tq: q}, nil
	case *ent.UpstreamCostSettlementIntervalQuery:
		return &query[*ent.UpstreamCostSettlementIntervalQuery, predicate.UpstreamCostSettlementInterval, upstreamcostsettlementinterval.OrderOption]{typ: ent.TypeUpstreamCostSettlementInterval, tq: q}, nil
	case *ent.UpstreamFinanceProtocolQuery:
		return &query[*ent.UpstreamFinanceProtocolQuery, predicate.UpstreamFinanceProtocol, upstreamfinanceprotocol.OrderOption]{typ: ent.TypeUpstreamFinanceProtocol, tq: q}, nil
	case *ent.UpstreamFinanceProtocolVersionQuery:
		return &query[*ent.UpstreamFinanceProtocolVersionQuery, predicate.UpstreamFinanceProtocolVersion, upstreamfinanceprotocolversion.OrderOption]{typ: ent.TypeUpstreamFinanceProtocolVersion, tq: q}, nil
	case *ent.UpstreamFinanceSyncRunQuery:
		return &query[*ent.UpstreamFinanceSyncRunQuery, predicate.UpstreamFinanceSyncRun, upstreamfinancesyncrun.OrderOption]{typ: ent.TypeUpstreamFinanceSyncRun, tq: q}, nil
	case *ent.UpstreamFundEventQuery:
		return &query[*ent.UpstreamFundEventQuery, predicate.UpstreamFundEvent, upstreamfundevent.OrderOption]{typ: ent.TypeUpstreamFundEvent, tq: q}, nil
	case *ent.UpstreamModelPriceVersionQuery:
		return &query[*ent.UpstreamModelPriceVersionQuery, predicate.UpstreamModelPriceVersion, upstreammodelpriceversion.OrderOption]{typ: ent.TypeUpstreamModelPriceVersion, tq: q}, nil
	case *ent.UpstreamWalletQuery:
		return &query[*ent.UpstreamWalletQuery, predicate.UpstreamWallet, upstreamwallet.OrderOption]{typ: ent.TypeUpstreamWallet, tq: q}, nil
	case *ent.UpstreamWalletAccountQuery:
		return &query[*ent.UpstreamWalletAccountQuery, predicate.UpstreamWalletAccount, upstreamwalletaccount.OrderOption]{typ: ent.TypeUpstreamWalletAccount, tq: q}, nil
	case *ent.UsageCleanupTaskQuery:
		return &query[*ent.UsageCleanupTaskQuery, predicate.UsageCleanupTask, usagecleanuptask.OrderOption]{typ: ent.TypeUsageCleanupTask, tq: q}, nil
	case *ent.UsageCostSettlementAllocationQuery:
		return &query[*ent.UsageCostSettlementAllocationQuery, predicate.UsageCostSettlementAllocation, usagecostsettlementallocation.OrderOption]{typ: ent.TypeUsageCostSettlementAllocation, tq: q}, nil
	case *ent.UsageFinanceCostSegmentQuery:
		return &query[*ent.UsageFinanceCostSegmentQuery, predicate.UsageFinanceCostSegment, usagefinancecostsegment.OrderOption]{typ: ent.TypeUsageFinanceCostSegment, tq: q}, nil
	case *ent.UsageFinanceRecordQuery:
		return &query[*ent.UsageFinanceRecordQuery, predicate.UsageFinanceRecord, usagefinancerecord.OrderOption]{typ: ent.TypeUsageFinanceRecord, tq: q}, nil
	case *ent.UsageLogQuery:
		return &query[*ent.UsageLogQuery, predicate.UsageLog, usagelog.OrderOption]{typ: ent.TypeUsageLog, tq: q}, nil
	case *ent.UsageRevenueAllocationQuery:
		return &query[*ent.UsageRevenueAllocationQuery, predicate.UsageRevenueAllocation, usagerevenueallocation.OrderOption]{typ: ent.TypeUsageRevenueAllocation, tq: q}, nil
	case *ent.UsageUpstreamAttemptQuery:
		return &query[*ent.UsageUpstreamAttemptQuery, predicate.UsageUpstreamAttempt, usageupstreamattempt.OrderOption]{typ: ent.TypeUsageUpstreamAttempt, tq: q}, nil
	case *ent.UserQuery:
		return &query[*ent.UserQuery, predicate.User, user.OrderOption]{typ: ent.TypeUser, tq: q}, nil
	case *ent.UserAllowedGroupQuery:
		return &query[*ent.UserAllowedGroupQuery, predicate.UserAllowedGroup, userallowedgroup.OrderOption]{typ: ent.TypeUserAllowedGroup, tq: q}, nil
	case *ent.UserAttributeDefinitionQuery:
		return &query[*ent.UserAttributeDefinitionQuery, predicate.UserAttributeDefinition, userattributedefinition.OrderOption]{typ: ent.TypeUserAttributeDefinition, tq: q}, nil
	case *ent.UserAttributeValueQuery:
		return &query[*ent.UserAttributeValueQuery, predicate.UserAttributeValue, userattributevalue.OrderOption]{typ: ent.TypeUserAttributeValue, tq: q}, nil
	case *ent.UserPlatformQuotaQuery:
		return &query[*ent.UserPlatformQuotaQuery, predicate.UserPlatformQuota, userplatformquota.OrderOption]{typ: ent.TypeUserPlatformQuota, tq: q}, nil
	case *ent.UserSubscriptionQuery:
		return &query[*ent.UserSubscriptionQuery, predicate.UserSubscription, usersubscription.OrderOption]{typ: ent.TypeUserSubscription, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
