<template>
  <AppLayout>
    <div class="space-y-6">
      <header class="flex flex-wrap items-end justify-between gap-3">
        <div><h1 class="text-2xl font-bold">上游财务协议</h1><p class="mt-1 text-sm text-gray-500">用已发布的版本接入新上游定价、余额和配额；协议版本发布后保持不可变。</p></div>
        <button class="btn btn-primary" @click="openCreate">新增协议</button>
      </header>
      <section class="card p-4"><label class="text-sm">状态筛选<select v-model="status" class="input ml-2" @change="load"><option value="">全部</option><option value="draft">草稿</option><option value="published">已发布</option><option value="disabled">已停用</option></select></label></section>
      <section class="card overflow-x-auto">
        <table class="min-w-full text-sm"><thead class="bg-gray-50 text-left text-xs text-gray-500 dark:bg-dark-800"><tr><th class="px-4 py-3">名称</th><th class="px-4 py-3">编码</th><th class="px-4 py-3">类型</th><th class="px-4 py-3">状态</th><th class="px-4 py-3">当前版本</th><th class="px-4 py-3 text-right">操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id" class="border-t border-gray-100 dark:border-dark-700"><td class="px-4 py-3 font-medium">{{ item.name }}</td><td class="px-4 py-3 font-mono text-xs">{{ item.code }}</td><td class="px-4 py-3">{{ item.protocol_type }}</td><td class="px-4 py-3">{{ statusLabel(item.status) }}</td><td class="px-4 py-3">{{ item.current_version?.version || '-' }}</td><td class="px-4 py-3 text-right"><button class="text-primary-700 dark:text-primary-400" @click="openEdit(item)">查看/编辑</button><button v-if="item.status === 'published'" class="ml-3 text-primary-700 dark:text-primary-400" @click="copyItem(item)">复制为草稿</button><button v-if="item.status === 'published'" class="ml-3 text-red-600" @click="disableItem(item)">停用</button><button v-if="item.status === 'draft'" class="ml-3 text-red-600" @click="removeDraft(item)">删除草稿</button></td></tr><tr v-if="!loading && items.length === 0"><td colspan="6" class="p-8 text-center text-gray-500">暂无协议</td></tr></tbody></table>
      </section>
      <div v-if="editing" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form class="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-xl bg-white p-6 dark:bg-dark-800" @submit.prevent="save"><h2 class="text-lg font-semibold">{{ editing.id ? '协议详情' : '新增协议' }}</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label>名称<input v-model="editing.name" class="input mt-1 w-full" required /></label><label>编码<input v-model="editing.code" class="input mt-1 w-full" :disabled="!!editing.id" required pattern="[a-z][a-z0-9_-]{2,79}" /></label><label>类型<select v-model="editing.protocol_type" class="input mt-1 w-full" :disabled="!!editing.id"><option value="http_json">HTTP JSON</option></select></label><label v-if="editing.id">测试 Base URL<input v-model="testBaseURL" class="input mt-1 w-full" placeholder="https://..." /></label><label v-if="editing.id">测试操作<input v-model="testOperation" class="input mt-1 w-full" placeholder="pricing / balance / quota" /></label><label v-if="editing.id">一次性测试凭据<input v-model="testCredential" type="password" autocomplete="new-password" class="input mt-1 w-full" /><span class="text-xs text-gray-500">仅随本次测试发送，不保存、不回显。</span></label></div><FinanceProtocolConfigEditor class="mt-5" :model-value="configDraft" @update:model-value="updateConfigDraft" /><details class="mt-5 rounded-lg border border-gray-200 p-4 dark:border-dark-700"><summary class="cursor-pointer font-medium">高级：查看或导入协议 JSON</summary><p class="mt-2 text-xs text-gray-500">结构化配置会自动同步到这里。手工修改后离开输入框即执行校验和导入。</p><textarea v-model="configJSON" class="input mt-3 h-72 w-full font-mono text-xs" @change="applyConfigJSON" /></details><pre v-if="testResult" class="mt-4 max-h-48 overflow-auto rounded bg-gray-950 p-3 text-xs text-gray-100">{{ testResult }}</pre><div class="mt-5 flex flex-wrap justify-end gap-2"><button v-if="editing.id" type="button" class="btn btn-secondary" @click="runTest">安全测试</button><button v-if="editing.id && editing.status === 'draft'" type="button" class="btn btn-primary" @click="publishItem">发布当前版本</button><button type="button" class="btn btn-secondary" @click="editing = null">关闭</button><button v-if="!editing.id || editing.status === 'draft'" class="btn btn-primary" :disabled="saving">保存草稿</button></div></form></div>
    </div>
  </AppLayout>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import AppLayout from '@/components/layout/AppLayout.vue'
import FinanceProtocolConfigEditor from '@/components/finance/FinanceProtocolConfigEditor.vue'
import { adminAPI } from '@/api/admin'
import type { FinanceProtocol, FinanceProtocolInput } from '@/api/admin/upstreamFinanceProtocols'
import { useAppStore } from '@/stores/app'
import { extractApiErrorMessage } from '@/utils/apiError'

const app = useAppStore(); const items = ref<FinanceProtocol[]>([]); const loading = ref(false); const saving = ref(false); const status = ref(''); const editing = ref<(FinanceProtocolInput & { id?: number; status?: string; current_version_id?: number }) | null>(null); const copySourceID = ref<number | null>(null); const configDraft = ref<Record<string, unknown>>({}); const configJSON = ref('{}'); const testBaseURL = ref(''); const testCredential = ref(''); const testOperation = ref(''); const testResult = ref('')
function errorMessage(error: unknown, fallback: string) { return extractApiErrorMessage(error, fallback) }
function statusLabel(value: string) { return ({ draft: '草稿', published: '已发布', disabled: '已停用' } as Record<string, string>)[value] || value }
async function load() { loading.value = true; try { items.value = (await adminAPI.upstreamFinanceProtocols.list(status.value)).items || [] } catch (e) { app.showError(errorMessage(e, '协议加载失败')) } finally { loading.value = false } }
function cloneConfig(value: Record<string, unknown>) { return JSON.parse(JSON.stringify(value)) as Record<string, unknown> }
function setConfig(value: Record<string, unknown>) { configDraft.value = cloneConfig(value); configJSON.value = JSON.stringify(configDraft.value, null, 2) }
function updateConfigDraft(value: Record<string, unknown>) { configDraft.value = value; configJSON.value = JSON.stringify(value, null, 2) }
function applyConfigJSON() { try { setConfig(JSON.parse(configJSON.value) as Record<string, unknown>) } catch { app.showError('协议 JSON 格式无效，未导入修改') } }
function openCreate() { copySourceID.value = null; editing.value = { name: '', code: '', protocol_type: 'http_json', config: {} }; setConfig({ capabilities: [], authentication: { type: 'none', credential_source: '' }, operations: {}, cost_mode: 'manual', unit_semantics: 'none', counter_scope: '', redact_paths: [] }); testResult.value = '' }
async function openEdit(item: FinanceProtocol) { try { copySourceID.value = null; const history = await adminAPI.upstreamFinanceProtocols.versions(item.id); const latest = history[0] || item.current_version; editing.value = { id: item.id, name: item.name, code: item.code, protocol_type: item.protocol_type === 'builtin' ? 'http_json' : item.protocol_type, config: latest?.config || {}, status: item.status, current_version_id: latest?.id }; setConfig(latest?.config || {}); testResult.value = '' } catch (e) { app.showError(errorMessage(e, '协议版本加载失败')) } }
async function copyItem(item: FinanceProtocol) { try { const history = await adminAPI.upstreamFinanceProtocols.versions(item.id); const latest = history[0] || item.current_version; copySourceID.value = item.id; editing.value = { name: `${item.name} 副本`, code: `${item.code}_copy`, protocol_type: item.protocol_type === 'plugin' ? 'plugin' : 'http_json', config: latest?.config || {}, status: 'draft' }; setConfig(latest?.config || {}); testResult.value = '' } catch (e) { app.showError(errorMessage(e, '协议版本加载失败')) } }
async function save() { if (!editing.value) return; saving.value = true; try { const config = cloneConfig(configDraft.value); if (editing.value.id) { const version = await adminAPI.upstreamFinanceProtocols.updateDraft(editing.value.id, { name: editing.value.name, config }); editing.value.current_version_id = version.id; editing.value.config = version.config; setConfig(version.config) } else { const payload = { code: editing.value.code, name: editing.value.name, protocol_type: editing.value.protocol_type, config }; const item = copySourceID.value ? await adminAPI.upstreamFinanceProtocols.copy(copySourceID.value, payload) : await adminAPI.upstreamFinanceProtocols.create(payload); copySourceID.value = null; editing.value = { id: item.id, name: item.name, code: item.code, protocol_type: item.protocol_type === 'builtin' ? 'http_json' : item.protocol_type, config, status: item.status, current_version_id: item.current_version?.id } } await load(); app.showSuccess('协议草稿已保存') } catch (e) { app.showError(errorMessage(e, '协议保存失败')) } finally { saving.value = false } }
async function runTest() { if (!editing.value?.id) return; try { testResult.value = JSON.stringify(await adminAPI.upstreamFinanceProtocols.testProtocol(editing.value.id, testBaseURL.value, testCredential.value, testOperation.value), null, 2); testCredential.value = '' } catch (e) { testCredential.value = ''; app.showError(errorMessage(e, '协议测试失败')) } }
async function publishItem() { if (!editing.value?.id || !editing.value.current_version_id || !window.confirm('发布后此版本不可修改，确认发布？')) return; try { await adminAPI.upstreamFinanceProtocols.publish(editing.value.id, editing.value.current_version_id); editing.value = null; await load(); app.showSuccess('协议已发布') } catch (e) { app.showError(errorMessage(e, '协议发布失败')) } }
async function disableItem(item: FinanceProtocol) { if (!window.confirm(`确认停用协议 ${item.name}？已绑定钱包保留历史版本。`)) return; try { await adminAPI.upstreamFinanceProtocols.disable(item.id); await load() } catch (e) { app.showError(errorMessage(e, '协议停用失败')) } }
async function removeDraft(item: FinanceProtocol) { if (!window.confirm(`确认删除草稿 ${item.name}？`)) return; try { await adminAPI.upstreamFinanceProtocols.deleteDraft(item.id); await load() } catch (e) { app.showError(errorMessage(e, '草稿删除失败')) } }
onMounted(load)
</script>
