// Code generated by ent, DO NOT EDIT.

package upstreamfinanceprotocolversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstreamfinanceprotocolversion type in the database.
	Label = "upstream_finance_protocol_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProtocolID holds the string denoting the protocol_id field in the database.
	FieldProtocolID = "protocol_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldChecksum holds the string denoting the checksum field in the database.
	FieldChecksum = "checksum"
	// FieldValidationStatus holds the string denoting the validation_status field in the database.
	FieldValidationStatus = "validation_status"
	// FieldValidationResult holds the string denoting the validation_result field in the database.
	FieldValidationResult = "validation_result"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the upstreamfinanceprotocolversion in the database.
	Table = "upstream_finance_protocol_versions"
)

// Columns holds all SQL columns for upstreamfinanceprotocolversion fields.
var Columns = []string{
	FieldID,
	FieldProtocolID,
	FieldVersion,
	FieldConfig,
	FieldChecksum,
	FieldValidationStatus,
	FieldValidationResult,
	FieldPublishedAt,
	FieldCreatedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int) error
	// ChecksumValidator is a validator for the "checksum" field. It is called by the builders before save.
	ChecksumValidator func(string) error
	// DefaultValidationStatus holds the default value on creation for the "validation_status" field.
	DefaultValidationStatus string
	// ValidationStatusValidator is a validator for the "validation_status" field. It is called by the builders before save.
	ValidationStatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UpstreamFinanceProtocolVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProtocolID orders the results by the protocol_id field.
func ByProtocolID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocolID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByChecksum orders the results by the checksum field.
func ByChecksum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChecksum, opts...).ToFunc()
}

// ByValidationStatus orders the results by the validation_status field.
func ByValidationStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidationStatus, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
