// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/financedailyaggregate"
)

// FinanceDailyAggregateCreate is the builder for creating a FinanceDailyAggregate entity.
type FinanceDailyAggregateCreate struct {
	config
	mutation *FinanceDailyAggregateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAggregateDate sets the "aggregate_date" field.
func (_c *FinanceDailyAggregateCreate) SetAggregateDate(v time.Time) *FinanceDailyAggregateCreate {
	_c.mutation.SetAggregateDate(v)
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *FinanceDailyAggregateCreate) SetTimezone(v string) *FinanceDailyAggregateCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetDimensionType sets the "dimension_type" field.
func (_c *FinanceDailyAggregateCreate) SetDimensionType(v string) *FinanceDailyAggregateCreate {
	_c.mutation.SetDimensionType(v)
	return _c
}

// SetDimensionKey sets the "dimension_key" field.
func (_c *FinanceDailyAggregateCreate) SetDimensionKey(v string) *FinanceDailyAggregateCreate {
	_c.mutation.SetDimensionKey(v)
	return _c
}

// SetMetricDetail sets the "metric_detail" field.
func (_c *FinanceDailyAggregateCreate) SetMetricDetail(v map[string]interface{}) *FinanceDailyAggregateCreate {
	_c.mutation.SetMetricDetail(v)
	return _c
}

// SetSourceRevision sets the "source_revision" field.
func (_c *FinanceDailyAggregateCreate) SetSourceRevision(v int64) *FinanceDailyAggregateCreate {
	_c.mutation.SetSourceRevision(v)
	return _c
}

// SetGeneratedAt sets the "generated_at" field.
func (_c *FinanceDailyAggregateCreate) SetGeneratedAt(v time.Time) *FinanceDailyAggregateCreate {
	_c.mutation.SetGeneratedAt(v)
	return _c
}

// Mutation returns the FinanceDailyAggregateMutation object of the builder.
func (_c *FinanceDailyAggregateCreate) Mutation() *FinanceDailyAggregateMutation {
	return _c.mutation
}

// Save creates the FinanceDailyAggregate in the database.
func (_c *FinanceDailyAggregateCreate) Save(ctx context.Context) (*FinanceDailyAggregate, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FinanceDailyAggregateCreate) SaveX(ctx context.Context) *FinanceDailyAggregate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceDailyAggregateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceDailyAggregateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FinanceDailyAggregateCreate) check() error {
	if _, ok := _c.mutation.AggregateDate(); !ok {
		return &ValidationError{Name: "aggregate_date", err: errors.New(`ent: missing required field "FinanceDailyAggregate.aggregate_date"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "FinanceDailyAggregate.timezone"`)}
	}
	if v, ok := _c.mutation.Timezone(); ok {
		if err := financedailyaggregate.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "FinanceDailyAggregate.timezone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DimensionType(); !ok {
		return &ValidationError{Name: "dimension_type", err: errors.New(`ent: missing required field "FinanceDailyAggregate.dimension_type"`)}
	}
	if v, ok := _c.mutation.DimensionType(); ok {
		if err := financedailyaggregate.DimensionTypeValidator(v); err != nil {
			return &ValidationError{Name: "dimension_type", err: fmt.Errorf(`ent: validator failed for field "FinanceDailyAggregate.dimension_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DimensionKey(); !ok {
		return &ValidationError{Name: "dimension_key", err: errors.New(`ent: missing required field "FinanceDailyAggregate.dimension_key"`)}
	}
	if v, ok := _c.mutation.DimensionKey(); ok {
		if err := financedailyaggregate.DimensionKeyValidator(v); err != nil {
			return &ValidationError{Name: "dimension_key", err: fmt.Errorf(`ent: validator failed for field "FinanceDailyAggregate.dimension_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MetricDetail(); !ok {
		return &ValidationError{Name: "metric_detail", err: errors.New(`ent: missing required field "FinanceDailyAggregate.metric_detail"`)}
	}
	if _, ok := _c.mutation.SourceRevision(); !ok {
		return &ValidationError{Name: "source_revision", err: errors.New(`ent: missing required field "FinanceDailyAggregate.source_revision"`)}
	}
	if _, ok := _c.mutation.GeneratedAt(); !ok {
		return &ValidationError{Name: "generated_at", err: errors.New(`ent: missing required field "FinanceDailyAggregate.generated_at"`)}
	}
	return nil
}

func (_c *FinanceDailyAggregateCreate) sqlSave(ctx context.Context) (*FinanceDailyAggregate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FinanceDailyAggregateCreate) createSpec() (*FinanceDailyAggregate, *sqlgraph.CreateSpec) {
	var (
		_node = &FinanceDailyAggregate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(financedailyaggregate.Table, sqlgraph.NewFieldSpec(financedailyaggregate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AggregateDate(); ok {
		_spec.SetField(financedailyaggregate.FieldAggregateDate, field.TypeTime, value)
		_node.AggregateDate = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(financedailyaggregate.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.DimensionType(); ok {
		_spec.SetField(financedailyaggregate.FieldDimensionType, field.TypeString, value)
		_node.DimensionType = value
	}
	if value, ok := _c.mutation.DimensionKey(); ok {
		_spec.SetField(financedailyaggregate.FieldDimensionKey, field.TypeString, value)
		_node.DimensionKey = value
	}
	if value, ok := _c.mutation.MetricDetail(); ok {
		_spec.SetField(financedailyaggregate.FieldMetricDetail, field.TypeJSON, value)
		_node.MetricDetail = value
	}
	if value, ok := _c.mutation.SourceRevision(); ok {
		_spec.SetField(financedailyaggregate.FieldSourceRevision, field.TypeInt64, value)
		_node.SourceRevision = value
	}
	if value, ok := _c.mutation.GeneratedAt(); ok {
		_spec.SetField(financedailyaggregate.FieldGeneratedAt, field.TypeTime, value)
		_node.GeneratedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FinanceDailyAggregate.Create().
//		SetAggregateDate(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FinanceDailyAggregateUpsert) {
//			SetAggregateDate(v+v).
//		}).
//		Exec(ctx)
func (_c *FinanceDailyAggregateCreate) OnConflict(opts ...sql.ConflictOption) *FinanceDailyAggregateUpsertOne {
	_c.conflict = opts
	return &FinanceDailyAggregateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FinanceDailyAggregate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FinanceDailyAggregateCreate) OnConflictColumns(columns ...string) *FinanceDailyAggregateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FinanceDailyAggregateUpsertOne{
		create: _c,
	}
}

type (
	// FinanceDailyAggregateUpsertOne is the builder for "upsert"-ing
	//  one FinanceDailyAggregate node.
	FinanceDailyAggregateUpsertOne struct {
		create *FinanceDailyAggregateCreate
	}

	// FinanceDailyAggregateUpsert is the "OnConflict" setter.
	FinanceDailyAggregateUpsert struct {
		*sql.UpdateSet
	}
)

// SetAggregateDate sets the "aggregate_date" field.
func (u *FinanceDailyAggregateUpsert) SetAggregateDate(v time.Time) *FinanceDailyAggregateUpsert {
	u.Set(financedailyaggregate.FieldAggregateDate, v)
	return u
}

// UpdateAggregateDate sets the "aggregate_date" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsert) UpdateAggregateDate() *FinanceDailyAggregateUpsert {
	u.SetExcluded(financedailyaggregate.FieldAggregateDate)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *FinanceDailyAggregateUpsert) SetTimezone(v string) *FinanceDailyAggregateUpsert {
	u.Set(financedailyaggregate.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsert) UpdateTimezone() *FinanceDailyAggregateUpsert {
	u.SetExcluded(financedailyaggregate.FieldTimezone)
	return u
}

// SetDimensionType sets the "dimension_type" field.
func (u *FinanceDailyAggregateUpsert) SetDimensionType(v string) *FinanceDailyAggregateUpsert {
	u.Set(financedailyaggregate.FieldDimensionType, v)
	return u
}

// UpdateDimensionType sets the "dimension_type" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsert) UpdateDimensionType() *FinanceDailyAggregateUpsert {
	u.SetExcluded(financedailyaggregate.FieldDimensionType)
	return u
}

// SetDimensionKey sets the "dimension_key" field.
func (u *FinanceDailyAggregateUpsert) SetDimensionKey(v string) *FinanceDailyAggregateUpsert {
	u.Set(financedailyaggregate.FieldDimensionKey, v)
	return u
}

// UpdateDimensionKey sets the "dimension_key" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsert) UpdateDimensionKey() *FinanceDailyAggregateUpsert {
	u.SetExcluded(financedailyaggregate.FieldDimensionKey)
	return u
}

// SetMetricDetail sets the "metric_detail" field.
func (u *FinanceDailyAggregateUpsert) SetMetricDetail(v map[string]interface{}) *FinanceDailyAggregateUpsert {
	u.Set(financedailyaggregate.FieldMetricDetail, v)
	return u
}

// UpdateMetricDetail sets the "metric_detail" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsert) UpdateMetricDetail() *FinanceDailyAggregateUpsert {
	u.SetExcluded(financedailyaggregate.FieldMetricDetail)
	return u
}

// SetSourceRevision sets the "source_revision" field.
func (u *FinanceDailyAggregateUpsert) SetSourceRevision(v int64) *FinanceDailyAggregateUpsert {
	u.Set(financedailyaggregate.FieldSourceRevision, v)
	return u
}

// UpdateSourceRevision sets the "source_revision" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsert) UpdateSourceRevision() *FinanceDailyAggregateUpsert {
	u.SetExcluded(financedailyaggregate.FieldSourceRevision)
	return u
}

// AddSourceRevision adds v to the "source_revision" field.
func (u *FinanceDailyAggregateUpsert) AddSourceRevision(v int64) *FinanceDailyAggregateUpsert {
	u.Add(financedailyaggregate.FieldSourceRevision, v)
	return u
}

// SetGeneratedAt sets the "generated_at" field.
func (u *FinanceDailyAggregateUpsert) SetGeneratedAt(v time.Time) *FinanceDailyAggregateUpsert {
	u.Set(financedailyaggregate.FieldGeneratedAt, v)
	return u
}

// UpdateGeneratedAt sets the "generated_at" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsert) UpdateGeneratedAt() *FinanceDailyAggregateUpsert {
	u.SetExcluded(financedailyaggregate.FieldGeneratedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FinanceDailyAggregate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FinanceDailyAggregateUpsertOne) UpdateNewValues() *FinanceDailyAggregateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FinanceDailyAggregate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FinanceDailyAggregateUpsertOne) Ignore() *FinanceDailyAggregateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FinanceDailyAggregateUpsertOne) DoNothing() *FinanceDailyAggregateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FinanceDailyAggregateCreate.OnConflict
// documentation for more info.
func (u *FinanceDailyAggregateUpsertOne) Update(set func(*FinanceDailyAggregateUpsert)) *FinanceDailyAggregateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FinanceDailyAggregateUpsert{UpdateSet: update})
	}))
	return u
}

// SetAggregateDate sets the "aggregate_date" field.
func (u *FinanceDailyAggregateUpsertOne) SetAggregateDate(v time.Time) *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetAggregateDate(v)
	})
}

// UpdateAggregateDate sets the "aggregate_date" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertOne) UpdateAggregateDate() *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateAggregateDate()
	})
}

// SetTimezone sets the "timezone" field.
func (u *FinanceDailyAggregateUpsertOne) SetTimezone(v string) *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertOne) UpdateTimezone() *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateTimezone()
	})
}

// SetDimensionType sets the "dimension_type" field.
func (u *FinanceDailyAggregateUpsertOne) SetDimensionType(v string) *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetDimensionType(v)
	})
}

// UpdateDimensionType sets the "dimension_type" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertOne) UpdateDimensionType() *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateDimensionType()
	})
}

// SetDimensionKey sets the "dimension_key" field.
func (u *FinanceDailyAggregateUpsertOne) SetDimensionKey(v string) *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetDimensionKey(v)
	})
}

// UpdateDimensionKey sets the "dimension_key" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertOne) UpdateDimensionKey() *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateDimensionKey()
	})
}

// SetMetricDetail sets the "metric_detail" field.
func (u *FinanceDailyAggregateUpsertOne) SetMetricDetail(v map[string]interface{}) *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetMetricDetail(v)
	})
}

// UpdateMetricDetail sets the "metric_detail" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertOne) UpdateMetricDetail() *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateMetricDetail()
	})
}

// SetSourceRevision sets the "source_revision" field.
func (u *FinanceDailyAggregateUpsertOne) SetSourceRevision(v int64) *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetSourceRevision(v)
	})
}

// AddSourceRevision adds v to the "source_revision" field.
func (u *FinanceDailyAggregateUpsertOne) AddSourceRevision(v int64) *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.AddSourceRevision(v)
	})
}

// UpdateSourceRevision sets the "source_revision" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertOne) UpdateSourceRevision() *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateSourceRevision()
	})
}

// SetGeneratedAt sets the "generated_at" field.
func (u *FinanceDailyAggregateUpsertOne) SetGeneratedAt(v time.Time) *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetGeneratedAt(v)
	})
}

// UpdateGeneratedAt sets the "generated_at" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertOne) UpdateGeneratedAt() *FinanceDailyAggregateUpsertOne {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateGeneratedAt()
	})
}

// Exec executes the query.
func (u *FinanceDailyAggregateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FinanceDailyAggregateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FinanceDailyAggregateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FinanceDailyAggregateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FinanceDailyAggregateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FinanceDailyAggregateCreateBulk is the builder for creating many FinanceDailyAggregate entities in bulk.
type FinanceDailyAggregateCreateBulk struct {
	config
	err      error
	builders []*FinanceDailyAggregateCreate
	conflict []sql.ConflictOption
}

// Save creates the FinanceDailyAggregate entities in the database.
func (_c *FinanceDailyAggregateCreateBulk) Save(ctx context.Context) ([]*FinanceDailyAggregate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FinanceDailyAggregate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FinanceDailyAggregateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FinanceDailyAggregateCreateBulk) SaveX(ctx context.Context) []*FinanceDailyAggregate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceDailyAggregateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceDailyAggregateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FinanceDailyAggregate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FinanceDailyAggregateUpsert) {
//			SetAggregateDate(v+v).
//		}).
//		Exec(ctx)
func (_c *FinanceDailyAggregateCreateBulk) OnConflict(opts ...sql.ConflictOption) *FinanceDailyAggregateUpsertBulk {
	_c.conflict = opts
	return &FinanceDailyAggregateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FinanceDailyAggregate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FinanceDailyAggregateCreateBulk) OnConflictColumns(columns ...string) *FinanceDailyAggregateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FinanceDailyAggregateUpsertBulk{
		create: _c,
	}
}

// FinanceDailyAggregateUpsertBulk is the builder for "upsert"-ing
// a bulk of FinanceDailyAggregate nodes.
type FinanceDailyAggregateUpsertBulk struct {
	create *FinanceDailyAggregateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FinanceDailyAggregate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FinanceDailyAggregateUpsertBulk) UpdateNewValues() *FinanceDailyAggregateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FinanceDailyAggregate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FinanceDailyAggregateUpsertBulk) Ignore() *FinanceDailyAggregateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FinanceDailyAggregateUpsertBulk) DoNothing() *FinanceDailyAggregateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FinanceDailyAggregateCreateBulk.OnConflict
// documentation for more info.
func (u *FinanceDailyAggregateUpsertBulk) Update(set func(*FinanceDailyAggregateUpsert)) *FinanceDailyAggregateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FinanceDailyAggregateUpsert{UpdateSet: update})
	}))
	return u
}

// SetAggregateDate sets the "aggregate_date" field.
func (u *FinanceDailyAggregateUpsertBulk) SetAggregateDate(v time.Time) *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetAggregateDate(v)
	})
}

// UpdateAggregateDate sets the "aggregate_date" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertBulk) UpdateAggregateDate() *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateAggregateDate()
	})
}

// SetTimezone sets the "timezone" field.
func (u *FinanceDailyAggregateUpsertBulk) SetTimezone(v string) *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertBulk) UpdateTimezone() *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateTimezone()
	})
}

// SetDimensionType sets the "dimension_type" field.
func (u *FinanceDailyAggregateUpsertBulk) SetDimensionType(v string) *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetDimensionType(v)
	})
}

// UpdateDimensionType sets the "dimension_type" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertBulk) UpdateDimensionType() *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateDimensionType()
	})
}

// SetDimensionKey sets the "dimension_key" field.
func (u *FinanceDailyAggregateUpsertBulk) SetDimensionKey(v string) *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetDimensionKey(v)
	})
}

// UpdateDimensionKey sets the "dimension_key" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertBulk) UpdateDimensionKey() *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateDimensionKey()
	})
}

// SetMetricDetail sets the "metric_detail" field.
func (u *FinanceDailyAggregateUpsertBulk) SetMetricDetail(v map[string]interface{}) *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetMetricDetail(v)
	})
}

// UpdateMetricDetail sets the "metric_detail" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertBulk) UpdateMetricDetail() *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateMetricDetail()
	})
}

// SetSourceRevision sets the "source_revision" field.
func (u *FinanceDailyAggregateUpsertBulk) SetSourceRevision(v int64) *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetSourceRevision(v)
	})
}

// AddSourceRevision adds v to the "source_revision" field.
func (u *FinanceDailyAggregateUpsertBulk) AddSourceRevision(v int64) *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.AddSourceRevision(v)
	})
}

// UpdateSourceRevision sets the "source_revision" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertBulk) UpdateSourceRevision() *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateSourceRevision()
	})
}

// SetGeneratedAt sets the "generated_at" field.
func (u *FinanceDailyAggregateUpsertBulk) SetGeneratedAt(v time.Time) *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.SetGeneratedAt(v)
	})
}

// UpdateGeneratedAt sets the "generated_at" field to the value that was provided on create.
func (u *FinanceDailyAggregateUpsertBulk) UpdateGeneratedAt() *FinanceDailyAggregateUpsertBulk {
	return u.Update(func(s *FinanceDailyAggregateUpsert) {
		s.UpdateGeneratedAt()
	})
}

// Exec executes the query.
func (u *FinanceDailyAggregateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FinanceDailyAggregateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FinanceDailyAggregateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FinanceDailyAggregateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
