// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/financecalculationrevision"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// FinanceCalculationRevisionUpdate is the builder for updating FinanceCalculationRevision entities.
type FinanceCalculationRevisionUpdate struct {
	config
	hooks    []Hook
	mutation *FinanceCalculationRevisionMutation
}

// Where appends a list predicates to the FinanceCalculationRevisionUpdate builder.
func (_u *FinanceCalculationRevisionUpdate) Where(ps ...predicate.FinanceCalculationRevision) *FinanceCalculationRevisionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *FinanceCalculationRevisionUpdate) SetEntityType(v string) *FinanceCalculationRevisionUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdate) SetNillableEntityType(v *string) *FinanceCalculationRevisionUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *FinanceCalculationRevisionUpdate) SetEntityID(v int64) *FinanceCalculationRevisionUpdate {
	_u.mutation.ResetEntityID()
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdate) SetNillableEntityID(v *int64) *FinanceCalculationRevisionUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// AddEntityID adds value to the "entity_id" field.
func (_u *FinanceCalculationRevisionUpdate) AddEntityID(v int64) *FinanceCalculationRevisionUpdate {
	_u.mutation.AddEntityID(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *FinanceCalculationRevisionUpdate) SetRevision(v int) *FinanceCalculationRevisionUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdate) SetNillableRevision(v *int) *FinanceCalculationRevisionUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *FinanceCalculationRevisionUpdate) AddRevision(v int) *FinanceCalculationRevisionUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetOldResult sets the "old_result" field.
func (_u *FinanceCalculationRevisionUpdate) SetOldResult(v map[string]interface{}) *FinanceCalculationRevisionUpdate {
	_u.mutation.SetOldResult(v)
	return _u
}

// ClearOldResult clears the value of the "old_result" field.
func (_u *FinanceCalculationRevisionUpdate) ClearOldResult() *FinanceCalculationRevisionUpdate {
	_u.mutation.ClearOldResult()
	return _u
}

// SetNewResult sets the "new_result" field.
func (_u *FinanceCalculationRevisionUpdate) SetNewResult(v map[string]interface{}) *FinanceCalculationRevisionUpdate {
	_u.mutation.SetNewResult(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *FinanceCalculationRevisionUpdate) SetReason(v string) *FinanceCalculationRevisionUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdate) SetNillableReason(v *string) *FinanceCalculationRevisionUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *FinanceCalculationRevisionUpdate) SetJobID(v int64) *FinanceCalculationRevisionUpdate {
	_u.mutation.ResetJobID()
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdate) SetNillableJobID(v *int64) *FinanceCalculationRevisionUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// AddJobID adds value to the "job_id" field.
func (_u *FinanceCalculationRevisionUpdate) AddJobID(v int64) *FinanceCalculationRevisionUpdate {
	_u.mutation.AddJobID(v)
	return _u
}

// ClearJobID clears the value of the "job_id" field.
func (_u *FinanceCalculationRevisionUpdate) ClearJobID() *FinanceCalculationRevisionUpdate {
	_u.mutation.ClearJobID()
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *FinanceCalculationRevisionUpdate) SetOperatorID(v int64) *FinanceCalculationRevisionUpdate {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdate) SetNillableOperatorID(v *int64) *FinanceCalculationRevisionUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *FinanceCalculationRevisionUpdate) AddOperatorID(v int64) *FinanceCalculationRevisionUpdate {
	_u.mutation.AddOperatorID(v)
	return _u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (_u *FinanceCalculationRevisionUpdate) ClearOperatorID() *FinanceCalculationRevisionUpdate {
	_u.mutation.ClearOperatorID()
	return _u
}

// Mutation returns the FinanceCalculationRevisionMutation object of the builder.
func (_u *FinanceCalculationRevisionUpdate) Mutation() *FinanceCalculationRevisionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FinanceCalculationRevisionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FinanceCalculationRevisionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FinanceCalculationRevisionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FinanceCalculationRevisionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FinanceCalculationRevisionUpdate) check() error {
	if v, ok := _u.mutation.EntityType(); ok {
		if err := financecalculationrevision.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "FinanceCalculationRevision.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := financecalculationrevision.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "FinanceCalculationRevision.revision": %w`, err)}
		}
	}
	return nil
}

func (_u *FinanceCalculationRevisionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(financecalculationrevision.Table, financecalculationrevision.Columns, sqlgraph.NewFieldSpec(financecalculationrevision.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(financecalculationrevision.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(financecalculationrevision.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntityID(); ok {
		_spec.AddField(financecalculationrevision.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(financecalculationrevision.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(financecalculationrevision.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OldResult(); ok {
		_spec.SetField(financecalculationrevision.FieldOldResult, field.TypeJSON, value)
	}
	if _u.mutation.OldResultCleared() {
		_spec.ClearField(financecalculationrevision.FieldOldResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.NewResult(); ok {
		_spec.SetField(financecalculationrevision.FieldNewResult, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(financecalculationrevision.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(financecalculationrevision.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedJobID(); ok {
		_spec.AddField(financecalculationrevision.FieldJobID, field.TypeInt64, value)
	}
	if _u.mutation.JobIDCleared() {
		_spec.ClearField(financecalculationrevision.FieldJobID, field.TypeInt64)
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(financecalculationrevision.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(financecalculationrevision.FieldOperatorID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorIDCleared() {
		_spec.ClearField(financecalculationrevision.FieldOperatorID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{financecalculationrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FinanceCalculationRevisionUpdateOne is the builder for updating a single FinanceCalculationRevision entity.
type FinanceCalculationRevisionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FinanceCalculationRevisionMutation
}

// SetEntityType sets the "entity_type" field.
func (_u *FinanceCalculationRevisionUpdateOne) SetEntityType(v string) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdateOne) SetNillableEntityType(v *string) *FinanceCalculationRevisionUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *FinanceCalculationRevisionUpdateOne) SetEntityID(v int64) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.ResetEntityID()
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdateOne) SetNillableEntityID(v *int64) *FinanceCalculationRevisionUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// AddEntityID adds value to the "entity_id" field.
func (_u *FinanceCalculationRevisionUpdateOne) AddEntityID(v int64) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.AddEntityID(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *FinanceCalculationRevisionUpdateOne) SetRevision(v int) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdateOne) SetNillableRevision(v *int) *FinanceCalculationRevisionUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *FinanceCalculationRevisionUpdateOne) AddRevision(v int) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetOldResult sets the "old_result" field.
func (_u *FinanceCalculationRevisionUpdateOne) SetOldResult(v map[string]interface{}) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.SetOldResult(v)
	return _u
}

// ClearOldResult clears the value of the "old_result" field.
func (_u *FinanceCalculationRevisionUpdateOne) ClearOldResult() *FinanceCalculationRevisionUpdateOne {
	_u.mutation.ClearOldResult()
	return _u
}

// SetNewResult sets the "new_result" field.
func (_u *FinanceCalculationRevisionUpdateOne) SetNewResult(v map[string]interface{}) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.SetNewResult(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *FinanceCalculationRevisionUpdateOne) SetReason(v string) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdateOne) SetNillableReason(v *string) *FinanceCalculationRevisionUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *FinanceCalculationRevisionUpdateOne) SetJobID(v int64) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.ResetJobID()
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdateOne) SetNillableJobID(v *int64) *FinanceCalculationRevisionUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// AddJobID adds value to the "job_id" field.
func (_u *FinanceCalculationRevisionUpdateOne) AddJobID(v int64) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.AddJobID(v)
	return _u
}

// ClearJobID clears the value of the "job_id" field.
func (_u *FinanceCalculationRevisionUpdateOne) ClearJobID() *FinanceCalculationRevisionUpdateOne {
	_u.mutation.ClearJobID()
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *FinanceCalculationRevisionUpdateOne) SetOperatorID(v int64) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *FinanceCalculationRevisionUpdateOne) SetNillableOperatorID(v *int64) *FinanceCalculationRevisionUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *FinanceCalculationRevisionUpdateOne) AddOperatorID(v int64) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.AddOperatorID(v)
	return _u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (_u *FinanceCalculationRevisionUpdateOne) ClearOperatorID() *FinanceCalculationRevisionUpdateOne {
	_u.mutation.ClearOperatorID()
	return _u
}

// Mutation returns the FinanceCalculationRevisionMutation object of the builder.
func (_u *FinanceCalculationRevisionUpdateOne) Mutation() *FinanceCalculationRevisionMutation {
	return _u.mutation
}

// Where appends a list predicates to the FinanceCalculationRevisionUpdate builder.
func (_u *FinanceCalculationRevisionUpdateOne) Where(ps ...predicate.FinanceCalculationRevision) *FinanceCalculationRevisionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FinanceCalculationRevisionUpdateOne) Select(field string, fields ...string) *FinanceCalculationRevisionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FinanceCalculationRevision entity.
func (_u *FinanceCalculationRevisionUpdateOne) Save(ctx context.Context) (*FinanceCalculationRevision, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FinanceCalculationRevisionUpdateOne) SaveX(ctx context.Context) *FinanceCalculationRevision {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FinanceCalculationRevisionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FinanceCalculationRevisionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FinanceCalculationRevisionUpdateOne) check() error {
	if v, ok := _u.mutation.EntityType(); ok {
		if err := financecalculationrevision.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "FinanceCalculationRevision.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := financecalculationrevision.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "FinanceCalculationRevision.revision": %w`, err)}
		}
	}
	return nil
}

func (_u *FinanceCalculationRevisionUpdateOne) sqlSave(ctx context.Context) (_node *FinanceCalculationRevision, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(financecalculationrevision.Table, financecalculationrevision.Columns, sqlgraph.NewFieldSpec(financecalculationrevision.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FinanceCalculationRevision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, financecalculationrevision.FieldID)
		for _, f := range fields {
			if !financecalculationrevision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != financecalculationrevision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(financecalculationrevision.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(financecalculationrevision.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntityID(); ok {
		_spec.AddField(financecalculationrevision.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(financecalculationrevision.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(financecalculationrevision.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OldResult(); ok {
		_spec.SetField(financecalculationrevision.FieldOldResult, field.TypeJSON, value)
	}
	if _u.mutation.OldResultCleared() {
		_spec.ClearField(financecalculationrevision.FieldOldResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.NewResult(); ok {
		_spec.SetField(financecalculationrevision.FieldNewResult, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(financecalculationrevision.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(financecalculationrevision.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedJobID(); ok {
		_spec.AddField(financecalculationrevision.FieldJobID, field.TypeInt64, value)
	}
	if _u.mutation.JobIDCleared() {
		_spec.ClearField(financecalculationrevision.FieldJobID, field.TypeInt64)
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(financecalculationrevision.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(financecalculationrevision.FieldOperatorID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorIDCleared() {
		_spec.ClearField(financecalculationrevision.FieldOperatorID, field.TypeInt64)
	}
	_node = &FinanceCalculationRevision{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{financecalculationrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
