// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/financefxrateversion"
	"github.com/shopspring/decimal"
)

// FinanceFXRateVersionCreate is the builder for creating a FinanceFXRateVersion entity.
type FinanceFXRateVersionCreate struct {
	config
	mutation *FinanceFXRateVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCurrency sets the "currency" field.
func (_c *FinanceFXRateVersionCreate) SetCurrency(v string) *FinanceFXRateVersionCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetRateToUsd sets the "rate_to_usd" field.
func (_c *FinanceFXRateVersionCreate) SetRateToUsd(v decimal.Decimal) *FinanceFXRateVersionCreate {
	_c.mutation.SetRateToUsd(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *FinanceFXRateVersionCreate) SetSource(v string) *FinanceFXRateVersionCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *FinanceFXRateVersionCreate) SetObservedAt(v time.Time) *FinanceFXRateVersionCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetEffectiveFrom sets the "effective_from" field.
func (_c *FinanceFXRateVersionCreate) SetEffectiveFrom(v time.Time) *FinanceFXRateVersionCreate {
	_c.mutation.SetEffectiveFrom(v)
	return _c
}

// SetEffectiveTo sets the "effective_to" field.
func (_c *FinanceFXRateVersionCreate) SetEffectiveTo(v time.Time) *FinanceFXRateVersionCreate {
	_c.mutation.SetEffectiveTo(v)
	return _c
}

// SetNillableEffectiveTo sets the "effective_to" field if the given value is not nil.
func (_c *FinanceFXRateVersionCreate) SetNillableEffectiveTo(v *time.Time) *FinanceFXRateVersionCreate {
	if v != nil {
		_c.SetEffectiveTo(*v)
	}
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *FinanceFXRateVersionCreate) SetChecksum(v string) *FinanceFXRateVersionCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FinanceFXRateVersionCreate) SetCreatedAt(v time.Time) *FinanceFXRateVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FinanceFXRateVersionCreate) SetNillableCreatedAt(v *time.Time) *FinanceFXRateVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the FinanceFXRateVersionMutation object of the builder.
func (_c *FinanceFXRateVersionCreate) Mutation() *FinanceFXRateVersionMutation {
	return _c.mutation
}

// Save creates the FinanceFXRateVersion in the database.
func (_c *FinanceFXRateVersionCreate) Save(ctx context.Context) (*FinanceFXRateVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FinanceFXRateVersionCreate) SaveX(ctx context.Context) *FinanceFXRateVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceFXRateVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceFXRateVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FinanceFXRateVersionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := financefxrateversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FinanceFXRateVersionCreate) check() error {
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "FinanceFXRateVersion.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := financefxrateversion.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "FinanceFXRateVersion.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateToUsd(); !ok {
		return &ValidationError{Name: "rate_to_usd", err: errors.New(`ent: missing required field "FinanceFXRateVersion.rate_to_usd"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "FinanceFXRateVersion.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := financefxrateversion.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "FinanceFXRateVersion.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		return &ValidationError{Name: "observed_at", err: errors.New(`ent: missing required field "FinanceFXRateVersion.observed_at"`)}
	}
	if _, ok := _c.mutation.EffectiveFrom(); !ok {
		return &ValidationError{Name: "effective_from", err: errors.New(`ent: missing required field "FinanceFXRateVersion.effective_from"`)}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "FinanceFXRateVersion.checksum"`)}
	}
	if v, ok := _c.mutation.Checksum(); ok {
		if err := financefxrateversion.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "FinanceFXRateVersion.checksum": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FinanceFXRateVersion.created_at"`)}
	}
	return nil
}

func (_c *FinanceFXRateVersionCreate) sqlSave(ctx context.Context) (*FinanceFXRateVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FinanceFXRateVersionCreate) createSpec() (*FinanceFXRateVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &FinanceFXRateVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(financefxrateversion.Table, sqlgraph.NewFieldSpec(financefxrateversion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(financefxrateversion.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.RateToUsd(); ok {
		_spec.SetField(financefxrateversion.FieldRateToUsd, field.TypeFloat64, value)
		_node.RateToUsd = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(financefxrateversion.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(financefxrateversion.FieldObservedAt, field.TypeTime, value)
		_node.ObservedAt = value
	}
	if value, ok := _c.mutation.EffectiveFrom(); ok {
		_spec.SetField(financefxrateversion.FieldEffectiveFrom, field.TypeTime, value)
		_node.EffectiveFrom = value
	}
	if value, ok := _c.mutation.EffectiveTo(); ok {
		_spec.SetField(financefxrateversion.FieldEffectiveTo, field.TypeTime, value)
		_node.EffectiveTo = &value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(financefxrateversion.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(financefxrateversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FinanceFXRateVersion.Create().
//		SetCurrency(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FinanceFXRateVersionUpsert) {
//			SetCurrency(v+v).
//		}).
//		Exec(ctx)
func (_c *FinanceFXRateVersionCreate) OnConflict(opts ...sql.ConflictOption) *FinanceFXRateVersionUpsertOne {
	_c.conflict = opts
	return &FinanceFXRateVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FinanceFXRateVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FinanceFXRateVersionCreate) OnConflictColumns(columns ...string) *FinanceFXRateVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FinanceFXRateVersionUpsertOne{
		create: _c,
	}
}

type (
	// FinanceFXRateVersionUpsertOne is the builder for "upsert"-ing
	//  one FinanceFXRateVersion node.
	FinanceFXRateVersionUpsertOne struct {
		create *FinanceFXRateVersionCreate
	}

	// FinanceFXRateVersionUpsert is the "OnConflict" setter.
	FinanceFXRateVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetCurrency sets the "currency" field.
func (u *FinanceFXRateVersionUpsert) SetCurrency(v string) *FinanceFXRateVersionUpsert {
	u.Set(financefxrateversion.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsert) UpdateCurrency() *FinanceFXRateVersionUpsert {
	u.SetExcluded(financefxrateversion.FieldCurrency)
	return u
}

// SetRateToUsd sets the "rate_to_usd" field.
func (u *FinanceFXRateVersionUpsert) SetRateToUsd(v decimal.Decimal) *FinanceFXRateVersionUpsert {
	u.Set(financefxrateversion.FieldRateToUsd, v)
	return u
}

// UpdateRateToUsd sets the "rate_to_usd" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsert) UpdateRateToUsd() *FinanceFXRateVersionUpsert {
	u.SetExcluded(financefxrateversion.FieldRateToUsd)
	return u
}

// AddRateToUsd adds v to the "rate_to_usd" field.
func (u *FinanceFXRateVersionUpsert) AddRateToUsd(v decimal.Decimal) *FinanceFXRateVersionUpsert {
	u.Add(financefxrateversion.FieldRateToUsd, v)
	return u
}

// SetSource sets the "source" field.
func (u *FinanceFXRateVersionUpsert) SetSource(v string) *FinanceFXRateVersionUpsert {
	u.Set(financefxrateversion.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsert) UpdateSource() *FinanceFXRateVersionUpsert {
	u.SetExcluded(financefxrateversion.FieldSource)
	return u
}

// SetObservedAt sets the "observed_at" field.
func (u *FinanceFXRateVersionUpsert) SetObservedAt(v time.Time) *FinanceFXRateVersionUpsert {
	u.Set(financefxrateversion.FieldObservedAt, v)
	return u
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsert) UpdateObservedAt() *FinanceFXRateVersionUpsert {
	u.SetExcluded(financefxrateversion.FieldObservedAt)
	return u
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *FinanceFXRateVersionUpsert) SetEffectiveFrom(v time.Time) *FinanceFXRateVersionUpsert {
	u.Set(financefxrateversion.FieldEffectiveFrom, v)
	return u
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsert) UpdateEffectiveFrom() *FinanceFXRateVersionUpsert {
	u.SetExcluded(financefxrateversion.FieldEffectiveFrom)
	return u
}

// SetEffectiveTo sets the "effective_to" field.
func (u *FinanceFXRateVersionUpsert) SetEffectiveTo(v time.Time) *FinanceFXRateVersionUpsert {
	u.Set(financefxrateversion.FieldEffectiveTo, v)
	return u
}

// UpdateEffectiveTo sets the "effective_to" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsert) UpdateEffectiveTo() *FinanceFXRateVersionUpsert {
	u.SetExcluded(financefxrateversion.FieldEffectiveTo)
	return u
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (u *FinanceFXRateVersionUpsert) ClearEffectiveTo() *FinanceFXRateVersionUpsert {
	u.SetNull(financefxrateversion.FieldEffectiveTo)
	return u
}

// SetChecksum sets the "checksum" field.
func (u *FinanceFXRateVersionUpsert) SetChecksum(v string) *FinanceFXRateVersionUpsert {
	u.Set(financefxrateversion.FieldChecksum, v)
	return u
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsert) UpdateChecksum() *FinanceFXRateVersionUpsert {
	u.SetExcluded(financefxrateversion.FieldChecksum)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FinanceFXRateVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FinanceFXRateVersionUpsertOne) UpdateNewValues() *FinanceFXRateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(financefxrateversion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FinanceFXRateVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FinanceFXRateVersionUpsertOne) Ignore() *FinanceFXRateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FinanceFXRateVersionUpsertOne) DoNothing() *FinanceFXRateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FinanceFXRateVersionCreate.OnConflict
// documentation for more info.
func (u *FinanceFXRateVersionUpsertOne) Update(set func(*FinanceFXRateVersionUpsert)) *FinanceFXRateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FinanceFXRateVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCurrency sets the "currency" field.
func (u *FinanceFXRateVersionUpsertOne) SetCurrency(v string) *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertOne) UpdateCurrency() *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateCurrency()
	})
}

// SetRateToUsd sets the "rate_to_usd" field.
func (u *FinanceFXRateVersionUpsertOne) SetRateToUsd(v decimal.Decimal) *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetRateToUsd(v)
	})
}

// AddRateToUsd adds v to the "rate_to_usd" field.
func (u *FinanceFXRateVersionUpsertOne) AddRateToUsd(v decimal.Decimal) *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.AddRateToUsd(v)
	})
}

// UpdateRateToUsd sets the "rate_to_usd" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertOne) UpdateRateToUsd() *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateRateToUsd()
	})
}

// SetSource sets the "source" field.
func (u *FinanceFXRateVersionUpsertOne) SetSource(v string) *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertOne) UpdateSource() *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateSource()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *FinanceFXRateVersionUpsertOne) SetObservedAt(v time.Time) *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertOne) UpdateObservedAt() *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateObservedAt()
	})
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *FinanceFXRateVersionUpsertOne) SetEffectiveFrom(v time.Time) *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetEffectiveFrom(v)
	})
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertOne) UpdateEffectiveFrom() *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateEffectiveFrom()
	})
}

// SetEffectiveTo sets the "effective_to" field.
func (u *FinanceFXRateVersionUpsertOne) SetEffectiveTo(v time.Time) *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetEffectiveTo(v)
	})
}

// UpdateEffectiveTo sets the "effective_to" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertOne) UpdateEffectiveTo() *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateEffectiveTo()
	})
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (u *FinanceFXRateVersionUpsertOne) ClearEffectiveTo() *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.ClearEffectiveTo()
	})
}

// SetChecksum sets the "checksum" field.
func (u *FinanceFXRateVersionUpsertOne) SetChecksum(v string) *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertOne) UpdateChecksum() *FinanceFXRateVersionUpsertOne {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateChecksum()
	})
}

// Exec executes the query.
func (u *FinanceFXRateVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FinanceFXRateVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FinanceFXRateVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FinanceFXRateVersionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FinanceFXRateVersionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FinanceFXRateVersionCreateBulk is the builder for creating many FinanceFXRateVersion entities in bulk.
type FinanceFXRateVersionCreateBulk struct {
	config
	err      error
	builders []*FinanceFXRateVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the FinanceFXRateVersion entities in the database.
func (_c *FinanceFXRateVersionCreateBulk) Save(ctx context.Context) ([]*FinanceFXRateVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FinanceFXRateVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FinanceFXRateVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FinanceFXRateVersionCreateBulk) SaveX(ctx context.Context) []*FinanceFXRateVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceFXRateVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceFXRateVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FinanceFXRateVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FinanceFXRateVersionUpsert) {
//			SetCurrency(v+v).
//		}).
//		Exec(ctx)
func (_c *FinanceFXRateVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *FinanceFXRateVersionUpsertBulk {
	_c.conflict = opts
	return &FinanceFXRateVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FinanceFXRateVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FinanceFXRateVersionCreateBulk) OnConflictColumns(columns ...string) *FinanceFXRateVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FinanceFXRateVersionUpsertBulk{
		create: _c,
	}
}

// FinanceFXRateVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of FinanceFXRateVersion nodes.
type FinanceFXRateVersionUpsertBulk struct {
	create *FinanceFXRateVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FinanceFXRateVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FinanceFXRateVersionUpsertBulk) UpdateNewValues() *FinanceFXRateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(financefxrateversion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FinanceFXRateVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FinanceFXRateVersionUpsertBulk) Ignore() *FinanceFXRateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FinanceFXRateVersionUpsertBulk) DoNothing() *FinanceFXRateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FinanceFXRateVersionCreateBulk.OnConflict
// documentation for more info.
func (u *FinanceFXRateVersionUpsertBulk) Update(set func(*FinanceFXRateVersionUpsert)) *FinanceFXRateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FinanceFXRateVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCurrency sets the "currency" field.
func (u *FinanceFXRateVersionUpsertBulk) SetCurrency(v string) *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertBulk) UpdateCurrency() *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateCurrency()
	})
}

// SetRateToUsd sets the "rate_to_usd" field.
func (u *FinanceFXRateVersionUpsertBulk) SetRateToUsd(v decimal.Decimal) *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetRateToUsd(v)
	})
}

// AddRateToUsd adds v to the "rate_to_usd" field.
func (u *FinanceFXRateVersionUpsertBulk) AddRateToUsd(v decimal.Decimal) *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.AddRateToUsd(v)
	})
}

// UpdateRateToUsd sets the "rate_to_usd" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertBulk) UpdateRateToUsd() *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateRateToUsd()
	})
}

// SetSource sets the "source" field.
func (u *FinanceFXRateVersionUpsertBulk) SetSource(v string) *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertBulk) UpdateSource() *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateSource()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *FinanceFXRateVersionUpsertBulk) SetObservedAt(v time.Time) *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertBulk) UpdateObservedAt() *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateObservedAt()
	})
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *FinanceFXRateVersionUpsertBulk) SetEffectiveFrom(v time.Time) *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetEffectiveFrom(v)
	})
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertBulk) UpdateEffectiveFrom() *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateEffectiveFrom()
	})
}

// SetEffectiveTo sets the "effective_to" field.
func (u *FinanceFXRateVersionUpsertBulk) SetEffectiveTo(v time.Time) *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetEffectiveTo(v)
	})
}

// UpdateEffectiveTo sets the "effective_to" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertBulk) UpdateEffectiveTo() *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateEffectiveTo()
	})
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (u *FinanceFXRateVersionUpsertBulk) ClearEffectiveTo() *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.ClearEffectiveTo()
	})
}

// SetChecksum sets the "checksum" field.
func (u *FinanceFXRateVersionUpsertBulk) SetChecksum(v string) *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *FinanceFXRateVersionUpsertBulk) UpdateChecksum() *FinanceFXRateVersionUpsertBulk {
	return u.Update(func(s *FinanceFXRateVersionUpsert) {
		s.UpdateChecksum()
	})
}

// Exec executes the query.
func (u *FinanceFXRateVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FinanceFXRateVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FinanceFXRateVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FinanceFXRateVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
