// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrevenuerecognition"
	"github.com/shopspring/decimal"
)

// SubscriptionRevenueRecognitionUpdate is the builder for updating SubscriptionRevenueRecognition entities.
type SubscriptionRevenueRecognitionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionRevenueRecognitionMutation
}

// Where appends a list predicates to the SubscriptionRevenueRecognitionUpdate builder.
func (_u *SubscriptionRevenueRecognitionUpdate) Where(ps ...predicate.SubscriptionRevenueRecognition) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetPaymentOrderID(v int64) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdate) SetNillablePaymentOrderID(v *int64) *SubscriptionRevenueRecognitionUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *SubscriptionRevenueRecognitionUpdate) AddPaymentOrderID(v int64) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetUserID(v int64) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdate) SetNillableUserID(v *int64) *SubscriptionRevenueRecognitionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionRevenueRecognitionUpdate) AddUserID(v int64) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetGroupID(v int64) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdate) SetNillableGroupID(v *int64) *SubscriptionRevenueRecognitionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionRevenueRecognitionUpdate) AddGroupID(v int64) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *SubscriptionRevenueRecognitionUpdate) ClearGroupID() *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetRecognitionDate sets the "recognition_date" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetRecognitionDate(v time.Time) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.SetRecognitionDate(v)
	return _u
}

// SetNillableRecognitionDate sets the "recognition_date" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdate) SetNillableRecognitionDate(v *time.Time) *SubscriptionRevenueRecognitionUpdate {
	if v != nil {
		_u.SetRecognitionDate(*v)
	}
	return _u
}

// SetRecognizedRevenue sets the "recognized_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetRecognizedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ResetRecognizedRevenue()
	_u.mutation.SetRecognizedRevenue(v)
	return _u
}

// SetNillableRecognizedRevenue sets the "recognized_revenue" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdate) SetNillableRecognizedRevenue(v *decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	if v != nil {
		_u.SetRecognizedRevenue(*v)
	}
	return _u
}

// AddRecognizedRevenue adds value to the "recognized_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdate) AddRecognizedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.AddRecognizedRevenue(v)
	return _u
}

// SetRefundReduction sets the "refund_reduction" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetRefundReduction(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ResetRefundReduction()
	_u.mutation.SetRefundReduction(v)
	return _u
}

// SetNillableRefundReduction sets the "refund_reduction" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdate) SetNillableRefundReduction(v *decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	if v != nil {
		_u.SetRefundReduction(*v)
	}
	return _u
}

// AddRefundReduction adds value to the "refund_reduction" field.
func (_u *SubscriptionRevenueRecognitionUpdate) AddRefundReduction(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.AddRefundReduction(v)
	return _u
}

// ClearRefundReduction clears the value of the "refund_reduction" field.
func (_u *SubscriptionRevenueRecognitionUpdate) ClearRefundReduction() *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ClearRefundReduction()
	return _u
}

// SetAllocatedRevenue sets the "allocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetAllocatedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ResetAllocatedRevenue()
	_u.mutation.SetAllocatedRevenue(v)
	return _u
}

// SetNillableAllocatedRevenue sets the "allocated_revenue" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdate) SetNillableAllocatedRevenue(v *decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	if v != nil {
		_u.SetAllocatedRevenue(*v)
	}
	return _u
}

// AddAllocatedRevenue adds value to the "allocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdate) AddAllocatedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.AddAllocatedRevenue(v)
	return _u
}

// ClearAllocatedRevenue clears the value of the "allocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdate) ClearAllocatedRevenue() *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ClearAllocatedRevenue()
	return _u
}

// SetUnallocatedRevenue sets the "unallocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetUnallocatedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ResetUnallocatedRevenue()
	_u.mutation.SetUnallocatedRevenue(v)
	return _u
}

// SetNillableUnallocatedRevenue sets the "unallocated_revenue" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdate) SetNillableUnallocatedRevenue(v *decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	if v != nil {
		_u.SetUnallocatedRevenue(*v)
	}
	return _u
}

// AddUnallocatedRevenue adds value to the "unallocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdate) AddUnallocatedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.AddUnallocatedRevenue(v)
	return _u
}

// ClearUnallocatedRevenue clears the value of the "unallocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdate) ClearUnallocatedRevenue() *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ClearUnallocatedRevenue()
	return _u
}

// SetAllocationStatus sets the "allocation_status" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetAllocationStatus(v string) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.SetAllocationStatus(v)
	return _u
}

// SetNillableAllocationStatus sets the "allocation_status" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdate) SetNillableAllocationStatus(v *string) *SubscriptionRevenueRecognitionUpdate {
	if v != nil {
		_u.SetAllocationStatus(*v)
	}
	return _u
}

// SetCalculationDetail sets the "calculation_detail" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetCalculationDetail(v map[string]interface{}) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.SetCalculationDetail(v)
	return _u
}

// SetCurrentRevision sets the "current_revision" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetCurrentRevision(v int) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.ResetCurrentRevision()
	_u.mutation.SetCurrentRevision(v)
	return _u
}

// SetNillableCurrentRevision sets the "current_revision" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdate) SetNillableCurrentRevision(v *int) *SubscriptionRevenueRecognitionUpdate {
	if v != nil {
		_u.SetCurrentRevision(*v)
	}
	return _u
}

// AddCurrentRevision adds value to the "current_revision" field.
func (_u *SubscriptionRevenueRecognitionUpdate) AddCurrentRevision(v int) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.AddCurrentRevision(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionRevenueRecognitionUpdate) SetUpdatedAt(v time.Time) *SubscriptionRevenueRecognitionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionRevenueRecognitionMutation object of the builder.
func (_u *SubscriptionRevenueRecognitionUpdate) Mutation() *SubscriptionRevenueRecognitionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionRevenueRecognitionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionRevenueRecognitionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionRevenueRecognitionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionRevenueRecognitionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionRevenueRecognitionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionrevenuerecognition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionRevenueRecognitionUpdate) check() error {
	if v, ok := _u.mutation.AllocationStatus(); ok {
		if err := subscriptionrevenuerecognition.AllocationStatusValidator(v); err != nil {
			return &ValidationError{Name: "allocation_status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionRevenueRecognition.allocation_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentRevision(); ok {
		if err := subscriptionrevenuerecognition.CurrentRevisionValidator(v); err != nil {
			return &ValidationError{Name: "current_revision", err: fmt.Errorf(`ent: validator failed for field "SubscriptionRevenueRecognition.current_revision": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionRevenueRecognitionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionrevenuerecognition.Table, subscriptionrevenuerecognition.Columns, sqlgraph.NewFieldSpec(subscriptionrevenuerecognition.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(subscriptionrevenuerecognition.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RecognitionDate(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldRecognitionDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecognizedRevenue(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldRecognizedRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRecognizedRevenue(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldRecognizedRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundReduction(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldRefundReduction, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundReduction(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldRefundReduction, field.TypeFloat64, value)
	}
	if _u.mutation.RefundReductionCleared() {
		_spec.ClearField(subscriptionrevenuerecognition.FieldRefundReduction, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AllocatedRevenue(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldAllocatedRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAllocatedRevenue(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldAllocatedRevenue, field.TypeFloat64, value)
	}
	if _u.mutation.AllocatedRevenueCleared() {
		_spec.ClearField(subscriptionrevenuerecognition.FieldAllocatedRevenue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UnallocatedRevenue(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldUnallocatedRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnallocatedRevenue(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldUnallocatedRevenue, field.TypeFloat64, value)
	}
	if _u.mutation.UnallocatedRevenueCleared() {
		_spec.ClearField(subscriptionrevenuerecognition.FieldUnallocatedRevenue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AllocationStatus(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldAllocationStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CalculationDetail(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldCalculationDetail, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CurrentRevision(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldCurrentRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentRevision(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldCurrentRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionrevenuerecognition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionRevenueRecognitionUpdateOne is the builder for updating a single SubscriptionRevenueRecognition entity.
type SubscriptionRevenueRecognitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionRevenueRecognitionMutation
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetPaymentOrderID(v int64) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetNillablePaymentOrderID(v *int64) *SubscriptionRevenueRecognitionUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) AddPaymentOrderID(v int64) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetUserID(v int64) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetNillableUserID(v *int64) *SubscriptionRevenueRecognitionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) AddUserID(v int64) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetGroupID(v int64) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetNillableGroupID(v *int64) *SubscriptionRevenueRecognitionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) AddGroupID(v int64) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) ClearGroupID() *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetRecognitionDate sets the "recognition_date" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetRecognitionDate(v time.Time) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.SetRecognitionDate(v)
	return _u
}

// SetNillableRecognitionDate sets the "recognition_date" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetNillableRecognitionDate(v *time.Time) *SubscriptionRevenueRecognitionUpdateOne {
	if v != nil {
		_u.SetRecognitionDate(*v)
	}
	return _u
}

// SetRecognizedRevenue sets the "recognized_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetRecognizedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ResetRecognizedRevenue()
	_u.mutation.SetRecognizedRevenue(v)
	return _u
}

// SetNillableRecognizedRevenue sets the "recognized_revenue" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetNillableRecognizedRevenue(v *decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	if v != nil {
		_u.SetRecognizedRevenue(*v)
	}
	return _u
}

// AddRecognizedRevenue adds value to the "recognized_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) AddRecognizedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.AddRecognizedRevenue(v)
	return _u
}

// SetRefundReduction sets the "refund_reduction" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetRefundReduction(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ResetRefundReduction()
	_u.mutation.SetRefundReduction(v)
	return _u
}

// SetNillableRefundReduction sets the "refund_reduction" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetNillableRefundReduction(v *decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	if v != nil {
		_u.SetRefundReduction(*v)
	}
	return _u
}

// AddRefundReduction adds value to the "refund_reduction" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) AddRefundReduction(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.AddRefundReduction(v)
	return _u
}

// ClearRefundReduction clears the value of the "refund_reduction" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) ClearRefundReduction() *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ClearRefundReduction()
	return _u
}

// SetAllocatedRevenue sets the "allocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetAllocatedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ResetAllocatedRevenue()
	_u.mutation.SetAllocatedRevenue(v)
	return _u
}

// SetNillableAllocatedRevenue sets the "allocated_revenue" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetNillableAllocatedRevenue(v *decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	if v != nil {
		_u.SetAllocatedRevenue(*v)
	}
	return _u
}

// AddAllocatedRevenue adds value to the "allocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) AddAllocatedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.AddAllocatedRevenue(v)
	return _u
}

// ClearAllocatedRevenue clears the value of the "allocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) ClearAllocatedRevenue() *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ClearAllocatedRevenue()
	return _u
}

// SetUnallocatedRevenue sets the "unallocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetUnallocatedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ResetUnallocatedRevenue()
	_u.mutation.SetUnallocatedRevenue(v)
	return _u
}

// SetNillableUnallocatedRevenue sets the "unallocated_revenue" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetNillableUnallocatedRevenue(v *decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	if v != nil {
		_u.SetUnallocatedRevenue(*v)
	}
	return _u
}

// AddUnallocatedRevenue adds value to the "unallocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) AddUnallocatedRevenue(v decimal.Decimal) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.AddUnallocatedRevenue(v)
	return _u
}

// ClearUnallocatedRevenue clears the value of the "unallocated_revenue" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) ClearUnallocatedRevenue() *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ClearUnallocatedRevenue()
	return _u
}

// SetAllocationStatus sets the "allocation_status" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetAllocationStatus(v string) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.SetAllocationStatus(v)
	return _u
}

// SetNillableAllocationStatus sets the "allocation_status" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetNillableAllocationStatus(v *string) *SubscriptionRevenueRecognitionUpdateOne {
	if v != nil {
		_u.SetAllocationStatus(*v)
	}
	return _u
}

// SetCalculationDetail sets the "calculation_detail" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetCalculationDetail(v map[string]interface{}) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.SetCalculationDetail(v)
	return _u
}

// SetCurrentRevision sets the "current_revision" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetCurrentRevision(v int) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.ResetCurrentRevision()
	_u.mutation.SetCurrentRevision(v)
	return _u
}

// SetNillableCurrentRevision sets the "current_revision" field if the given value is not nil.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetNillableCurrentRevision(v *int) *SubscriptionRevenueRecognitionUpdateOne {
	if v != nil {
		_u.SetCurrentRevision(*v)
	}
	return _u
}

// AddCurrentRevision adds value to the "current_revision" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) AddCurrentRevision(v int) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.AddCurrentRevision(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionRevenueRecognitionMutation object of the builder.
func (_u *SubscriptionRevenueRecognitionUpdateOne) Mutation() *SubscriptionRevenueRecognitionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionRevenueRecognitionUpdate builder.
func (_u *SubscriptionRevenueRecognitionUpdateOne) Where(ps ...predicate.SubscriptionRevenueRecognition) *SubscriptionRevenueRecognitionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionRevenueRecognitionUpdateOne) Select(field string, fields ...string) *SubscriptionRevenueRecognitionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionRevenueRecognition entity.
func (_u *SubscriptionRevenueRecognitionUpdateOne) Save(ctx context.Context) (*SubscriptionRevenueRecognition, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionRevenueRecognitionUpdateOne) SaveX(ctx context.Context) *SubscriptionRevenueRecognition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionRevenueRecognitionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionRevenueRecognitionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionRevenueRecognitionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionrevenuerecognition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionRevenueRecognitionUpdateOne) check() error {
	if v, ok := _u.mutation.AllocationStatus(); ok {
		if err := subscriptionrevenuerecognition.AllocationStatusValidator(v); err != nil {
			return &ValidationError{Name: "allocation_status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionRevenueRecognition.allocation_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentRevision(); ok {
		if err := subscriptionrevenuerecognition.CurrentRevisionValidator(v); err != nil {
			return &ValidationError{Name: "current_revision", err: fmt.Errorf(`ent: validator failed for field "SubscriptionRevenueRecognition.current_revision": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionRevenueRecognitionUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionRevenueRecognition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionrevenuerecognition.Table, subscriptionrevenuerecognition.Columns, sqlgraph.NewFieldSpec(subscriptionrevenuerecognition.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionRevenueRecognition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionrevenuerecognition.FieldID)
		for _, f := range fields {
			if !subscriptionrevenuerecognition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionrevenuerecognition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(subscriptionrevenuerecognition.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RecognitionDate(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldRecognitionDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecognizedRevenue(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldRecognizedRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRecognizedRevenue(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldRecognizedRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundReduction(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldRefundReduction, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundReduction(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldRefundReduction, field.TypeFloat64, value)
	}
	if _u.mutation.RefundReductionCleared() {
		_spec.ClearField(subscriptionrevenuerecognition.FieldRefundReduction, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AllocatedRevenue(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldAllocatedRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAllocatedRevenue(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldAllocatedRevenue, field.TypeFloat64, value)
	}
	if _u.mutation.AllocatedRevenueCleared() {
		_spec.ClearField(subscriptionrevenuerecognition.FieldAllocatedRevenue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UnallocatedRevenue(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldUnallocatedRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnallocatedRevenue(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldUnallocatedRevenue, field.TypeFloat64, value)
	}
	if _u.mutation.UnallocatedRevenueCleared() {
		_spec.ClearField(subscriptionrevenuerecognition.FieldUnallocatedRevenue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AllocationStatus(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldAllocationStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CalculationDetail(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldCalculationDetail, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CurrentRevision(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldCurrentRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentRevision(); ok {
		_spec.AddField(subscriptionrevenuerecognition.FieldCurrentRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionrevenuerecognition.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SubscriptionRevenueRecognition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionrevenuerecognition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
