// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/systemmodelpriceversion"
)

// SystemModelPriceVersionCreate is the builder for creating a SystemModelPriceVersion entity.
type SystemModelPriceVersionCreate struct {
	config
	mutation *SystemModelPriceVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCatalogChecksum sets the "catalog_checksum" field.
func (_c *SystemModelPriceVersionCreate) SetCatalogChecksum(v string) *SystemModelPriceVersionCreate {
	_c.mutation.SetCatalogChecksum(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *SystemModelPriceVersionCreate) SetProvider(v string) *SystemModelPriceVersionCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *SystemModelPriceVersionCreate) SetModelName(v string) *SystemModelPriceVersionCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetBillingMode sets the "billing_mode" field.
func (_c *SystemModelPriceVersionCreate) SetBillingMode(v string) *SystemModelPriceVersionCreate {
	_c.mutation.SetBillingMode(v)
	return _c
}

// SetPriceDetail sets the "price_detail" field.
func (_c *SystemModelPriceVersionCreate) SetPriceDetail(v map[string]interface{}) *SystemModelPriceVersionCreate {
	_c.mutation.SetPriceDetail(v)
	return _c
}

// SetEffectiveFrom sets the "effective_from" field.
func (_c *SystemModelPriceVersionCreate) SetEffectiveFrom(v time.Time) *SystemModelPriceVersionCreate {
	_c.mutation.SetEffectiveFrom(v)
	return _c
}

// SetEffectiveTo sets the "effective_to" field.
func (_c *SystemModelPriceVersionCreate) SetEffectiveTo(v time.Time) *SystemModelPriceVersionCreate {
	_c.mutation.SetEffectiveTo(v)
	return _c
}

// SetNillableEffectiveTo sets the "effective_to" field if the given value is not nil.
func (_c *SystemModelPriceVersionCreate) SetNillableEffectiveTo(v *time.Time) *SystemModelPriceVersionCreate {
	if v != nil {
		_c.SetEffectiveTo(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SystemModelPriceVersionCreate) SetCreatedAt(v time.Time) *SystemModelPriceVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SystemModelPriceVersionCreate) SetNillableCreatedAt(v *time.Time) *SystemModelPriceVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the SystemModelPriceVersionMutation object of the builder.
func (_c *SystemModelPriceVersionCreate) Mutation() *SystemModelPriceVersionMutation {
	return _c.mutation
}

// Save creates the SystemModelPriceVersion in the database.
func (_c *SystemModelPriceVersionCreate) Save(ctx context.Context) (*SystemModelPriceVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SystemModelPriceVersionCreate) SaveX(ctx context.Context) *SystemModelPriceVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemModelPriceVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemModelPriceVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SystemModelPriceVersionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := systemmodelpriceversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SystemModelPriceVersionCreate) check() error {
	if _, ok := _c.mutation.CatalogChecksum(); !ok {
		return &ValidationError{Name: "catalog_checksum", err: errors.New(`ent: missing required field "SystemModelPriceVersion.catalog_checksum"`)}
	}
	if v, ok := _c.mutation.CatalogChecksum(); ok {
		if err := systemmodelpriceversion.CatalogChecksumValidator(v); err != nil {
			return &ValidationError{Name: "catalog_checksum", err: fmt.Errorf(`ent: validator failed for field "SystemModelPriceVersion.catalog_checksum": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "SystemModelPriceVersion.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := systemmodelpriceversion.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "SystemModelPriceVersion.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "SystemModelPriceVersion.model_name"`)}
	}
	if v, ok := _c.mutation.ModelName(); ok {
		if err := systemmodelpriceversion.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "SystemModelPriceVersion.model_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BillingMode(); !ok {
		return &ValidationError{Name: "billing_mode", err: errors.New(`ent: missing required field "SystemModelPriceVersion.billing_mode"`)}
	}
	if v, ok := _c.mutation.BillingMode(); ok {
		if err := systemmodelpriceversion.BillingModeValidator(v); err != nil {
			return &ValidationError{Name: "billing_mode", err: fmt.Errorf(`ent: validator failed for field "SystemModelPriceVersion.billing_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceDetail(); !ok {
		return &ValidationError{Name: "price_detail", err: errors.New(`ent: missing required field "SystemModelPriceVersion.price_detail"`)}
	}
	if _, ok := _c.mutation.EffectiveFrom(); !ok {
		return &ValidationError{Name: "effective_from", err: errors.New(`ent: missing required field "SystemModelPriceVersion.effective_from"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SystemModelPriceVersion.created_at"`)}
	}
	return nil
}

func (_c *SystemModelPriceVersionCreate) sqlSave(ctx context.Context) (*SystemModelPriceVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SystemModelPriceVersionCreate) createSpec() (*SystemModelPriceVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemModelPriceVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(systemmodelpriceversion.Table, sqlgraph.NewFieldSpec(systemmodelpriceversion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CatalogChecksum(); ok {
		_spec.SetField(systemmodelpriceversion.FieldCatalogChecksum, field.TypeString, value)
		_node.CatalogChecksum = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(systemmodelpriceversion.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(systemmodelpriceversion.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.BillingMode(); ok {
		_spec.SetField(systemmodelpriceversion.FieldBillingMode, field.TypeString, value)
		_node.BillingMode = value
	}
	if value, ok := _c.mutation.PriceDetail(); ok {
		_spec.SetField(systemmodelpriceversion.FieldPriceDetail, field.TypeJSON, value)
		_node.PriceDetail = value
	}
	if value, ok := _c.mutation.EffectiveFrom(); ok {
		_spec.SetField(systemmodelpriceversion.FieldEffectiveFrom, field.TypeTime, value)
		_node.EffectiveFrom = value
	}
	if value, ok := _c.mutation.EffectiveTo(); ok {
		_spec.SetField(systemmodelpriceversion.FieldEffectiveTo, field.TypeTime, value)
		_node.EffectiveTo = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(systemmodelpriceversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SystemModelPriceVersion.Create().
//		SetCatalogChecksum(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemModelPriceVersionUpsert) {
//			SetCatalogChecksum(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemModelPriceVersionCreate) OnConflict(opts ...sql.ConflictOption) *SystemModelPriceVersionUpsertOne {
	_c.conflict = opts
	return &SystemModelPriceVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SystemModelPriceVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemModelPriceVersionCreate) OnConflictColumns(columns ...string) *SystemModelPriceVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemModelPriceVersionUpsertOne{
		create: _c,
	}
}

type (
	// SystemModelPriceVersionUpsertOne is the builder for "upsert"-ing
	//  one SystemModelPriceVersion node.
	SystemModelPriceVersionUpsertOne struct {
		create *SystemModelPriceVersionCreate
	}

	// SystemModelPriceVersionUpsert is the "OnConflict" setter.
	SystemModelPriceVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetCatalogChecksum sets the "catalog_checksum" field.
func (u *SystemModelPriceVersionUpsert) SetCatalogChecksum(v string) *SystemModelPriceVersionUpsert {
	u.Set(systemmodelpriceversion.FieldCatalogChecksum, v)
	return u
}

// UpdateCatalogChecksum sets the "catalog_checksum" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsert) UpdateCatalogChecksum() *SystemModelPriceVersionUpsert {
	u.SetExcluded(systemmodelpriceversion.FieldCatalogChecksum)
	return u
}

// SetProvider sets the "provider" field.
func (u *SystemModelPriceVersionUpsert) SetProvider(v string) *SystemModelPriceVersionUpsert {
	u.Set(systemmodelpriceversion.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsert) UpdateProvider() *SystemModelPriceVersionUpsert {
	u.SetExcluded(systemmodelpriceversion.FieldProvider)
	return u
}

// SetModelName sets the "model_name" field.
func (u *SystemModelPriceVersionUpsert) SetModelName(v string) *SystemModelPriceVersionUpsert {
	u.Set(systemmodelpriceversion.FieldModelName, v)
	return u
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsert) UpdateModelName() *SystemModelPriceVersionUpsert {
	u.SetExcluded(systemmodelpriceversion.FieldModelName)
	return u
}

// SetBillingMode sets the "billing_mode" field.
func (u *SystemModelPriceVersionUpsert) SetBillingMode(v string) *SystemModelPriceVersionUpsert {
	u.Set(systemmodelpriceversion.FieldBillingMode, v)
	return u
}

// UpdateBillingMode sets the "billing_mode" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsert) UpdateBillingMode() *SystemModelPriceVersionUpsert {
	u.SetExcluded(systemmodelpriceversion.FieldBillingMode)
	return u
}

// SetPriceDetail sets the "price_detail" field.
func (u *SystemModelPriceVersionUpsert) SetPriceDetail(v map[string]interface{}) *SystemModelPriceVersionUpsert {
	u.Set(systemmodelpriceversion.FieldPriceDetail, v)
	return u
}

// UpdatePriceDetail sets the "price_detail" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsert) UpdatePriceDetail() *SystemModelPriceVersionUpsert {
	u.SetExcluded(systemmodelpriceversion.FieldPriceDetail)
	return u
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *SystemModelPriceVersionUpsert) SetEffectiveFrom(v time.Time) *SystemModelPriceVersionUpsert {
	u.Set(systemmodelpriceversion.FieldEffectiveFrom, v)
	return u
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsert) UpdateEffectiveFrom() *SystemModelPriceVersionUpsert {
	u.SetExcluded(systemmodelpriceversion.FieldEffectiveFrom)
	return u
}

// SetEffectiveTo sets the "effective_to" field.
func (u *SystemModelPriceVersionUpsert) SetEffectiveTo(v time.Time) *SystemModelPriceVersionUpsert {
	u.Set(systemmodelpriceversion.FieldEffectiveTo, v)
	return u
}

// UpdateEffectiveTo sets the "effective_to" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsert) UpdateEffectiveTo() *SystemModelPriceVersionUpsert {
	u.SetExcluded(systemmodelpriceversion.FieldEffectiveTo)
	return u
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (u *SystemModelPriceVersionUpsert) ClearEffectiveTo() *SystemModelPriceVersionUpsert {
	u.SetNull(systemmodelpriceversion.FieldEffectiveTo)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SystemModelPriceVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SystemModelPriceVersionUpsertOne) UpdateNewValues() *SystemModelPriceVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(systemmodelpriceversion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SystemModelPriceVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SystemModelPriceVersionUpsertOne) Ignore() *SystemModelPriceVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemModelPriceVersionUpsertOne) DoNothing() *SystemModelPriceVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemModelPriceVersionCreate.OnConflict
// documentation for more info.
func (u *SystemModelPriceVersionUpsertOne) Update(set func(*SystemModelPriceVersionUpsert)) *SystemModelPriceVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemModelPriceVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCatalogChecksum sets the "catalog_checksum" field.
func (u *SystemModelPriceVersionUpsertOne) SetCatalogChecksum(v string) *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetCatalogChecksum(v)
	})
}

// UpdateCatalogChecksum sets the "catalog_checksum" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertOne) UpdateCatalogChecksum() *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateCatalogChecksum()
	})
}

// SetProvider sets the "provider" field.
func (u *SystemModelPriceVersionUpsertOne) SetProvider(v string) *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertOne) UpdateProvider() *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateProvider()
	})
}

// SetModelName sets the "model_name" field.
func (u *SystemModelPriceVersionUpsertOne) SetModelName(v string) *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertOne) UpdateModelName() *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateModelName()
	})
}

// SetBillingMode sets the "billing_mode" field.
func (u *SystemModelPriceVersionUpsertOne) SetBillingMode(v string) *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetBillingMode(v)
	})
}

// UpdateBillingMode sets the "billing_mode" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertOne) UpdateBillingMode() *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateBillingMode()
	})
}

// SetPriceDetail sets the "price_detail" field.
func (u *SystemModelPriceVersionUpsertOne) SetPriceDetail(v map[string]interface{}) *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetPriceDetail(v)
	})
}

// UpdatePriceDetail sets the "price_detail" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertOne) UpdatePriceDetail() *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdatePriceDetail()
	})
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *SystemModelPriceVersionUpsertOne) SetEffectiveFrom(v time.Time) *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetEffectiveFrom(v)
	})
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertOne) UpdateEffectiveFrom() *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateEffectiveFrom()
	})
}

// SetEffectiveTo sets the "effective_to" field.
func (u *SystemModelPriceVersionUpsertOne) SetEffectiveTo(v time.Time) *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetEffectiveTo(v)
	})
}

// UpdateEffectiveTo sets the "effective_to" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertOne) UpdateEffectiveTo() *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateEffectiveTo()
	})
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (u *SystemModelPriceVersionUpsertOne) ClearEffectiveTo() *SystemModelPriceVersionUpsertOne {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.ClearEffectiveTo()
	})
}

// Exec executes the query.
func (u *SystemModelPriceVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemModelPriceVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemModelPriceVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SystemModelPriceVersionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SystemModelPriceVersionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SystemModelPriceVersionCreateBulk is the builder for creating many SystemModelPriceVersion entities in bulk.
type SystemModelPriceVersionCreateBulk struct {
	config
	err      error
	builders []*SystemModelPriceVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the SystemModelPriceVersion entities in the database.
func (_c *SystemModelPriceVersionCreateBulk) Save(ctx context.Context) ([]*SystemModelPriceVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SystemModelPriceVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemModelPriceVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SystemModelPriceVersionCreateBulk) SaveX(ctx context.Context) []*SystemModelPriceVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemModelPriceVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemModelPriceVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SystemModelPriceVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemModelPriceVersionUpsert) {
//			SetCatalogChecksum(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemModelPriceVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SystemModelPriceVersionUpsertBulk {
	_c.conflict = opts
	return &SystemModelPriceVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SystemModelPriceVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemModelPriceVersionCreateBulk) OnConflictColumns(columns ...string) *SystemModelPriceVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemModelPriceVersionUpsertBulk{
		create: _c,
	}
}

// SystemModelPriceVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of SystemModelPriceVersion nodes.
type SystemModelPriceVersionUpsertBulk struct {
	create *SystemModelPriceVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SystemModelPriceVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SystemModelPriceVersionUpsertBulk) UpdateNewValues() *SystemModelPriceVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(systemmodelpriceversion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SystemModelPriceVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SystemModelPriceVersionUpsertBulk) Ignore() *SystemModelPriceVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemModelPriceVersionUpsertBulk) DoNothing() *SystemModelPriceVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemModelPriceVersionCreateBulk.OnConflict
// documentation for more info.
func (u *SystemModelPriceVersionUpsertBulk) Update(set func(*SystemModelPriceVersionUpsert)) *SystemModelPriceVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemModelPriceVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCatalogChecksum sets the "catalog_checksum" field.
func (u *SystemModelPriceVersionUpsertBulk) SetCatalogChecksum(v string) *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetCatalogChecksum(v)
	})
}

// UpdateCatalogChecksum sets the "catalog_checksum" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertBulk) UpdateCatalogChecksum() *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateCatalogChecksum()
	})
}

// SetProvider sets the "provider" field.
func (u *SystemModelPriceVersionUpsertBulk) SetProvider(v string) *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertBulk) UpdateProvider() *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateProvider()
	})
}

// SetModelName sets the "model_name" field.
func (u *SystemModelPriceVersionUpsertBulk) SetModelName(v string) *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertBulk) UpdateModelName() *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateModelName()
	})
}

// SetBillingMode sets the "billing_mode" field.
func (u *SystemModelPriceVersionUpsertBulk) SetBillingMode(v string) *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetBillingMode(v)
	})
}

// UpdateBillingMode sets the "billing_mode" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertBulk) UpdateBillingMode() *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateBillingMode()
	})
}

// SetPriceDetail sets the "price_detail" field.
func (u *SystemModelPriceVersionUpsertBulk) SetPriceDetail(v map[string]interface{}) *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetPriceDetail(v)
	})
}

// UpdatePriceDetail sets the "price_detail" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertBulk) UpdatePriceDetail() *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdatePriceDetail()
	})
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *SystemModelPriceVersionUpsertBulk) SetEffectiveFrom(v time.Time) *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetEffectiveFrom(v)
	})
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertBulk) UpdateEffectiveFrom() *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateEffectiveFrom()
	})
}

// SetEffectiveTo sets the "effective_to" field.
func (u *SystemModelPriceVersionUpsertBulk) SetEffectiveTo(v time.Time) *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.SetEffectiveTo(v)
	})
}

// UpdateEffectiveTo sets the "effective_to" field to the value that was provided on create.
func (u *SystemModelPriceVersionUpsertBulk) UpdateEffectiveTo() *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.UpdateEffectiveTo()
	})
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (u *SystemModelPriceVersionUpsertBulk) ClearEffectiveTo() *SystemModelPriceVersionUpsertBulk {
	return u.Update(func(s *SystemModelPriceVersionUpsert) {
		s.ClearEffectiveTo()
	})
}

// Exec executes the query.
func (u *SystemModelPriceVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SystemModelPriceVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemModelPriceVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemModelPriceVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
