// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usagefinancecostsegment"
	"github.com/shopspring/decimal"
)

// UsageFinanceCostSegmentCreate is the builder for creating a UsageFinanceCostSegment entity.
type UsageFinanceCostSegmentCreate struct {
	config
	mutation *UsageFinanceCostSegmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsageFinanceRecordID sets the "usage_finance_record_id" field.
func (_c *UsageFinanceCostSegmentCreate) SetUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetUsageFinanceRecordID(v)
	return _c
}

// SetAttemptNo sets the "attempt_no" field.
func (_c *UsageFinanceCostSegmentCreate) SetAttemptNo(v int) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetAttemptNo(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UsageFinanceCostSegmentCreate) SetAccountID(v int64) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetWalletID sets the "wallet_id" field.
func (_c *UsageFinanceCostSegmentCreate) SetWalletID(v int64) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetWalletID(v)
	return _c
}

// SetNillableWalletID sets the "wallet_id" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableWalletID(v *int64) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetWalletID(*v)
	}
	return _c
}

// SetUpstreamID sets the "upstream_id" field.
func (_c *UsageFinanceCostSegmentCreate) SetUpstreamID(v int64) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetUpstreamID(v)
	return _c
}

// SetNillableUpstreamID sets the "upstream_id" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableUpstreamID(v *int64) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetUpstreamID(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *UsageFinanceCostSegmentCreate) SetChannelID(v int64) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableChannelID(v *int64) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetChannelID(*v)
	}
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *UsageFinanceCostSegmentCreate) SetUpstreamModel(v string) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetServiceTier sets the "service_tier" field.
func (_c *UsageFinanceCostSegmentCreate) SetServiceTier(v string) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetServiceTier(v)
	return _c
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableServiceTier(v *string) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetServiceTier(*v)
	}
	return _c
}

// SetUsageDetail sets the "usage_detail" field.
func (_c *UsageFinanceCostSegmentCreate) SetUsageDetail(v map[string]interface{}) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetUsageDetail(v)
	return _c
}

// SetUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field.
func (_c *UsageFinanceCostSegmentCreate) SetUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetUpstreamCostMultiplierSnapshot(v)
	return _c
}

// SetNillableUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableUpstreamCostMultiplierSnapshot(v *decimal.Decimal) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetUpstreamCostMultiplierSnapshot(*v)
	}
	return _c
}

// SetUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field.
func (_c *UsageFinanceCostSegmentCreate) SetUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetUpstreamMultiplierChangeID(v)
	return _c
}

// SetNillableUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableUpstreamMultiplierChangeID(v *int64) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetUpstreamMultiplierChangeID(*v)
	}
	return _c
}

// SetUpstreamMultiplierSource sets the "upstream_multiplier_source" field.
func (_c *UsageFinanceCostSegmentCreate) SetUpstreamMultiplierSource(v string) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetUpstreamMultiplierSource(v)
	return _c
}

// SetNillableUpstreamMultiplierSource sets the "upstream_multiplier_source" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableUpstreamMultiplierSource(v *string) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetUpstreamMultiplierSource(*v)
	}
	return _c
}

// SetUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field.
func (_c *UsageFinanceCostSegmentCreate) SetUpstreamMultiplierEffectiveAt(v time.Time) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetUpstreamMultiplierEffectiveAt(v)
	return _c
}

// SetNillableUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableUpstreamMultiplierEffectiveAt(v *time.Time) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetUpstreamMultiplierEffectiveAt(*v)
	}
	return _c
}

// SetAccountFinanceProfileID sets the "account_finance_profile_id" field.
func (_c *UsageFinanceCostSegmentCreate) SetAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetAccountFinanceProfileID(v)
	return _c
}

// SetNillableAccountFinanceProfileID sets the "account_finance_profile_id" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableAccountFinanceProfileID(v *int64) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetAccountFinanceProfileID(*v)
	}
	return _c
}

// SetFxRateVersionID sets the "fx_rate_version_id" field.
func (_c *UsageFinanceCostSegmentCreate) SetFxRateVersionID(v int64) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetFxRateVersionID(v)
	return _c
}

// SetNillableFxRateVersionID sets the "fx_rate_version_id" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableFxRateVersionID(v *int64) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetFxRateVersionID(*v)
	}
	return _c
}

// SetSourceCurrency sets the "source_currency" field.
func (_c *UsageFinanceCostSegmentCreate) SetSourceCurrency(v string) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetSourceCurrency(v)
	return _c
}

// SetNillableSourceCurrency sets the "source_currency" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableSourceCurrency(v *string) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetSourceCurrency(*v)
	}
	return _c
}

// SetFxRateToUsd sets the "fx_rate_to_usd" field.
func (_c *UsageFinanceCostSegmentCreate) SetFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetFxRateToUsd(v)
	return _c
}

// SetNillableFxRateToUsd sets the "fx_rate_to_usd" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableFxRateToUsd(v *decimal.Decimal) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetFxRateToUsd(*v)
	}
	return _c
}

// SetFxSource sets the "fx_source" field.
func (_c *UsageFinanceCostSegmentCreate) SetFxSource(v string) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetFxSource(v)
	return _c
}

// SetNillableFxSource sets the "fx_source" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableFxSource(v *string) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetFxSource(*v)
	}
	return _c
}

// SetFxObservedAt sets the "fx_observed_at" field.
func (_c *UsageFinanceCostSegmentCreate) SetFxObservedAt(v time.Time) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetFxObservedAt(v)
	return _c
}

// SetNillableFxObservedAt sets the "fx_observed_at" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableFxObservedAt(v *time.Time) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetFxObservedAt(*v)
	}
	return _c
}

// SetPriceVersionID sets the "price_version_id" field.
func (_c *UsageFinanceCostSegmentCreate) SetPriceVersionID(v int64) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetPriceVersionID(v)
	return _c
}

// SetNillablePriceVersionID sets the "price_version_id" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillablePriceVersionID(v *int64) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetPriceVersionID(*v)
	}
	return _c
}

// SetPricingSource sets the "pricing_source" field.
func (_c *UsageFinanceCostSegmentCreate) SetPricingSource(v string) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetPricingSource(v)
	return _c
}

// SetNillablePricingSource sets the "pricing_source" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillablePricingSource(v *string) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetPricingSource(*v)
	}
	return _c
}

// SetCostStatus sets the "cost_status" field.
func (_c *UsageFinanceCostSegmentCreate) SetCostStatus(v string) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetCostStatus(v)
	return _c
}

// SetCostAmount sets the "cost_amount" field.
func (_c *UsageFinanceCostSegmentCreate) SetCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetCostAmount(v)
	return _c
}

// SetNillableCostAmount sets the "cost_amount" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableCostAmount(v *decimal.Decimal) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetCostAmount(*v)
	}
	return _c
}

// SetCalculationDetail sets the "calculation_detail" field.
func (_c *UsageFinanceCostSegmentCreate) SetCalculationDetail(v map[string]interface{}) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetCalculationDetail(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageFinanceCostSegmentCreate) SetCreatedAt(v time.Time) *UsageFinanceCostSegmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageFinanceCostSegmentCreate) SetNillableCreatedAt(v *time.Time) *UsageFinanceCostSegmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the UsageFinanceCostSegmentMutation object of the builder.
func (_c *UsageFinanceCostSegmentCreate) Mutation() *UsageFinanceCostSegmentMutation {
	return _c.mutation
}

// Save creates the UsageFinanceCostSegment in the database.
func (_c *UsageFinanceCostSegmentCreate) Save(ctx context.Context) (*UsageFinanceCostSegment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageFinanceCostSegmentCreate) SaveX(ctx context.Context) *UsageFinanceCostSegment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageFinanceCostSegmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageFinanceCostSegmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageFinanceCostSegmentCreate) defaults() {
	if _, ok := _c.mutation.CalculationDetail(); !ok {
		v := usagefinancecostsegment.DefaultCalculationDetail()
		_c.mutation.SetCalculationDetail(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagefinancecostsegment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageFinanceCostSegmentCreate) check() error {
	if _, ok := _c.mutation.UsageFinanceRecordID(); !ok {
		return &ValidationError{Name: "usage_finance_record_id", err: errors.New(`ent: missing required field "UsageFinanceCostSegment.usage_finance_record_id"`)}
	}
	if _, ok := _c.mutation.AttemptNo(); !ok {
		return &ValidationError{Name: "attempt_no", err: errors.New(`ent: missing required field "UsageFinanceCostSegment.attempt_no"`)}
	}
	if v, ok := _c.mutation.AttemptNo(); ok {
		if err := usagefinancecostsegment.AttemptNoValidator(v); err != nil {
			return &ValidationError{Name: "attempt_no", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.attempt_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "UsageFinanceCostSegment.account_id"`)}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "UsageFinanceCostSegment.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := usagefinancecostsegment.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.upstream_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ServiceTier(); ok {
		if err := usagefinancecostsegment.ServiceTierValidator(v); err != nil {
			return &ValidationError{Name: "service_tier", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.service_tier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsageDetail(); !ok {
		return &ValidationError{Name: "usage_detail", err: errors.New(`ent: missing required field "UsageFinanceCostSegment.usage_detail"`)}
	}
	if v, ok := _c.mutation.UpstreamMultiplierSource(); ok {
		if err := usagefinancecostsegment.UpstreamMultiplierSourceValidator(v); err != nil {
			return &ValidationError{Name: "upstream_multiplier_source", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.upstream_multiplier_source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceCurrency(); ok {
		if err := usagefinancecostsegment.SourceCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "source_currency", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.source_currency": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FxSource(); ok {
		if err := usagefinancecostsegment.FxSourceValidator(v); err != nil {
			return &ValidationError{Name: "fx_source", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.fx_source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PricingSource(); ok {
		if err := usagefinancecostsegment.PricingSourceValidator(v); err != nil {
			return &ValidationError{Name: "pricing_source", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.pricing_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CostStatus(); !ok {
		return &ValidationError{Name: "cost_status", err: errors.New(`ent: missing required field "UsageFinanceCostSegment.cost_status"`)}
	}
	if v, ok := _c.mutation.CostStatus(); ok {
		if err := usagefinancecostsegment.CostStatusValidator(v); err != nil {
			return &ValidationError{Name: "cost_status", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.cost_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CalculationDetail(); !ok {
		return &ValidationError{Name: "calculation_detail", err: errors.New(`ent: missing required field "UsageFinanceCostSegment.calculation_detail"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageFinanceCostSegment.created_at"`)}
	}
	return nil
}

func (_c *UsageFinanceCostSegmentCreate) sqlSave(ctx context.Context) (*UsageFinanceCostSegment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageFinanceCostSegmentCreate) createSpec() (*UsageFinanceCostSegment, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageFinanceCostSegment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagefinancecostsegment.Table, sqlgraph.NewFieldSpec(usagefinancecostsegment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UsageFinanceRecordID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUsageFinanceRecordID, field.TypeInt64, value)
		_node.UsageFinanceRecordID = value
	}
	if value, ok := _c.mutation.AttemptNo(); ok {
		_spec.SetField(usagefinancecostsegment.FieldAttemptNo, field.TypeInt, value)
		_node.AttemptNo = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.WalletID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldWalletID, field.TypeInt64, value)
		_node.WalletID = &value
	}
	if value, ok := _c.mutation.UpstreamID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamID, field.TypeInt64, value)
		_node.UpstreamID = &value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldChannelID, field.TypeInt64, value)
		_node.ChannelID = &value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.ServiceTier(); ok {
		_spec.SetField(usagefinancecostsegment.FieldServiceTier, field.TypeString, value)
		_node.ServiceTier = &value
	}
	if value, ok := _c.mutation.UsageDetail(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUsageDetail, field.TypeJSON, value)
		_node.UsageDetail = value
	}
	if value, ok := _c.mutation.UpstreamCostMultiplierSnapshot(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot, field.TypeFloat64, value)
		_node.UpstreamCostMultiplierSnapshot = &value
	}
	if value, ok := _c.mutation.UpstreamMultiplierChangeID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamMultiplierChangeID, field.TypeInt64, value)
		_node.UpstreamMultiplierChangeID = &value
	}
	if value, ok := _c.mutation.UpstreamMultiplierSource(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamMultiplierSource, field.TypeString, value)
		_node.UpstreamMultiplierSource = &value
	}
	if value, ok := _c.mutation.UpstreamMultiplierEffectiveAt(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamMultiplierEffectiveAt, field.TypeTime, value)
		_node.UpstreamMultiplierEffectiveAt = &value
	}
	if value, ok := _c.mutation.AccountFinanceProfileID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldAccountFinanceProfileID, field.TypeInt64, value)
		_node.AccountFinanceProfileID = &value
	}
	if value, ok := _c.mutation.FxRateVersionID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxRateVersionID, field.TypeInt64, value)
		_node.FxRateVersionID = &value
	}
	if value, ok := _c.mutation.SourceCurrency(); ok {
		_spec.SetField(usagefinancecostsegment.FieldSourceCurrency, field.TypeString, value)
		_node.SourceCurrency = &value
	}
	if value, ok := _c.mutation.FxRateToUsd(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxRateToUsd, field.TypeFloat64, value)
		_node.FxRateToUsd = &value
	}
	if value, ok := _c.mutation.FxSource(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxSource, field.TypeString, value)
		_node.FxSource = &value
	}
	if value, ok := _c.mutation.FxObservedAt(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxObservedAt, field.TypeTime, value)
		_node.FxObservedAt = &value
	}
	if value, ok := _c.mutation.PriceVersionID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldPriceVersionID, field.TypeInt64, value)
		_node.PriceVersionID = &value
	}
	if value, ok := _c.mutation.PricingSource(); ok {
		_spec.SetField(usagefinancecostsegment.FieldPricingSource, field.TypeString, value)
		_node.PricingSource = &value
	}
	if value, ok := _c.mutation.CostStatus(); ok {
		_spec.SetField(usagefinancecostsegment.FieldCostStatus, field.TypeString, value)
		_node.CostStatus = value
	}
	if value, ok := _c.mutation.CostAmount(); ok {
		_spec.SetField(usagefinancecostsegment.FieldCostAmount, field.TypeFloat64, value)
		_node.CostAmount = &value
	}
	if value, ok := _c.mutation.CalculationDetail(); ok {
		_spec.SetField(usagefinancecostsegment.FieldCalculationDetail, field.TypeJSON, value)
		_node.CalculationDetail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagefinancecostsegment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageFinanceCostSegment.Create().
//		SetUsageFinanceRecordID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageFinanceCostSegmentUpsert) {
//			SetUsageFinanceRecordID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageFinanceCostSegmentCreate) OnConflict(opts ...sql.ConflictOption) *UsageFinanceCostSegmentUpsertOne {
	_c.conflict = opts
	return &UsageFinanceCostSegmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageFinanceCostSegment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageFinanceCostSegmentCreate) OnConflictColumns(columns ...string) *UsageFinanceCostSegmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageFinanceCostSegmentUpsertOne{
		create: _c,
	}
}

type (
	// UsageFinanceCostSegmentUpsertOne is the builder for "upsert"-ing
	//  one UsageFinanceCostSegment node.
	UsageFinanceCostSegmentUpsertOne struct {
		create *UsageFinanceCostSegmentCreate
	}

	// UsageFinanceCostSegmentUpsert is the "OnConflict" setter.
	UsageFinanceCostSegmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsageFinanceRecordID sets the "usage_finance_record_id" field.
func (u *UsageFinanceCostSegmentUpsert) SetUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldUsageFinanceRecordID, v)
	return u
}

// UpdateUsageFinanceRecordID sets the "usage_finance_record_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateUsageFinanceRecordID() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldUsageFinanceRecordID)
	return u
}

// AddUsageFinanceRecordID adds v to the "usage_finance_record_id" field.
func (u *UsageFinanceCostSegmentUpsert) AddUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldUsageFinanceRecordID, v)
	return u
}

// SetAttemptNo sets the "attempt_no" field.
func (u *UsageFinanceCostSegmentUpsert) SetAttemptNo(v int) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldAttemptNo, v)
	return u
}

// UpdateAttemptNo sets the "attempt_no" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateAttemptNo() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldAttemptNo)
	return u
}

// AddAttemptNo adds v to the "attempt_no" field.
func (u *UsageFinanceCostSegmentUpsert) AddAttemptNo(v int) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldAttemptNo, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *UsageFinanceCostSegmentUpsert) SetAccountID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateAccountID() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageFinanceCostSegmentUpsert) AddAccountID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldAccountID, v)
	return u
}

// SetWalletID sets the "wallet_id" field.
func (u *UsageFinanceCostSegmentUpsert) SetWalletID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldWalletID, v)
	return u
}

// UpdateWalletID sets the "wallet_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateWalletID() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldWalletID)
	return u
}

// AddWalletID adds v to the "wallet_id" field.
func (u *UsageFinanceCostSegmentUpsert) AddWalletID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldWalletID, v)
	return u
}

// ClearWalletID clears the value of the "wallet_id" field.
func (u *UsageFinanceCostSegmentUpsert) ClearWalletID() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldWalletID)
	return u
}

// SetUpstreamID sets the "upstream_id" field.
func (u *UsageFinanceCostSegmentUpsert) SetUpstreamID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldUpstreamID, v)
	return u
}

// UpdateUpstreamID sets the "upstream_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateUpstreamID() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldUpstreamID)
	return u
}

// AddUpstreamID adds v to the "upstream_id" field.
func (u *UsageFinanceCostSegmentUpsert) AddUpstreamID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldUpstreamID, v)
	return u
}

// ClearUpstreamID clears the value of the "upstream_id" field.
func (u *UsageFinanceCostSegmentUpsert) ClearUpstreamID() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldUpstreamID)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *UsageFinanceCostSegmentUpsert) SetChannelID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateChannelID() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldChannelID)
	return u
}

// AddChannelID adds v to the "channel_id" field.
func (u *UsageFinanceCostSegmentUpsert) AddChannelID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldChannelID, v)
	return u
}

// ClearChannelID clears the value of the "channel_id" field.
func (u *UsageFinanceCostSegmentUpsert) ClearChannelID() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldChannelID)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *UsageFinanceCostSegmentUpsert) SetUpstreamModel(v string) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateUpstreamModel() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldUpstreamModel)
	return u
}

// SetServiceTier sets the "service_tier" field.
func (u *UsageFinanceCostSegmentUpsert) SetServiceTier(v string) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldServiceTier, v)
	return u
}

// UpdateServiceTier sets the "service_tier" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateServiceTier() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldServiceTier)
	return u
}

// ClearServiceTier clears the value of the "service_tier" field.
func (u *UsageFinanceCostSegmentUpsert) ClearServiceTier() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldServiceTier)
	return u
}

// SetUsageDetail sets the "usage_detail" field.
func (u *UsageFinanceCostSegmentUpsert) SetUsageDetail(v map[string]interface{}) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldUsageDetail, v)
	return u
}

// UpdateUsageDetail sets the "usage_detail" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateUsageDetail() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldUsageDetail)
	return u
}

// SetUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field.
func (u *UsageFinanceCostSegmentUpsert) SetUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot, v)
	return u
}

// UpdateUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateUpstreamCostMultiplierSnapshot() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot)
	return u
}

// AddUpstreamCostMultiplierSnapshot adds v to the "upstream_cost_multiplier_snapshot" field.
func (u *UsageFinanceCostSegmentUpsert) AddUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot, v)
	return u
}

// ClearUpstreamCostMultiplierSnapshot clears the value of the "upstream_cost_multiplier_snapshot" field.
func (u *UsageFinanceCostSegmentUpsert) ClearUpstreamCostMultiplierSnapshot() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot)
	return u
}

// SetUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field.
func (u *UsageFinanceCostSegmentUpsert) SetUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldUpstreamMultiplierChangeID, v)
	return u
}

// UpdateUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateUpstreamMultiplierChangeID() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldUpstreamMultiplierChangeID)
	return u
}

// AddUpstreamMultiplierChangeID adds v to the "upstream_multiplier_change_id" field.
func (u *UsageFinanceCostSegmentUpsert) AddUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldUpstreamMultiplierChangeID, v)
	return u
}

// ClearUpstreamMultiplierChangeID clears the value of the "upstream_multiplier_change_id" field.
func (u *UsageFinanceCostSegmentUpsert) ClearUpstreamMultiplierChangeID() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldUpstreamMultiplierChangeID)
	return u
}

// SetUpstreamMultiplierSource sets the "upstream_multiplier_source" field.
func (u *UsageFinanceCostSegmentUpsert) SetUpstreamMultiplierSource(v string) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldUpstreamMultiplierSource, v)
	return u
}

// UpdateUpstreamMultiplierSource sets the "upstream_multiplier_source" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateUpstreamMultiplierSource() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldUpstreamMultiplierSource)
	return u
}

// ClearUpstreamMultiplierSource clears the value of the "upstream_multiplier_source" field.
func (u *UsageFinanceCostSegmentUpsert) ClearUpstreamMultiplierSource() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldUpstreamMultiplierSource)
	return u
}

// SetUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field.
func (u *UsageFinanceCostSegmentUpsert) SetUpstreamMultiplierEffectiveAt(v time.Time) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldUpstreamMultiplierEffectiveAt, v)
	return u
}

// UpdateUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateUpstreamMultiplierEffectiveAt() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldUpstreamMultiplierEffectiveAt)
	return u
}

// ClearUpstreamMultiplierEffectiveAt clears the value of the "upstream_multiplier_effective_at" field.
func (u *UsageFinanceCostSegmentUpsert) ClearUpstreamMultiplierEffectiveAt() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldUpstreamMultiplierEffectiveAt)
	return u
}

// SetAccountFinanceProfileID sets the "account_finance_profile_id" field.
func (u *UsageFinanceCostSegmentUpsert) SetAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldAccountFinanceProfileID, v)
	return u
}

// UpdateAccountFinanceProfileID sets the "account_finance_profile_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateAccountFinanceProfileID() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldAccountFinanceProfileID)
	return u
}

// AddAccountFinanceProfileID adds v to the "account_finance_profile_id" field.
func (u *UsageFinanceCostSegmentUpsert) AddAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldAccountFinanceProfileID, v)
	return u
}

// ClearAccountFinanceProfileID clears the value of the "account_finance_profile_id" field.
func (u *UsageFinanceCostSegmentUpsert) ClearAccountFinanceProfileID() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldAccountFinanceProfileID)
	return u
}

// SetFxRateVersionID sets the "fx_rate_version_id" field.
func (u *UsageFinanceCostSegmentUpsert) SetFxRateVersionID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldFxRateVersionID, v)
	return u
}

// UpdateFxRateVersionID sets the "fx_rate_version_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateFxRateVersionID() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldFxRateVersionID)
	return u
}

// AddFxRateVersionID adds v to the "fx_rate_version_id" field.
func (u *UsageFinanceCostSegmentUpsert) AddFxRateVersionID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldFxRateVersionID, v)
	return u
}

// ClearFxRateVersionID clears the value of the "fx_rate_version_id" field.
func (u *UsageFinanceCostSegmentUpsert) ClearFxRateVersionID() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldFxRateVersionID)
	return u
}

// SetSourceCurrency sets the "source_currency" field.
func (u *UsageFinanceCostSegmentUpsert) SetSourceCurrency(v string) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldSourceCurrency, v)
	return u
}

// UpdateSourceCurrency sets the "source_currency" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateSourceCurrency() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldSourceCurrency)
	return u
}

// ClearSourceCurrency clears the value of the "source_currency" field.
func (u *UsageFinanceCostSegmentUpsert) ClearSourceCurrency() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldSourceCurrency)
	return u
}

// SetFxRateToUsd sets the "fx_rate_to_usd" field.
func (u *UsageFinanceCostSegmentUpsert) SetFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldFxRateToUsd, v)
	return u
}

// UpdateFxRateToUsd sets the "fx_rate_to_usd" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateFxRateToUsd() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldFxRateToUsd)
	return u
}

// AddFxRateToUsd adds v to the "fx_rate_to_usd" field.
func (u *UsageFinanceCostSegmentUpsert) AddFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldFxRateToUsd, v)
	return u
}

// ClearFxRateToUsd clears the value of the "fx_rate_to_usd" field.
func (u *UsageFinanceCostSegmentUpsert) ClearFxRateToUsd() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldFxRateToUsd)
	return u
}

// SetFxSource sets the "fx_source" field.
func (u *UsageFinanceCostSegmentUpsert) SetFxSource(v string) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldFxSource, v)
	return u
}

// UpdateFxSource sets the "fx_source" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateFxSource() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldFxSource)
	return u
}

// ClearFxSource clears the value of the "fx_source" field.
func (u *UsageFinanceCostSegmentUpsert) ClearFxSource() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldFxSource)
	return u
}

// SetFxObservedAt sets the "fx_observed_at" field.
func (u *UsageFinanceCostSegmentUpsert) SetFxObservedAt(v time.Time) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldFxObservedAt, v)
	return u
}

// UpdateFxObservedAt sets the "fx_observed_at" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateFxObservedAt() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldFxObservedAt)
	return u
}

// ClearFxObservedAt clears the value of the "fx_observed_at" field.
func (u *UsageFinanceCostSegmentUpsert) ClearFxObservedAt() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldFxObservedAt)
	return u
}

// SetPriceVersionID sets the "price_version_id" field.
func (u *UsageFinanceCostSegmentUpsert) SetPriceVersionID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldPriceVersionID, v)
	return u
}

// UpdatePriceVersionID sets the "price_version_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdatePriceVersionID() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldPriceVersionID)
	return u
}

// AddPriceVersionID adds v to the "price_version_id" field.
func (u *UsageFinanceCostSegmentUpsert) AddPriceVersionID(v int64) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldPriceVersionID, v)
	return u
}

// ClearPriceVersionID clears the value of the "price_version_id" field.
func (u *UsageFinanceCostSegmentUpsert) ClearPriceVersionID() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldPriceVersionID)
	return u
}

// SetPricingSource sets the "pricing_source" field.
func (u *UsageFinanceCostSegmentUpsert) SetPricingSource(v string) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldPricingSource, v)
	return u
}

// UpdatePricingSource sets the "pricing_source" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdatePricingSource() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldPricingSource)
	return u
}

// ClearPricingSource clears the value of the "pricing_source" field.
func (u *UsageFinanceCostSegmentUpsert) ClearPricingSource() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldPricingSource)
	return u
}

// SetCostStatus sets the "cost_status" field.
func (u *UsageFinanceCostSegmentUpsert) SetCostStatus(v string) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldCostStatus, v)
	return u
}

// UpdateCostStatus sets the "cost_status" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateCostStatus() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldCostStatus)
	return u
}

// SetCostAmount sets the "cost_amount" field.
func (u *UsageFinanceCostSegmentUpsert) SetCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldCostAmount, v)
	return u
}

// UpdateCostAmount sets the "cost_amount" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateCostAmount() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldCostAmount)
	return u
}

// AddCostAmount adds v to the "cost_amount" field.
func (u *UsageFinanceCostSegmentUpsert) AddCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentUpsert {
	u.Add(usagefinancecostsegment.FieldCostAmount, v)
	return u
}

// ClearCostAmount clears the value of the "cost_amount" field.
func (u *UsageFinanceCostSegmentUpsert) ClearCostAmount() *UsageFinanceCostSegmentUpsert {
	u.SetNull(usagefinancecostsegment.FieldCostAmount)
	return u
}

// SetCalculationDetail sets the "calculation_detail" field.
func (u *UsageFinanceCostSegmentUpsert) SetCalculationDetail(v map[string]interface{}) *UsageFinanceCostSegmentUpsert {
	u.Set(usagefinancecostsegment.FieldCalculationDetail, v)
	return u
}

// UpdateCalculationDetail sets the "calculation_detail" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsert) UpdateCalculationDetail() *UsageFinanceCostSegmentUpsert {
	u.SetExcluded(usagefinancecostsegment.FieldCalculationDetail)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageFinanceCostSegment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageFinanceCostSegmentUpsertOne) UpdateNewValues() *UsageFinanceCostSegmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagefinancecostsegment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageFinanceCostSegment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageFinanceCostSegmentUpsertOne) Ignore() *UsageFinanceCostSegmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageFinanceCostSegmentUpsertOne) DoNothing() *UsageFinanceCostSegmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageFinanceCostSegmentCreate.OnConflict
// documentation for more info.
func (u *UsageFinanceCostSegmentUpsertOne) Update(set func(*UsageFinanceCostSegmentUpsert)) *UsageFinanceCostSegmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageFinanceCostSegmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageFinanceRecordID sets the "usage_finance_record_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUsageFinanceRecordID(v)
	})
}

// AddUsageFinanceRecordID adds v to the "usage_finance_record_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddUsageFinanceRecordID(v)
	})
}

// UpdateUsageFinanceRecordID sets the "usage_finance_record_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateUsageFinanceRecordID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUsageFinanceRecordID()
	})
}

// SetAttemptNo sets the "attempt_no" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetAttemptNo(v int) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetAttemptNo(v)
	})
}

// AddAttemptNo adds v to the "attempt_no" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddAttemptNo(v int) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddAttemptNo(v)
	})
}

// UpdateAttemptNo sets the "attempt_no" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateAttemptNo() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateAttemptNo()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetAccountID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddAccountID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateAccountID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateAccountID()
	})
}

// SetWalletID sets the "wallet_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetWalletID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetWalletID(v)
	})
}

// AddWalletID adds v to the "wallet_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddWalletID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddWalletID(v)
	})
}

// UpdateWalletID sets the "wallet_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateWalletID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateWalletID()
	})
}

// ClearWalletID clears the value of the "wallet_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearWalletID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearWalletID()
	})
}

// SetUpstreamID sets the "upstream_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetUpstreamID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamID(v)
	})
}

// AddUpstreamID adds v to the "upstream_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddUpstreamID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddUpstreamID(v)
	})
}

// UpdateUpstreamID sets the "upstream_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateUpstreamID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamID()
	})
}

// ClearUpstreamID clears the value of the "upstream_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearUpstreamID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearUpstreamID()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetChannelID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddChannelID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateChannelID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateChannelID()
	})
}

// ClearChannelID clears the value of the "channel_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearChannelID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearChannelID()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetUpstreamModel(v string) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateUpstreamModel() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetServiceTier sets the "service_tier" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetServiceTier(v string) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetServiceTier(v)
	})
}

// UpdateServiceTier sets the "service_tier" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateServiceTier() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateServiceTier()
	})
}

// ClearServiceTier clears the value of the "service_tier" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearServiceTier() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearServiceTier()
	})
}

// SetUsageDetail sets the "usage_detail" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetUsageDetail(v map[string]interface{}) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUsageDetail(v)
	})
}

// UpdateUsageDetail sets the "usage_detail" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateUsageDetail() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUsageDetail()
	})
}

// SetUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamCostMultiplierSnapshot(v)
	})
}

// AddUpstreamCostMultiplierSnapshot adds v to the "upstream_cost_multiplier_snapshot" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddUpstreamCostMultiplierSnapshot(v)
	})
}

// UpdateUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateUpstreamCostMultiplierSnapshot() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamCostMultiplierSnapshot()
	})
}

// ClearUpstreamCostMultiplierSnapshot clears the value of the "upstream_cost_multiplier_snapshot" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearUpstreamCostMultiplierSnapshot() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearUpstreamCostMultiplierSnapshot()
	})
}

// SetUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamMultiplierChangeID(v)
	})
}

// AddUpstreamMultiplierChangeID adds v to the "upstream_multiplier_change_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddUpstreamMultiplierChangeID(v)
	})
}

// UpdateUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateUpstreamMultiplierChangeID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamMultiplierChangeID()
	})
}

// ClearUpstreamMultiplierChangeID clears the value of the "upstream_multiplier_change_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearUpstreamMultiplierChangeID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearUpstreamMultiplierChangeID()
	})
}

// SetUpstreamMultiplierSource sets the "upstream_multiplier_source" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetUpstreamMultiplierSource(v string) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamMultiplierSource(v)
	})
}

// UpdateUpstreamMultiplierSource sets the "upstream_multiplier_source" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateUpstreamMultiplierSource() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamMultiplierSource()
	})
}

// ClearUpstreamMultiplierSource clears the value of the "upstream_multiplier_source" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearUpstreamMultiplierSource() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearUpstreamMultiplierSource()
	})
}

// SetUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetUpstreamMultiplierEffectiveAt(v time.Time) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamMultiplierEffectiveAt(v)
	})
}

// UpdateUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateUpstreamMultiplierEffectiveAt() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamMultiplierEffectiveAt()
	})
}

// ClearUpstreamMultiplierEffectiveAt clears the value of the "upstream_multiplier_effective_at" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearUpstreamMultiplierEffectiveAt() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearUpstreamMultiplierEffectiveAt()
	})
}

// SetAccountFinanceProfileID sets the "account_finance_profile_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetAccountFinanceProfileID(v)
	})
}

// AddAccountFinanceProfileID adds v to the "account_finance_profile_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddAccountFinanceProfileID(v)
	})
}

// UpdateAccountFinanceProfileID sets the "account_finance_profile_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateAccountFinanceProfileID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateAccountFinanceProfileID()
	})
}

// ClearAccountFinanceProfileID clears the value of the "account_finance_profile_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearAccountFinanceProfileID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearAccountFinanceProfileID()
	})
}

// SetFxRateVersionID sets the "fx_rate_version_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetFxRateVersionID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetFxRateVersionID(v)
	})
}

// AddFxRateVersionID adds v to the "fx_rate_version_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddFxRateVersionID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddFxRateVersionID(v)
	})
}

// UpdateFxRateVersionID sets the "fx_rate_version_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateFxRateVersionID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateFxRateVersionID()
	})
}

// ClearFxRateVersionID clears the value of the "fx_rate_version_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearFxRateVersionID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearFxRateVersionID()
	})
}

// SetSourceCurrency sets the "source_currency" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetSourceCurrency(v string) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetSourceCurrency(v)
	})
}

// UpdateSourceCurrency sets the "source_currency" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateSourceCurrency() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateSourceCurrency()
	})
}

// ClearSourceCurrency clears the value of the "source_currency" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearSourceCurrency() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearSourceCurrency()
	})
}

// SetFxRateToUsd sets the "fx_rate_to_usd" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetFxRateToUsd(v)
	})
}

// AddFxRateToUsd adds v to the "fx_rate_to_usd" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddFxRateToUsd(v)
	})
}

// UpdateFxRateToUsd sets the "fx_rate_to_usd" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateFxRateToUsd() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateFxRateToUsd()
	})
}

// ClearFxRateToUsd clears the value of the "fx_rate_to_usd" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearFxRateToUsd() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearFxRateToUsd()
	})
}

// SetFxSource sets the "fx_source" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetFxSource(v string) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetFxSource(v)
	})
}

// UpdateFxSource sets the "fx_source" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateFxSource() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateFxSource()
	})
}

// ClearFxSource clears the value of the "fx_source" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearFxSource() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearFxSource()
	})
}

// SetFxObservedAt sets the "fx_observed_at" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetFxObservedAt(v time.Time) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetFxObservedAt(v)
	})
}

// UpdateFxObservedAt sets the "fx_observed_at" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateFxObservedAt() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateFxObservedAt()
	})
}

// ClearFxObservedAt clears the value of the "fx_observed_at" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearFxObservedAt() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearFxObservedAt()
	})
}

// SetPriceVersionID sets the "price_version_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetPriceVersionID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetPriceVersionID(v)
	})
}

// AddPriceVersionID adds v to the "price_version_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddPriceVersionID(v int64) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddPriceVersionID(v)
	})
}

// UpdatePriceVersionID sets the "price_version_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdatePriceVersionID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdatePriceVersionID()
	})
}

// ClearPriceVersionID clears the value of the "price_version_id" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearPriceVersionID() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearPriceVersionID()
	})
}

// SetPricingSource sets the "pricing_source" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetPricingSource(v string) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetPricingSource(v)
	})
}

// UpdatePricingSource sets the "pricing_source" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdatePricingSource() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdatePricingSource()
	})
}

// ClearPricingSource clears the value of the "pricing_source" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearPricingSource() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearPricingSource()
	})
}

// SetCostStatus sets the "cost_status" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetCostStatus(v string) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetCostStatus(v)
	})
}

// UpdateCostStatus sets the "cost_status" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateCostStatus() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateCostStatus()
	})
}

// SetCostAmount sets the "cost_amount" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetCostAmount(v)
	})
}

// AddCostAmount adds v to the "cost_amount" field.
func (u *UsageFinanceCostSegmentUpsertOne) AddCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddCostAmount(v)
	})
}

// UpdateCostAmount sets the "cost_amount" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateCostAmount() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateCostAmount()
	})
}

// ClearCostAmount clears the value of the "cost_amount" field.
func (u *UsageFinanceCostSegmentUpsertOne) ClearCostAmount() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearCostAmount()
	})
}

// SetCalculationDetail sets the "calculation_detail" field.
func (u *UsageFinanceCostSegmentUpsertOne) SetCalculationDetail(v map[string]interface{}) *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetCalculationDetail(v)
	})
}

// UpdateCalculationDetail sets the "calculation_detail" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertOne) UpdateCalculationDetail() *UsageFinanceCostSegmentUpsertOne {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateCalculationDetail()
	})
}

// Exec executes the query.
func (u *UsageFinanceCostSegmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageFinanceCostSegmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageFinanceCostSegmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageFinanceCostSegmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageFinanceCostSegmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageFinanceCostSegmentCreateBulk is the builder for creating many UsageFinanceCostSegment entities in bulk.
type UsageFinanceCostSegmentCreateBulk struct {
	config
	err      error
	builders []*UsageFinanceCostSegmentCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageFinanceCostSegment entities in the database.
func (_c *UsageFinanceCostSegmentCreateBulk) Save(ctx context.Context) ([]*UsageFinanceCostSegment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageFinanceCostSegment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageFinanceCostSegmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageFinanceCostSegmentCreateBulk) SaveX(ctx context.Context) []*UsageFinanceCostSegment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageFinanceCostSegmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageFinanceCostSegmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageFinanceCostSegment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageFinanceCostSegmentUpsert) {
//			SetUsageFinanceRecordID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageFinanceCostSegmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageFinanceCostSegmentUpsertBulk {
	_c.conflict = opts
	return &UsageFinanceCostSegmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageFinanceCostSegment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageFinanceCostSegmentCreateBulk) OnConflictColumns(columns ...string) *UsageFinanceCostSegmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageFinanceCostSegmentUpsertBulk{
		create: _c,
	}
}

// UsageFinanceCostSegmentUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageFinanceCostSegment nodes.
type UsageFinanceCostSegmentUpsertBulk struct {
	create *UsageFinanceCostSegmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageFinanceCostSegment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateNewValues() *UsageFinanceCostSegmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagefinancecostsegment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageFinanceCostSegment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageFinanceCostSegmentUpsertBulk) Ignore() *UsageFinanceCostSegmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageFinanceCostSegmentUpsertBulk) DoNothing() *UsageFinanceCostSegmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageFinanceCostSegmentCreateBulk.OnConflict
// documentation for more info.
func (u *UsageFinanceCostSegmentUpsertBulk) Update(set func(*UsageFinanceCostSegmentUpsert)) *UsageFinanceCostSegmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageFinanceCostSegmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageFinanceRecordID sets the "usage_finance_record_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUsageFinanceRecordID(v)
	})
}

// AddUsageFinanceRecordID adds v to the "usage_finance_record_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddUsageFinanceRecordID(v)
	})
}

// UpdateUsageFinanceRecordID sets the "usage_finance_record_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateUsageFinanceRecordID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUsageFinanceRecordID()
	})
}

// SetAttemptNo sets the "attempt_no" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetAttemptNo(v int) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetAttemptNo(v)
	})
}

// AddAttemptNo adds v to the "attempt_no" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddAttemptNo(v int) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddAttemptNo(v)
	})
}

// UpdateAttemptNo sets the "attempt_no" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateAttemptNo() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateAttemptNo()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetAccountID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddAccountID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateAccountID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateAccountID()
	})
}

// SetWalletID sets the "wallet_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetWalletID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetWalletID(v)
	})
}

// AddWalletID adds v to the "wallet_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddWalletID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddWalletID(v)
	})
}

// UpdateWalletID sets the "wallet_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateWalletID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateWalletID()
	})
}

// ClearWalletID clears the value of the "wallet_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearWalletID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearWalletID()
	})
}

// SetUpstreamID sets the "upstream_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetUpstreamID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamID(v)
	})
}

// AddUpstreamID adds v to the "upstream_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddUpstreamID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddUpstreamID(v)
	})
}

// UpdateUpstreamID sets the "upstream_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateUpstreamID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamID()
	})
}

// ClearUpstreamID clears the value of the "upstream_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearUpstreamID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearUpstreamID()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetChannelID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddChannelID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateChannelID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateChannelID()
	})
}

// ClearChannelID clears the value of the "channel_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearChannelID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearChannelID()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetUpstreamModel(v string) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateUpstreamModel() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetServiceTier sets the "service_tier" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetServiceTier(v string) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetServiceTier(v)
	})
}

// UpdateServiceTier sets the "service_tier" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateServiceTier() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateServiceTier()
	})
}

// ClearServiceTier clears the value of the "service_tier" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearServiceTier() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearServiceTier()
	})
}

// SetUsageDetail sets the "usage_detail" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetUsageDetail(v map[string]interface{}) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUsageDetail(v)
	})
}

// UpdateUsageDetail sets the "usage_detail" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateUsageDetail() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUsageDetail()
	})
}

// SetUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamCostMultiplierSnapshot(v)
	})
}

// AddUpstreamCostMultiplierSnapshot adds v to the "upstream_cost_multiplier_snapshot" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddUpstreamCostMultiplierSnapshot(v)
	})
}

// UpdateUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateUpstreamCostMultiplierSnapshot() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamCostMultiplierSnapshot()
	})
}

// ClearUpstreamCostMultiplierSnapshot clears the value of the "upstream_cost_multiplier_snapshot" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearUpstreamCostMultiplierSnapshot() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearUpstreamCostMultiplierSnapshot()
	})
}

// SetUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamMultiplierChangeID(v)
	})
}

// AddUpstreamMultiplierChangeID adds v to the "upstream_multiplier_change_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddUpstreamMultiplierChangeID(v)
	})
}

// UpdateUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateUpstreamMultiplierChangeID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamMultiplierChangeID()
	})
}

// ClearUpstreamMultiplierChangeID clears the value of the "upstream_multiplier_change_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearUpstreamMultiplierChangeID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearUpstreamMultiplierChangeID()
	})
}

// SetUpstreamMultiplierSource sets the "upstream_multiplier_source" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetUpstreamMultiplierSource(v string) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamMultiplierSource(v)
	})
}

// UpdateUpstreamMultiplierSource sets the "upstream_multiplier_source" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateUpstreamMultiplierSource() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamMultiplierSource()
	})
}

// ClearUpstreamMultiplierSource clears the value of the "upstream_multiplier_source" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearUpstreamMultiplierSource() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearUpstreamMultiplierSource()
	})
}

// SetUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetUpstreamMultiplierEffectiveAt(v time.Time) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetUpstreamMultiplierEffectiveAt(v)
	})
}

// UpdateUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateUpstreamMultiplierEffectiveAt() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateUpstreamMultiplierEffectiveAt()
	})
}

// ClearUpstreamMultiplierEffectiveAt clears the value of the "upstream_multiplier_effective_at" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearUpstreamMultiplierEffectiveAt() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearUpstreamMultiplierEffectiveAt()
	})
}

// SetAccountFinanceProfileID sets the "account_finance_profile_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetAccountFinanceProfileID(v)
	})
}

// AddAccountFinanceProfileID adds v to the "account_finance_profile_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddAccountFinanceProfileID(v)
	})
}

// UpdateAccountFinanceProfileID sets the "account_finance_profile_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateAccountFinanceProfileID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateAccountFinanceProfileID()
	})
}

// ClearAccountFinanceProfileID clears the value of the "account_finance_profile_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearAccountFinanceProfileID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearAccountFinanceProfileID()
	})
}

// SetFxRateVersionID sets the "fx_rate_version_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetFxRateVersionID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetFxRateVersionID(v)
	})
}

// AddFxRateVersionID adds v to the "fx_rate_version_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddFxRateVersionID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddFxRateVersionID(v)
	})
}

// UpdateFxRateVersionID sets the "fx_rate_version_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateFxRateVersionID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateFxRateVersionID()
	})
}

// ClearFxRateVersionID clears the value of the "fx_rate_version_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearFxRateVersionID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearFxRateVersionID()
	})
}

// SetSourceCurrency sets the "source_currency" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetSourceCurrency(v string) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetSourceCurrency(v)
	})
}

// UpdateSourceCurrency sets the "source_currency" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateSourceCurrency() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateSourceCurrency()
	})
}

// ClearSourceCurrency clears the value of the "source_currency" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearSourceCurrency() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearSourceCurrency()
	})
}

// SetFxRateToUsd sets the "fx_rate_to_usd" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetFxRateToUsd(v)
	})
}

// AddFxRateToUsd adds v to the "fx_rate_to_usd" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddFxRateToUsd(v)
	})
}

// UpdateFxRateToUsd sets the "fx_rate_to_usd" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateFxRateToUsd() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateFxRateToUsd()
	})
}

// ClearFxRateToUsd clears the value of the "fx_rate_to_usd" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearFxRateToUsd() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearFxRateToUsd()
	})
}

// SetFxSource sets the "fx_source" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetFxSource(v string) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetFxSource(v)
	})
}

// UpdateFxSource sets the "fx_source" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateFxSource() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateFxSource()
	})
}

// ClearFxSource clears the value of the "fx_source" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearFxSource() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearFxSource()
	})
}

// SetFxObservedAt sets the "fx_observed_at" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetFxObservedAt(v time.Time) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetFxObservedAt(v)
	})
}

// UpdateFxObservedAt sets the "fx_observed_at" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateFxObservedAt() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateFxObservedAt()
	})
}

// ClearFxObservedAt clears the value of the "fx_observed_at" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearFxObservedAt() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearFxObservedAt()
	})
}

// SetPriceVersionID sets the "price_version_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetPriceVersionID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetPriceVersionID(v)
	})
}

// AddPriceVersionID adds v to the "price_version_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddPriceVersionID(v int64) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddPriceVersionID(v)
	})
}

// UpdatePriceVersionID sets the "price_version_id" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdatePriceVersionID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdatePriceVersionID()
	})
}

// ClearPriceVersionID clears the value of the "price_version_id" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearPriceVersionID() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearPriceVersionID()
	})
}

// SetPricingSource sets the "pricing_source" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetPricingSource(v string) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetPricingSource(v)
	})
}

// UpdatePricingSource sets the "pricing_source" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdatePricingSource() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdatePricingSource()
	})
}

// ClearPricingSource clears the value of the "pricing_source" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearPricingSource() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearPricingSource()
	})
}

// SetCostStatus sets the "cost_status" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetCostStatus(v string) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetCostStatus(v)
	})
}

// UpdateCostStatus sets the "cost_status" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateCostStatus() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateCostStatus()
	})
}

// SetCostAmount sets the "cost_amount" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetCostAmount(v)
	})
}

// AddCostAmount adds v to the "cost_amount" field.
func (u *UsageFinanceCostSegmentUpsertBulk) AddCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.AddCostAmount(v)
	})
}

// UpdateCostAmount sets the "cost_amount" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateCostAmount() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateCostAmount()
	})
}

// ClearCostAmount clears the value of the "cost_amount" field.
func (u *UsageFinanceCostSegmentUpsertBulk) ClearCostAmount() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.ClearCostAmount()
	})
}

// SetCalculationDetail sets the "calculation_detail" field.
func (u *UsageFinanceCostSegmentUpsertBulk) SetCalculationDetail(v map[string]interface{}) *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.SetCalculationDetail(v)
	})
}

// UpdateCalculationDetail sets the "calculation_detail" field to the value that was provided on create.
func (u *UsageFinanceCostSegmentUpsertBulk) UpdateCalculationDetail() *UsageFinanceCostSegmentUpsertBulk {
	return u.Update(func(s *UsageFinanceCostSegmentUpsert) {
		s.UpdateCalculationDetail()
	})
}

// Exec executes the query.
func (u *UsageFinanceCostSegmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageFinanceCostSegmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageFinanceCostSegmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageFinanceCostSegmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
