// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagefinancecostsegment"
	"github.com/shopspring/decimal"
)

// UsageFinanceCostSegmentUpdate is the builder for updating UsageFinanceCostSegment entities.
type UsageFinanceCostSegmentUpdate struct {
	config
	hooks    []Hook
	mutation *UsageFinanceCostSegmentMutation
}

// Where appends a list predicates to the UsageFinanceCostSegmentUpdate builder.
func (_u *UsageFinanceCostSegmentUpdate) Where(ps ...predicate.UsageFinanceCostSegment) *UsageFinanceCostSegmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsageFinanceRecordID sets the "usage_finance_record_id" field.
func (_u *UsageFinanceCostSegmentUpdate) SetUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetUsageFinanceRecordID()
	_u.mutation.SetUsageFinanceRecordID(v)
	return _u
}

// SetNillableUsageFinanceRecordID sets the "usage_finance_record_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableUsageFinanceRecordID(v *int64) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetUsageFinanceRecordID(*v)
	}
	return _u
}

// AddUsageFinanceRecordID adds value to the "usage_finance_record_id" field.
func (_u *UsageFinanceCostSegmentUpdate) AddUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddUsageFinanceRecordID(v)
	return _u
}

// SetAttemptNo sets the "attempt_no" field.
func (_u *UsageFinanceCostSegmentUpdate) SetAttemptNo(v int) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetAttemptNo()
	_u.mutation.SetAttemptNo(v)
	return _u
}

// SetNillableAttemptNo sets the "attempt_no" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableAttemptNo(v *int) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetAttemptNo(*v)
	}
	return _u
}

// AddAttemptNo adds value to the "attempt_no" field.
func (_u *UsageFinanceCostSegmentUpdate) AddAttemptNo(v int) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddAttemptNo(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UsageFinanceCostSegmentUpdate) SetAccountID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableAccountID(v *int64) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UsageFinanceCostSegmentUpdate) AddAccountID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetWalletID sets the "wallet_id" field.
func (_u *UsageFinanceCostSegmentUpdate) SetWalletID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetWalletID()
	_u.mutation.SetWalletID(v)
	return _u
}

// SetNillableWalletID sets the "wallet_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableWalletID(v *int64) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetWalletID(*v)
	}
	return _u
}

// AddWalletID adds value to the "wallet_id" field.
func (_u *UsageFinanceCostSegmentUpdate) AddWalletID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddWalletID(v)
	return _u
}

// ClearWalletID clears the value of the "wallet_id" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearWalletID() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearWalletID()
	return _u
}

// SetUpstreamID sets the "upstream_id" field.
func (_u *UsageFinanceCostSegmentUpdate) SetUpstreamID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetUpstreamID()
	_u.mutation.SetUpstreamID(v)
	return _u
}

// SetNillableUpstreamID sets the "upstream_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableUpstreamID(v *int64) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetUpstreamID(*v)
	}
	return _u
}

// AddUpstreamID adds value to the "upstream_id" field.
func (_u *UsageFinanceCostSegmentUpdate) AddUpstreamID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddUpstreamID(v)
	return _u
}

// ClearUpstreamID clears the value of the "upstream_id" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearUpstreamID() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearUpstreamID()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *UsageFinanceCostSegmentUpdate) SetChannelID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableChannelID(v *int64) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *UsageFinanceCostSegmentUpdate) AddChannelID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddChannelID(v)
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearChannelID() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearChannelID()
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *UsageFinanceCostSegmentUpdate) SetUpstreamModel(v string) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableUpstreamModel(v *string) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetServiceTier sets the "service_tier" field.
func (_u *UsageFinanceCostSegmentUpdate) SetServiceTier(v string) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetServiceTier(v)
	return _u
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableServiceTier(v *string) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetServiceTier(*v)
	}
	return _u
}

// ClearServiceTier clears the value of the "service_tier" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearServiceTier() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearServiceTier()
	return _u
}

// SetUsageDetail sets the "usage_detail" field.
func (_u *UsageFinanceCostSegmentUpdate) SetUsageDetail(v map[string]interface{}) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetUsageDetail(v)
	return _u
}

// SetUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field.
func (_u *UsageFinanceCostSegmentUpdate) SetUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetUpstreamCostMultiplierSnapshot()
	_u.mutation.SetUpstreamCostMultiplierSnapshot(v)
	return _u
}

// SetNillableUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableUpstreamCostMultiplierSnapshot(v *decimal.Decimal) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetUpstreamCostMultiplierSnapshot(*v)
	}
	return _u
}

// AddUpstreamCostMultiplierSnapshot adds value to the "upstream_cost_multiplier_snapshot" field.
func (_u *UsageFinanceCostSegmentUpdate) AddUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddUpstreamCostMultiplierSnapshot(v)
	return _u
}

// ClearUpstreamCostMultiplierSnapshot clears the value of the "upstream_cost_multiplier_snapshot" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearUpstreamCostMultiplierSnapshot() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearUpstreamCostMultiplierSnapshot()
	return _u
}

// SetUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field.
func (_u *UsageFinanceCostSegmentUpdate) SetUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetUpstreamMultiplierChangeID()
	_u.mutation.SetUpstreamMultiplierChangeID(v)
	return _u
}

// SetNillableUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableUpstreamMultiplierChangeID(v *int64) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetUpstreamMultiplierChangeID(*v)
	}
	return _u
}

// AddUpstreamMultiplierChangeID adds value to the "upstream_multiplier_change_id" field.
func (_u *UsageFinanceCostSegmentUpdate) AddUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddUpstreamMultiplierChangeID(v)
	return _u
}

// ClearUpstreamMultiplierChangeID clears the value of the "upstream_multiplier_change_id" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearUpstreamMultiplierChangeID() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearUpstreamMultiplierChangeID()
	return _u
}

// SetUpstreamMultiplierSource sets the "upstream_multiplier_source" field.
func (_u *UsageFinanceCostSegmentUpdate) SetUpstreamMultiplierSource(v string) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetUpstreamMultiplierSource(v)
	return _u
}

// SetNillableUpstreamMultiplierSource sets the "upstream_multiplier_source" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableUpstreamMultiplierSource(v *string) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetUpstreamMultiplierSource(*v)
	}
	return _u
}

// ClearUpstreamMultiplierSource clears the value of the "upstream_multiplier_source" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearUpstreamMultiplierSource() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearUpstreamMultiplierSource()
	return _u
}

// SetUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field.
func (_u *UsageFinanceCostSegmentUpdate) SetUpstreamMultiplierEffectiveAt(v time.Time) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetUpstreamMultiplierEffectiveAt(v)
	return _u
}

// SetNillableUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableUpstreamMultiplierEffectiveAt(v *time.Time) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetUpstreamMultiplierEffectiveAt(*v)
	}
	return _u
}

// ClearUpstreamMultiplierEffectiveAt clears the value of the "upstream_multiplier_effective_at" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearUpstreamMultiplierEffectiveAt() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearUpstreamMultiplierEffectiveAt()
	return _u
}

// SetAccountFinanceProfileID sets the "account_finance_profile_id" field.
func (_u *UsageFinanceCostSegmentUpdate) SetAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetAccountFinanceProfileID()
	_u.mutation.SetAccountFinanceProfileID(v)
	return _u
}

// SetNillableAccountFinanceProfileID sets the "account_finance_profile_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableAccountFinanceProfileID(v *int64) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetAccountFinanceProfileID(*v)
	}
	return _u
}

// AddAccountFinanceProfileID adds value to the "account_finance_profile_id" field.
func (_u *UsageFinanceCostSegmentUpdate) AddAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddAccountFinanceProfileID(v)
	return _u
}

// ClearAccountFinanceProfileID clears the value of the "account_finance_profile_id" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearAccountFinanceProfileID() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearAccountFinanceProfileID()
	return _u
}

// SetFxRateVersionID sets the "fx_rate_version_id" field.
func (_u *UsageFinanceCostSegmentUpdate) SetFxRateVersionID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetFxRateVersionID()
	_u.mutation.SetFxRateVersionID(v)
	return _u
}

// SetNillableFxRateVersionID sets the "fx_rate_version_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableFxRateVersionID(v *int64) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetFxRateVersionID(*v)
	}
	return _u
}

// AddFxRateVersionID adds value to the "fx_rate_version_id" field.
func (_u *UsageFinanceCostSegmentUpdate) AddFxRateVersionID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddFxRateVersionID(v)
	return _u
}

// ClearFxRateVersionID clears the value of the "fx_rate_version_id" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearFxRateVersionID() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearFxRateVersionID()
	return _u
}

// SetSourceCurrency sets the "source_currency" field.
func (_u *UsageFinanceCostSegmentUpdate) SetSourceCurrency(v string) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetSourceCurrency(v)
	return _u
}

// SetNillableSourceCurrency sets the "source_currency" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableSourceCurrency(v *string) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetSourceCurrency(*v)
	}
	return _u
}

// ClearSourceCurrency clears the value of the "source_currency" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearSourceCurrency() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearSourceCurrency()
	return _u
}

// SetFxRateToUsd sets the "fx_rate_to_usd" field.
func (_u *UsageFinanceCostSegmentUpdate) SetFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetFxRateToUsd()
	_u.mutation.SetFxRateToUsd(v)
	return _u
}

// SetNillableFxRateToUsd sets the "fx_rate_to_usd" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableFxRateToUsd(v *decimal.Decimal) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetFxRateToUsd(*v)
	}
	return _u
}

// AddFxRateToUsd adds value to the "fx_rate_to_usd" field.
func (_u *UsageFinanceCostSegmentUpdate) AddFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddFxRateToUsd(v)
	return _u
}

// ClearFxRateToUsd clears the value of the "fx_rate_to_usd" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearFxRateToUsd() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearFxRateToUsd()
	return _u
}

// SetFxSource sets the "fx_source" field.
func (_u *UsageFinanceCostSegmentUpdate) SetFxSource(v string) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetFxSource(v)
	return _u
}

// SetNillableFxSource sets the "fx_source" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableFxSource(v *string) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetFxSource(*v)
	}
	return _u
}

// ClearFxSource clears the value of the "fx_source" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearFxSource() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearFxSource()
	return _u
}

// SetFxObservedAt sets the "fx_observed_at" field.
func (_u *UsageFinanceCostSegmentUpdate) SetFxObservedAt(v time.Time) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetFxObservedAt(v)
	return _u
}

// SetNillableFxObservedAt sets the "fx_observed_at" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableFxObservedAt(v *time.Time) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetFxObservedAt(*v)
	}
	return _u
}

// ClearFxObservedAt clears the value of the "fx_observed_at" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearFxObservedAt() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearFxObservedAt()
	return _u
}

// SetPriceVersionID sets the "price_version_id" field.
func (_u *UsageFinanceCostSegmentUpdate) SetPriceVersionID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetPriceVersionID()
	_u.mutation.SetPriceVersionID(v)
	return _u
}

// SetNillablePriceVersionID sets the "price_version_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillablePriceVersionID(v *int64) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetPriceVersionID(*v)
	}
	return _u
}

// AddPriceVersionID adds value to the "price_version_id" field.
func (_u *UsageFinanceCostSegmentUpdate) AddPriceVersionID(v int64) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddPriceVersionID(v)
	return _u
}

// ClearPriceVersionID clears the value of the "price_version_id" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearPriceVersionID() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearPriceVersionID()
	return _u
}

// SetPricingSource sets the "pricing_source" field.
func (_u *UsageFinanceCostSegmentUpdate) SetPricingSource(v string) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetPricingSource(v)
	return _u
}

// SetNillablePricingSource sets the "pricing_source" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillablePricingSource(v *string) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetPricingSource(*v)
	}
	return _u
}

// ClearPricingSource clears the value of the "pricing_source" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearPricingSource() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearPricingSource()
	return _u
}

// SetCostStatus sets the "cost_status" field.
func (_u *UsageFinanceCostSegmentUpdate) SetCostStatus(v string) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetCostStatus(v)
	return _u
}

// SetNillableCostStatus sets the "cost_status" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableCostStatus(v *string) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetCostStatus(*v)
	}
	return _u
}

// SetCostAmount sets the "cost_amount" field.
func (_u *UsageFinanceCostSegmentUpdate) SetCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentUpdate {
	_u.mutation.ResetCostAmount()
	_u.mutation.SetCostAmount(v)
	return _u
}

// SetNillableCostAmount sets the "cost_amount" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdate) SetNillableCostAmount(v *decimal.Decimal) *UsageFinanceCostSegmentUpdate {
	if v != nil {
		_u.SetCostAmount(*v)
	}
	return _u
}

// AddCostAmount adds value to the "cost_amount" field.
func (_u *UsageFinanceCostSegmentUpdate) AddCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentUpdate {
	_u.mutation.AddCostAmount(v)
	return _u
}

// ClearCostAmount clears the value of the "cost_amount" field.
func (_u *UsageFinanceCostSegmentUpdate) ClearCostAmount() *UsageFinanceCostSegmentUpdate {
	_u.mutation.ClearCostAmount()
	return _u
}

// SetCalculationDetail sets the "calculation_detail" field.
func (_u *UsageFinanceCostSegmentUpdate) SetCalculationDetail(v map[string]interface{}) *UsageFinanceCostSegmentUpdate {
	_u.mutation.SetCalculationDetail(v)
	return _u
}

// Mutation returns the UsageFinanceCostSegmentMutation object of the builder.
func (_u *UsageFinanceCostSegmentUpdate) Mutation() *UsageFinanceCostSegmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageFinanceCostSegmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageFinanceCostSegmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageFinanceCostSegmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageFinanceCostSegmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageFinanceCostSegmentUpdate) check() error {
	if v, ok := _u.mutation.AttemptNo(); ok {
		if err := usagefinancecostsegment.AttemptNoValidator(v); err != nil {
			return &ValidationError{Name: "attempt_no", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.attempt_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := usagefinancecostsegment.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServiceTier(); ok {
		if err := usagefinancecostsegment.ServiceTierValidator(v); err != nil {
			return &ValidationError{Name: "service_tier", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.service_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamMultiplierSource(); ok {
		if err := usagefinancecostsegment.UpstreamMultiplierSourceValidator(v); err != nil {
			return &ValidationError{Name: "upstream_multiplier_source", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.upstream_multiplier_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceCurrency(); ok {
		if err := usagefinancecostsegment.SourceCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "source_currency", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.source_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FxSource(); ok {
		if err := usagefinancecostsegment.FxSourceValidator(v); err != nil {
			return &ValidationError{Name: "fx_source", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.fx_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PricingSource(); ok {
		if err := usagefinancecostsegment.PricingSourceValidator(v); err != nil {
			return &ValidationError{Name: "pricing_source", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.pricing_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostStatus(); ok {
		if err := usagefinancecostsegment.CostStatusValidator(v); err != nil {
			return &ValidationError{Name: "cost_status", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.cost_status": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageFinanceCostSegmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagefinancecostsegment.Table, usagefinancecostsegment.Columns, sqlgraph.NewFieldSpec(usagefinancecostsegment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsageFinanceRecordID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUsageFinanceRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageFinanceRecordID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldUsageFinanceRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AttemptNo(); ok {
		_spec.SetField(usagefinancecostsegment.FieldAttemptNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptNo(); ok {
		_spec.AddField(usagefinancecostsegment.FieldAttemptNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WalletID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldWalletID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWalletID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldWalletID, field.TypeInt64, value)
	}
	if _u.mutation.WalletIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldWalletID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldUpstreamID, field.TypeInt64, value)
	}
	if _u.mutation.UpstreamIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldUpstreamID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldChannelID, field.TypeInt64, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldChannelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceTier(); ok {
		_spec.SetField(usagefinancecostsegment.FieldServiceTier, field.TypeString, value)
	}
	if _u.mutation.ServiceTierCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldServiceTier, field.TypeString)
	}
	if value, ok := _u.mutation.UsageDetail(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUsageDetail, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpstreamCostMultiplierSnapshot(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamCostMultiplierSnapshot(); ok {
		_spec.AddField(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamCostMultiplierSnapshotCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamMultiplierChangeID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamMultiplierChangeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamMultiplierChangeID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldUpstreamMultiplierChangeID, field.TypeInt64, value)
	}
	if _u.mutation.UpstreamMultiplierChangeIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldUpstreamMultiplierChangeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamMultiplierSource(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamMultiplierSource, field.TypeString, value)
	}
	if _u.mutation.UpstreamMultiplierSourceCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldUpstreamMultiplierSource, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamMultiplierEffectiveAt(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamMultiplierEffectiveAt, field.TypeTime, value)
	}
	if _u.mutation.UpstreamMultiplierEffectiveAtCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldUpstreamMultiplierEffectiveAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AccountFinanceProfileID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldAccountFinanceProfileID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountFinanceProfileID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldAccountFinanceProfileID, field.TypeInt64, value)
	}
	if _u.mutation.AccountFinanceProfileIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldAccountFinanceProfileID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FxRateVersionID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxRateVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFxRateVersionID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldFxRateVersionID, field.TypeInt64, value)
	}
	if _u.mutation.FxRateVersionIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldFxRateVersionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceCurrency(); ok {
		_spec.SetField(usagefinancecostsegment.FieldSourceCurrency, field.TypeString, value)
	}
	if _u.mutation.SourceCurrencyCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldSourceCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.FxRateToUsd(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxRateToUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFxRateToUsd(); ok {
		_spec.AddField(usagefinancecostsegment.FieldFxRateToUsd, field.TypeFloat64, value)
	}
	if _u.mutation.FxRateToUsdCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldFxRateToUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FxSource(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxSource, field.TypeString, value)
	}
	if _u.mutation.FxSourceCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldFxSource, field.TypeString)
	}
	if value, ok := _u.mutation.FxObservedAt(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxObservedAt, field.TypeTime, value)
	}
	if _u.mutation.FxObservedAtCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldFxObservedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PriceVersionID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldPriceVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceVersionID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldPriceVersionID, field.TypeInt64, value)
	}
	if _u.mutation.PriceVersionIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldPriceVersionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PricingSource(); ok {
		_spec.SetField(usagefinancecostsegment.FieldPricingSource, field.TypeString, value)
	}
	if _u.mutation.PricingSourceCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldPricingSource, field.TypeString)
	}
	if value, ok := _u.mutation.CostStatus(); ok {
		_spec.SetField(usagefinancecostsegment.FieldCostStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostAmount(); ok {
		_spec.SetField(usagefinancecostsegment.FieldCostAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostAmount(); ok {
		_spec.AddField(usagefinancecostsegment.FieldCostAmount, field.TypeFloat64, value)
	}
	if _u.mutation.CostAmountCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldCostAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CalculationDetail(); ok {
		_spec.SetField(usagefinancecostsegment.FieldCalculationDetail, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagefinancecostsegment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageFinanceCostSegmentUpdateOne is the builder for updating a single UsageFinanceCostSegment entity.
type UsageFinanceCostSegmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageFinanceCostSegmentMutation
}

// SetUsageFinanceRecordID sets the "usage_finance_record_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetUsageFinanceRecordID()
	_u.mutation.SetUsageFinanceRecordID(v)
	return _u
}

// SetNillableUsageFinanceRecordID sets the "usage_finance_record_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableUsageFinanceRecordID(v *int64) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetUsageFinanceRecordID(*v)
	}
	return _u
}

// AddUsageFinanceRecordID adds value to the "usage_finance_record_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddUsageFinanceRecordID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddUsageFinanceRecordID(v)
	return _u
}

// SetAttemptNo sets the "attempt_no" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetAttemptNo(v int) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetAttemptNo()
	_u.mutation.SetAttemptNo(v)
	return _u
}

// SetNillableAttemptNo sets the "attempt_no" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableAttemptNo(v *int) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetAttemptNo(*v)
	}
	return _u
}

// AddAttemptNo adds value to the "attempt_no" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddAttemptNo(v int) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddAttemptNo(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetAccountID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableAccountID(v *int64) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddAccountID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetWalletID sets the "wallet_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetWalletID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetWalletID()
	_u.mutation.SetWalletID(v)
	return _u
}

// SetNillableWalletID sets the "wallet_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableWalletID(v *int64) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetWalletID(*v)
	}
	return _u
}

// AddWalletID adds value to the "wallet_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddWalletID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddWalletID(v)
	return _u
}

// ClearWalletID clears the value of the "wallet_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearWalletID() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearWalletID()
	return _u
}

// SetUpstreamID sets the "upstream_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetUpstreamID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetUpstreamID()
	_u.mutation.SetUpstreamID(v)
	return _u
}

// SetNillableUpstreamID sets the "upstream_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableUpstreamID(v *int64) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetUpstreamID(*v)
	}
	return _u
}

// AddUpstreamID adds value to the "upstream_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddUpstreamID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddUpstreamID(v)
	return _u
}

// ClearUpstreamID clears the value of the "upstream_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearUpstreamID() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearUpstreamID()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetChannelID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableChannelID(v *int64) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddChannelID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddChannelID(v)
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearChannelID() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearChannelID()
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetUpstreamModel(v string) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableUpstreamModel(v *string) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetServiceTier sets the "service_tier" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetServiceTier(v string) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetServiceTier(v)
	return _u
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableServiceTier(v *string) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetServiceTier(*v)
	}
	return _u
}

// ClearServiceTier clears the value of the "service_tier" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearServiceTier() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearServiceTier()
	return _u
}

// SetUsageDetail sets the "usage_detail" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetUsageDetail(v map[string]interface{}) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetUsageDetail(v)
	return _u
}

// SetUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetUpstreamCostMultiplierSnapshot()
	_u.mutation.SetUpstreamCostMultiplierSnapshot(v)
	return _u
}

// SetNillableUpstreamCostMultiplierSnapshot sets the "upstream_cost_multiplier_snapshot" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableUpstreamCostMultiplierSnapshot(v *decimal.Decimal) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetUpstreamCostMultiplierSnapshot(*v)
	}
	return _u
}

// AddUpstreamCostMultiplierSnapshot adds value to the "upstream_cost_multiplier_snapshot" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddUpstreamCostMultiplierSnapshot(v decimal.Decimal) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddUpstreamCostMultiplierSnapshot(v)
	return _u
}

// ClearUpstreamCostMultiplierSnapshot clears the value of the "upstream_cost_multiplier_snapshot" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearUpstreamCostMultiplierSnapshot() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearUpstreamCostMultiplierSnapshot()
	return _u
}

// SetUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetUpstreamMultiplierChangeID()
	_u.mutation.SetUpstreamMultiplierChangeID(v)
	return _u
}

// SetNillableUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableUpstreamMultiplierChangeID(v *int64) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetUpstreamMultiplierChangeID(*v)
	}
	return _u
}

// AddUpstreamMultiplierChangeID adds value to the "upstream_multiplier_change_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddUpstreamMultiplierChangeID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddUpstreamMultiplierChangeID(v)
	return _u
}

// ClearUpstreamMultiplierChangeID clears the value of the "upstream_multiplier_change_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearUpstreamMultiplierChangeID() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearUpstreamMultiplierChangeID()
	return _u
}

// SetUpstreamMultiplierSource sets the "upstream_multiplier_source" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetUpstreamMultiplierSource(v string) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetUpstreamMultiplierSource(v)
	return _u
}

// SetNillableUpstreamMultiplierSource sets the "upstream_multiplier_source" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableUpstreamMultiplierSource(v *string) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetUpstreamMultiplierSource(*v)
	}
	return _u
}

// ClearUpstreamMultiplierSource clears the value of the "upstream_multiplier_source" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearUpstreamMultiplierSource() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearUpstreamMultiplierSource()
	return _u
}

// SetUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetUpstreamMultiplierEffectiveAt(v time.Time) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetUpstreamMultiplierEffectiveAt(v)
	return _u
}

// SetNillableUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableUpstreamMultiplierEffectiveAt(v *time.Time) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetUpstreamMultiplierEffectiveAt(*v)
	}
	return _u
}

// ClearUpstreamMultiplierEffectiveAt clears the value of the "upstream_multiplier_effective_at" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearUpstreamMultiplierEffectiveAt() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearUpstreamMultiplierEffectiveAt()
	return _u
}

// SetAccountFinanceProfileID sets the "account_finance_profile_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetAccountFinanceProfileID()
	_u.mutation.SetAccountFinanceProfileID(v)
	return _u
}

// SetNillableAccountFinanceProfileID sets the "account_finance_profile_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableAccountFinanceProfileID(v *int64) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetAccountFinanceProfileID(*v)
	}
	return _u
}

// AddAccountFinanceProfileID adds value to the "account_finance_profile_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddAccountFinanceProfileID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddAccountFinanceProfileID(v)
	return _u
}

// ClearAccountFinanceProfileID clears the value of the "account_finance_profile_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearAccountFinanceProfileID() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearAccountFinanceProfileID()
	return _u
}

// SetFxRateVersionID sets the "fx_rate_version_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetFxRateVersionID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetFxRateVersionID()
	_u.mutation.SetFxRateVersionID(v)
	return _u
}

// SetNillableFxRateVersionID sets the "fx_rate_version_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableFxRateVersionID(v *int64) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetFxRateVersionID(*v)
	}
	return _u
}

// AddFxRateVersionID adds value to the "fx_rate_version_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddFxRateVersionID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddFxRateVersionID(v)
	return _u
}

// ClearFxRateVersionID clears the value of the "fx_rate_version_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearFxRateVersionID() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearFxRateVersionID()
	return _u
}

// SetSourceCurrency sets the "source_currency" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetSourceCurrency(v string) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetSourceCurrency(v)
	return _u
}

// SetNillableSourceCurrency sets the "source_currency" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableSourceCurrency(v *string) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetSourceCurrency(*v)
	}
	return _u
}

// ClearSourceCurrency clears the value of the "source_currency" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearSourceCurrency() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearSourceCurrency()
	return _u
}

// SetFxRateToUsd sets the "fx_rate_to_usd" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetFxRateToUsd()
	_u.mutation.SetFxRateToUsd(v)
	return _u
}

// SetNillableFxRateToUsd sets the "fx_rate_to_usd" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableFxRateToUsd(v *decimal.Decimal) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetFxRateToUsd(*v)
	}
	return _u
}

// AddFxRateToUsd adds value to the "fx_rate_to_usd" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddFxRateToUsd(v decimal.Decimal) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddFxRateToUsd(v)
	return _u
}

// ClearFxRateToUsd clears the value of the "fx_rate_to_usd" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearFxRateToUsd() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearFxRateToUsd()
	return _u
}

// SetFxSource sets the "fx_source" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetFxSource(v string) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetFxSource(v)
	return _u
}

// SetNillableFxSource sets the "fx_source" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableFxSource(v *string) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetFxSource(*v)
	}
	return _u
}

// ClearFxSource clears the value of the "fx_source" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearFxSource() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearFxSource()
	return _u
}

// SetFxObservedAt sets the "fx_observed_at" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetFxObservedAt(v time.Time) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetFxObservedAt(v)
	return _u
}

// SetNillableFxObservedAt sets the "fx_observed_at" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableFxObservedAt(v *time.Time) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetFxObservedAt(*v)
	}
	return _u
}

// ClearFxObservedAt clears the value of the "fx_observed_at" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearFxObservedAt() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearFxObservedAt()
	return _u
}

// SetPriceVersionID sets the "price_version_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetPriceVersionID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetPriceVersionID()
	_u.mutation.SetPriceVersionID(v)
	return _u
}

// SetNillablePriceVersionID sets the "price_version_id" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillablePriceVersionID(v *int64) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetPriceVersionID(*v)
	}
	return _u
}

// AddPriceVersionID adds value to the "price_version_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddPriceVersionID(v int64) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddPriceVersionID(v)
	return _u
}

// ClearPriceVersionID clears the value of the "price_version_id" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearPriceVersionID() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearPriceVersionID()
	return _u
}

// SetPricingSource sets the "pricing_source" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetPricingSource(v string) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetPricingSource(v)
	return _u
}

// SetNillablePricingSource sets the "pricing_source" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillablePricingSource(v *string) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetPricingSource(*v)
	}
	return _u
}

// ClearPricingSource clears the value of the "pricing_source" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearPricingSource() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearPricingSource()
	return _u
}

// SetCostStatus sets the "cost_status" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetCostStatus(v string) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetCostStatus(v)
	return _u
}

// SetNillableCostStatus sets the "cost_status" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableCostStatus(v *string) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetCostStatus(*v)
	}
	return _u
}

// SetCostAmount sets the "cost_amount" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ResetCostAmount()
	_u.mutation.SetCostAmount(v)
	return _u
}

// SetNillableCostAmount sets the "cost_amount" field if the given value is not nil.
func (_u *UsageFinanceCostSegmentUpdateOne) SetNillableCostAmount(v *decimal.Decimal) *UsageFinanceCostSegmentUpdateOne {
	if v != nil {
		_u.SetCostAmount(*v)
	}
	return _u
}

// AddCostAmount adds value to the "cost_amount" field.
func (_u *UsageFinanceCostSegmentUpdateOne) AddCostAmount(v decimal.Decimal) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.AddCostAmount(v)
	return _u
}

// ClearCostAmount clears the value of the "cost_amount" field.
func (_u *UsageFinanceCostSegmentUpdateOne) ClearCostAmount() *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.ClearCostAmount()
	return _u
}

// SetCalculationDetail sets the "calculation_detail" field.
func (_u *UsageFinanceCostSegmentUpdateOne) SetCalculationDetail(v map[string]interface{}) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.SetCalculationDetail(v)
	return _u
}

// Mutation returns the UsageFinanceCostSegmentMutation object of the builder.
func (_u *UsageFinanceCostSegmentUpdateOne) Mutation() *UsageFinanceCostSegmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsageFinanceCostSegmentUpdate builder.
func (_u *UsageFinanceCostSegmentUpdateOne) Where(ps ...predicate.UsageFinanceCostSegment) *UsageFinanceCostSegmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageFinanceCostSegmentUpdateOne) Select(field string, fields ...string) *UsageFinanceCostSegmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageFinanceCostSegment entity.
func (_u *UsageFinanceCostSegmentUpdateOne) Save(ctx context.Context) (*UsageFinanceCostSegment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageFinanceCostSegmentUpdateOne) SaveX(ctx context.Context) *UsageFinanceCostSegment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageFinanceCostSegmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageFinanceCostSegmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageFinanceCostSegmentUpdateOne) check() error {
	if v, ok := _u.mutation.AttemptNo(); ok {
		if err := usagefinancecostsegment.AttemptNoValidator(v); err != nil {
			return &ValidationError{Name: "attempt_no", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.attempt_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := usagefinancecostsegment.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServiceTier(); ok {
		if err := usagefinancecostsegment.ServiceTierValidator(v); err != nil {
			return &ValidationError{Name: "service_tier", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.service_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamMultiplierSource(); ok {
		if err := usagefinancecostsegment.UpstreamMultiplierSourceValidator(v); err != nil {
			return &ValidationError{Name: "upstream_multiplier_source", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.upstream_multiplier_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceCurrency(); ok {
		if err := usagefinancecostsegment.SourceCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "source_currency", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.source_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FxSource(); ok {
		if err := usagefinancecostsegment.FxSourceValidator(v); err != nil {
			return &ValidationError{Name: "fx_source", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.fx_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PricingSource(); ok {
		if err := usagefinancecostsegment.PricingSourceValidator(v); err != nil {
			return &ValidationError{Name: "pricing_source", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.pricing_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostStatus(); ok {
		if err := usagefinancecostsegment.CostStatusValidator(v); err != nil {
			return &ValidationError{Name: "cost_status", err: fmt.Errorf(`ent: validator failed for field "UsageFinanceCostSegment.cost_status": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageFinanceCostSegmentUpdateOne) sqlSave(ctx context.Context) (_node *UsageFinanceCostSegment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagefinancecostsegment.Table, usagefinancecostsegment.Columns, sqlgraph.NewFieldSpec(usagefinancecostsegment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageFinanceCostSegment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagefinancecostsegment.FieldID)
		for _, f := range fields {
			if !usagefinancecostsegment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagefinancecostsegment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsageFinanceRecordID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUsageFinanceRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageFinanceRecordID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldUsageFinanceRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AttemptNo(); ok {
		_spec.SetField(usagefinancecostsegment.FieldAttemptNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptNo(); ok {
		_spec.AddField(usagefinancecostsegment.FieldAttemptNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WalletID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldWalletID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWalletID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldWalletID, field.TypeInt64, value)
	}
	if _u.mutation.WalletIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldWalletID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldUpstreamID, field.TypeInt64, value)
	}
	if _u.mutation.UpstreamIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldUpstreamID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldChannelID, field.TypeInt64, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldChannelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceTier(); ok {
		_spec.SetField(usagefinancecostsegment.FieldServiceTier, field.TypeString, value)
	}
	if _u.mutation.ServiceTierCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldServiceTier, field.TypeString)
	}
	if value, ok := _u.mutation.UsageDetail(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUsageDetail, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpstreamCostMultiplierSnapshot(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamCostMultiplierSnapshot(); ok {
		_spec.AddField(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamCostMultiplierSnapshotCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldUpstreamCostMultiplierSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamMultiplierChangeID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamMultiplierChangeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamMultiplierChangeID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldUpstreamMultiplierChangeID, field.TypeInt64, value)
	}
	if _u.mutation.UpstreamMultiplierChangeIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldUpstreamMultiplierChangeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamMultiplierSource(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamMultiplierSource, field.TypeString, value)
	}
	if _u.mutation.UpstreamMultiplierSourceCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldUpstreamMultiplierSource, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamMultiplierEffectiveAt(); ok {
		_spec.SetField(usagefinancecostsegment.FieldUpstreamMultiplierEffectiveAt, field.TypeTime, value)
	}
	if _u.mutation.UpstreamMultiplierEffectiveAtCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldUpstreamMultiplierEffectiveAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AccountFinanceProfileID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldAccountFinanceProfileID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountFinanceProfileID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldAccountFinanceProfileID, field.TypeInt64, value)
	}
	if _u.mutation.AccountFinanceProfileIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldAccountFinanceProfileID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FxRateVersionID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxRateVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFxRateVersionID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldFxRateVersionID, field.TypeInt64, value)
	}
	if _u.mutation.FxRateVersionIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldFxRateVersionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceCurrency(); ok {
		_spec.SetField(usagefinancecostsegment.FieldSourceCurrency, field.TypeString, value)
	}
	if _u.mutation.SourceCurrencyCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldSourceCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.FxRateToUsd(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxRateToUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFxRateToUsd(); ok {
		_spec.AddField(usagefinancecostsegment.FieldFxRateToUsd, field.TypeFloat64, value)
	}
	if _u.mutation.FxRateToUsdCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldFxRateToUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FxSource(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxSource, field.TypeString, value)
	}
	if _u.mutation.FxSourceCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldFxSource, field.TypeString)
	}
	if value, ok := _u.mutation.FxObservedAt(); ok {
		_spec.SetField(usagefinancecostsegment.FieldFxObservedAt, field.TypeTime, value)
	}
	if _u.mutation.FxObservedAtCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldFxObservedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PriceVersionID(); ok {
		_spec.SetField(usagefinancecostsegment.FieldPriceVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceVersionID(); ok {
		_spec.AddField(usagefinancecostsegment.FieldPriceVersionID, field.TypeInt64, value)
	}
	if _u.mutation.PriceVersionIDCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldPriceVersionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PricingSource(); ok {
		_spec.SetField(usagefinancecostsegment.FieldPricingSource, field.TypeString, value)
	}
	if _u.mutation.PricingSourceCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldPricingSource, field.TypeString)
	}
	if value, ok := _u.mutation.CostStatus(); ok {
		_spec.SetField(usagefinancecostsegment.FieldCostStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostAmount(); ok {
		_spec.SetField(usagefinancecostsegment.FieldCostAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostAmount(); ok {
		_spec.AddField(usagefinancecostsegment.FieldCostAmount, field.TypeFloat64, value)
	}
	if _u.mutation.CostAmountCleared() {
		_spec.ClearField(usagefinancecostsegment.FieldCostAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CalculationDetail(); ok {
		_spec.SetField(usagefinancecostsegment.FieldCalculationDetail, field.TypeJSON, value)
	}
	_node = &UsageFinanceCostSegment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagefinancecostsegment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
