// Code generated by ent, DO NOT EDIT.

package accountupstreammultiplierchange

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldAccountID, v))
}

// OldMultiplier applies equality check predicate on the "old_multiplier" field. It's identical to OldMultiplierEQ.
func OldMultiplier(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldOldMultiplier, v))
}

// NewMultiplier applies equality check predicate on the "new_multiplier" field. It's identical to NewMultiplierEQ.
func NewMultiplier(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldNewMultiplier, v))
}

// ChangeType applies equality check predicate on the "change_type" field. It's identical to ChangeTypeEQ.
func ChangeType(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldChangeType, v))
}

// EffectiveAt applies equality check predicate on the "effective_at" field. It's identical to EffectiveAtEQ.
func EffectiveAt(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldEffectiveAt, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldOperatorID, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldCreatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLTE(FieldAccountID, v))
}

// OldMultiplierEQ applies the EQ predicate on the "old_multiplier" field.
func OldMultiplierEQ(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldOldMultiplier, v))
}

// OldMultiplierNEQ applies the NEQ predicate on the "old_multiplier" field.
func OldMultiplierNEQ(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNEQ(FieldOldMultiplier, v))
}

// OldMultiplierIn applies the In predicate on the "old_multiplier" field.
func OldMultiplierIn(vs ...decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIn(FieldOldMultiplier, vs...))
}

// OldMultiplierNotIn applies the NotIn predicate on the "old_multiplier" field.
func OldMultiplierNotIn(vs ...decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotIn(FieldOldMultiplier, vs...))
}

// OldMultiplierGT applies the GT predicate on the "old_multiplier" field.
func OldMultiplierGT(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGT(FieldOldMultiplier, v))
}

// OldMultiplierGTE applies the GTE predicate on the "old_multiplier" field.
func OldMultiplierGTE(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGTE(FieldOldMultiplier, v))
}

// OldMultiplierLT applies the LT predicate on the "old_multiplier" field.
func OldMultiplierLT(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLT(FieldOldMultiplier, v))
}

// OldMultiplierLTE applies the LTE predicate on the "old_multiplier" field.
func OldMultiplierLTE(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLTE(FieldOldMultiplier, v))
}

// OldMultiplierIsNil applies the IsNil predicate on the "old_multiplier" field.
func OldMultiplierIsNil() predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIsNull(FieldOldMultiplier))
}

// OldMultiplierNotNil applies the NotNil predicate on the "old_multiplier" field.
func OldMultiplierNotNil() predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotNull(FieldOldMultiplier))
}

// NewMultiplierEQ applies the EQ predicate on the "new_multiplier" field.
func NewMultiplierEQ(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldNewMultiplier, v))
}

// NewMultiplierNEQ applies the NEQ predicate on the "new_multiplier" field.
func NewMultiplierNEQ(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNEQ(FieldNewMultiplier, v))
}

// NewMultiplierIn applies the In predicate on the "new_multiplier" field.
func NewMultiplierIn(vs ...decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIn(FieldNewMultiplier, vs...))
}

// NewMultiplierNotIn applies the NotIn predicate on the "new_multiplier" field.
func NewMultiplierNotIn(vs ...decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotIn(FieldNewMultiplier, vs...))
}

// NewMultiplierGT applies the GT predicate on the "new_multiplier" field.
func NewMultiplierGT(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGT(FieldNewMultiplier, v))
}

// NewMultiplierGTE applies the GTE predicate on the "new_multiplier" field.
func NewMultiplierGTE(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGTE(FieldNewMultiplier, v))
}

// NewMultiplierLT applies the LT predicate on the "new_multiplier" field.
func NewMultiplierLT(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLT(FieldNewMultiplier, v))
}

// NewMultiplierLTE applies the LTE predicate on the "new_multiplier" field.
func NewMultiplierLTE(v decimal.Decimal) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLTE(FieldNewMultiplier, v))
}

// ChangeTypeEQ applies the EQ predicate on the "change_type" field.
func ChangeTypeEQ(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldChangeType, v))
}

// ChangeTypeNEQ applies the NEQ predicate on the "change_type" field.
func ChangeTypeNEQ(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNEQ(FieldChangeType, v))
}

// ChangeTypeIn applies the In predicate on the "change_type" field.
func ChangeTypeIn(vs ...string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIn(FieldChangeType, vs...))
}

// ChangeTypeNotIn applies the NotIn predicate on the "change_type" field.
func ChangeTypeNotIn(vs ...string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotIn(FieldChangeType, vs...))
}

// ChangeTypeGT applies the GT predicate on the "change_type" field.
func ChangeTypeGT(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGT(FieldChangeType, v))
}

// ChangeTypeGTE applies the GTE predicate on the "change_type" field.
func ChangeTypeGTE(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGTE(FieldChangeType, v))
}

// ChangeTypeLT applies the LT predicate on the "change_type" field.
func ChangeTypeLT(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLT(FieldChangeType, v))
}

// ChangeTypeLTE applies the LTE predicate on the "change_type" field.
func ChangeTypeLTE(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLTE(FieldChangeType, v))
}

// ChangeTypeContains applies the Contains predicate on the "change_type" field.
func ChangeTypeContains(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldContains(FieldChangeType, v))
}

// ChangeTypeHasPrefix applies the HasPrefix predicate on the "change_type" field.
func ChangeTypeHasPrefix(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldHasPrefix(FieldChangeType, v))
}

// ChangeTypeHasSuffix applies the HasSuffix predicate on the "change_type" field.
func ChangeTypeHasSuffix(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldHasSuffix(FieldChangeType, v))
}

// ChangeTypeEqualFold applies the EqualFold predicate on the "change_type" field.
func ChangeTypeEqualFold(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEqualFold(FieldChangeType, v))
}

// ChangeTypeContainsFold applies the ContainsFold predicate on the "change_type" field.
func ChangeTypeContainsFold(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldContainsFold(FieldChangeType, v))
}

// EffectiveAtEQ applies the EQ predicate on the "effective_at" field.
func EffectiveAtEQ(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldEffectiveAt, v))
}

// EffectiveAtNEQ applies the NEQ predicate on the "effective_at" field.
func EffectiveAtNEQ(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNEQ(FieldEffectiveAt, v))
}

// EffectiveAtIn applies the In predicate on the "effective_at" field.
func EffectiveAtIn(vs ...time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIn(FieldEffectiveAt, vs...))
}

// EffectiveAtNotIn applies the NotIn predicate on the "effective_at" field.
func EffectiveAtNotIn(vs ...time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotIn(FieldEffectiveAt, vs...))
}

// EffectiveAtGT applies the GT predicate on the "effective_at" field.
func EffectiveAtGT(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGT(FieldEffectiveAt, v))
}

// EffectiveAtGTE applies the GTE predicate on the "effective_at" field.
func EffectiveAtGTE(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGTE(FieldEffectiveAt, v))
}

// EffectiveAtLT applies the LT predicate on the "effective_at" field.
func EffectiveAtLT(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLT(FieldEffectiveAt, v))
}

// EffectiveAtLTE applies the LTE predicate on the "effective_at" field.
func EffectiveAtLTE(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLTE(FieldEffectiveAt, v))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDGT applies the GT predicate on the "operator_id" field.
func OperatorIDGT(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGT(FieldOperatorID, v))
}

// OperatorIDGTE applies the GTE predicate on the "operator_id" field.
func OperatorIDGTE(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGTE(FieldOperatorID, v))
}

// OperatorIDLT applies the LT predicate on the "operator_id" field.
func OperatorIDLT(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLT(FieldOperatorID, v))
}

// OperatorIDLTE applies the LTE predicate on the "operator_id" field.
func OperatorIDLTE(v int64) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLTE(FieldOperatorID, v))
}

// OperatorIDIsNil applies the IsNil predicate on the "operator_id" field.
func OperatorIDIsNil() predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIsNull(FieldOperatorID))
}

// OperatorIDNotNil applies the NotNil predicate on the "operator_id" field.
func OperatorIDNotNil() predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotNull(FieldOperatorID))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldContainsFold(FieldReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountUpstreamMultiplierChange) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountUpstreamMultiplierChange) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountUpstreamMultiplierChange) predicate.AccountUpstreamMultiplierChange {
	return predicate.AccountUpstreamMultiplierChange(sql.NotPredicates(p))
}
