// Code generated by ent, DO NOT EDIT.

package financefxrateversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the financefxrateversion type in the database.
	Label = "finance_fx_rate_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldRateToUsd holds the string denoting the rate_to_usd field in the database.
	FieldRateToUsd = "rate_to_usd"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldObservedAt holds the string denoting the observed_at field in the database.
	FieldObservedAt = "observed_at"
	// FieldEffectiveFrom holds the string denoting the effective_from field in the database.
	FieldEffectiveFrom = "effective_from"
	// FieldEffectiveTo holds the string denoting the effective_to field in the database.
	FieldEffectiveTo = "effective_to"
	// FieldChecksum holds the string denoting the checksum field in the database.
	FieldChecksum = "checksum"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the financefxrateversion in the database.
	Table = "finance_fx_rate_versions"
)

// Columns holds all SQL columns for financefxrateversion fields.
var Columns = []string{
	FieldID,
	FieldCurrency,
	FieldRateToUsd,
	FieldSource,
	FieldObservedAt,
	FieldEffectiveFrom,
	FieldEffectiveTo,
	FieldChecksum,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// ChecksumValidator is a validator for the "checksum" field. It is called by the builders before save.
	ChecksumValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the FinanceFXRateVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByRateToUsd orders the results by the rate_to_usd field.
func ByRateToUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateToUsd, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByObservedAt orders the results by the observed_at field.
func ByObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedAt, opts...).ToFunc()
}

// ByEffectiveFrom orders the results by the effective_from field.
func ByEffectiveFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveFrom, opts...).ToFunc()
}

// ByEffectiveTo orders the results by the effective_to field.
func ByEffectiveTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveTo, opts...).ToFunc()
}

// ByChecksum orders the results by the checksum field.
func ByChecksum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChecksum, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
