// Code generated by ent, DO NOT EDIT.

package accountfinancecountersnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountfinancecountersnapshot type in the database.
	Label = "account_finance_counter_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountFinanceProfileID holds the string denoting the account_finance_profile_id field in the database.
	FieldAccountFinanceProfileID = "account_finance_profile_id"
	// FieldScopeKey holds the string denoting the scope_key field in the database.
	FieldScopeKey = "scope_key"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldUpstreamCounterID holds the string denoting the upstream_counter_id field in the database.
	FieldUpstreamCounterID = "upstream_counter_id"
	// FieldCounterPeriod holds the string denoting the counter_period field in the database.
	FieldCounterPeriod = "counter_period"
	// FieldListCostTotal holds the string denoting the list_cost_total field in the database.
	FieldListCostTotal = "list_cost_total"
	// FieldActualCostTotal holds the string denoting the actual_cost_total field in the database.
	FieldActualCostTotal = "actual_cost_total"
	// FieldUnitCode holds the string denoting the unit_code field in the database.
	FieldUnitCode = "unit_code"
	// FieldUnitSemantics holds the string denoting the unit_semantics field in the database.
	FieldUnitSemantics = "unit_semantics"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldUpstreamObservedAt holds the string denoting the upstream_observed_at field in the database.
	FieldUpstreamObservedAt = "upstream_observed_at"
	// FieldCollectedAt holds the string denoting the collected_at field in the database.
	FieldCollectedAt = "collected_at"
	// FieldSafeSnapshot holds the string denoting the safe_snapshot field in the database.
	FieldSafeSnapshot = "safe_snapshot"
	// FieldChecksum holds the string denoting the checksum field in the database.
	FieldChecksum = "checksum"
	// FieldPreviousSnapshotID holds the string denoting the previous_snapshot_id field in the database.
	FieldPreviousSnapshotID = "previous_snapshot_id"
	// FieldListCostDelta holds the string denoting the list_cost_delta field in the database.
	FieldListCostDelta = "list_cost_delta"
	// FieldActualCostDelta holds the string denoting the actual_cost_delta field in the database.
	FieldActualCostDelta = "actual_cost_delta"
	// FieldObservedMultiplier holds the string denoting the observed_multiplier field in the database.
	FieldObservedMultiplier = "observed_multiplier"
	// FieldDerivationStatus holds the string denoting the derivation_status field in the database.
	FieldDerivationStatus = "derivation_status"
	// FieldAnomalyCode holds the string denoting the anomaly_code field in the database.
	FieldAnomalyCode = "anomaly_code"
	// FieldMultiplierChangeID holds the string denoting the multiplier_change_id field in the database.
	FieldMultiplierChangeID = "multiplier_change_id"
	// FieldMultiplierEffectiveAt holds the string denoting the multiplier_effective_at field in the database.
	FieldMultiplierEffectiveAt = "multiplier_effective_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the accountfinancecountersnapshot in the database.
	Table = "account_finance_counter_snapshots"
)

// Columns holds all SQL columns for accountfinancecountersnapshot fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldAccountFinanceProfileID,
	FieldScopeKey,
	FieldIdempotencyKey,
	FieldUpstreamCounterID,
	FieldCounterPeriod,
	FieldListCostTotal,
	FieldActualCostTotal,
	FieldUnitCode,
	FieldUnitSemantics,
	FieldCurrency,
	FieldUpstreamObservedAt,
	FieldCollectedAt,
	FieldSafeSnapshot,
	FieldChecksum,
	FieldPreviousSnapshotID,
	FieldListCostDelta,
	FieldActualCostDelta,
	FieldObservedMultiplier,
	FieldDerivationStatus,
	FieldAnomalyCode,
	FieldMultiplierChangeID,
	FieldMultiplierEffectiveAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ScopeKeyValidator is a validator for the "scope_key" field. It is called by the builders before save.
	ScopeKeyValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// UpstreamCounterIDValidator is a validator for the "upstream_counter_id" field. It is called by the builders before save.
	UpstreamCounterIDValidator func(string) error
	// CounterPeriodValidator is a validator for the "counter_period" field. It is called by the builders before save.
	CounterPeriodValidator func(string) error
	// UnitCodeValidator is a validator for the "unit_code" field. It is called by the builders before save.
	UnitCodeValidator func(string) error
	// UnitSemanticsValidator is a validator for the "unit_semantics" field. It is called by the builders before save.
	UnitSemanticsValidator func(string) error
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// ChecksumValidator is a validator for the "checksum" field. It is called by the builders before save.
	ChecksumValidator func(string) error
	// DerivationStatusValidator is a validator for the "derivation_status" field. It is called by the builders before save.
	DerivationStatusValidator func(string) error
	// AnomalyCodeValidator is a validator for the "anomaly_code" field. It is called by the builders before save.
	AnomalyCodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AccountFinanceCounterSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountFinanceProfileID orders the results by the account_finance_profile_id field.
func ByAccountFinanceProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountFinanceProfileID, opts...).ToFunc()
}

// ByScopeKey orders the results by the scope_key field.
func ByScopeKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeKey, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByUpstreamCounterID orders the results by the upstream_counter_id field.
func ByUpstreamCounterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamCounterID, opts...).ToFunc()
}

// ByCounterPeriod orders the results by the counter_period field.
func ByCounterPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCounterPeriod, opts...).ToFunc()
}

// ByListCostTotal orders the results by the list_cost_total field.
func ByListCostTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldListCostTotal, opts...).ToFunc()
}

// ByActualCostTotal orders the results by the actual_cost_total field.
func ByActualCostTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCostTotal, opts...).ToFunc()
}

// ByUnitCode orders the results by the unit_code field.
func ByUnitCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitCode, opts...).ToFunc()
}

// ByUnitSemantics orders the results by the unit_semantics field.
func ByUnitSemantics(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitSemantics, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByUpstreamObservedAt orders the results by the upstream_observed_at field.
func ByUpstreamObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamObservedAt, opts...).ToFunc()
}

// ByCollectedAt orders the results by the collected_at field.
func ByCollectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectedAt, opts...).ToFunc()
}

// ByChecksum orders the results by the checksum field.
func ByChecksum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChecksum, opts...).ToFunc()
}

// ByPreviousSnapshotID orders the results by the previous_snapshot_id field.
func ByPreviousSnapshotID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousSnapshotID, opts...).ToFunc()
}

// ByListCostDelta orders the results by the list_cost_delta field.
func ByListCostDelta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldListCostDelta, opts...).ToFunc()
}

// ByActualCostDelta orders the results by the actual_cost_delta field.
func ByActualCostDelta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCostDelta, opts...).ToFunc()
}

// ByObservedMultiplier orders the results by the observed_multiplier field.
func ByObservedMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedMultiplier, opts...).ToFunc()
}

// ByDerivationStatus orders the results by the derivation_status field.
func ByDerivationStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDerivationStatus, opts...).ToFunc()
}

// ByAnomalyCode orders the results by the anomaly_code field.
func ByAnomalyCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnomalyCode, opts...).ToFunc()
}

// ByMultiplierChangeID orders the results by the multiplier_change_id field.
func ByMultiplierChangeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMultiplierChangeID, opts...).ToFunc()
}

// ByMultiplierEffectiveAt orders the results by the multiplier_effective_at field.
func ByMultiplierEffectiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMultiplierEffectiveAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
